/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEFoundation/IDELocalizationStream.h>

@interface _IDELocalizationStreamMap : IDELocalizationStream
{
    BOOL _shouldComplete;
    id <IDELocalizationStreamPublisher> _publisher;
    id _work;
    unsigned long long _outstandingWork;
}

+ (id)withPublisher:(id)arg1 withWork:(id)arg2;
- (void).cxx_destruct;
- (void)onCompleted;
- (void)onError:(id)arg1;
- (void)onNext:(id)arg1;
@property unsigned long long outstandingWork; // @synthesize outstandingWork=_outstandingWork;
@property(retain) id <IDELocalizationStreamPublisher> publisher; // @synthesize publisher=_publisher;
@property BOOL shouldComplete; // @synthesize shouldComplete=_shouldComplete;
@property(copy) id work; // @synthesize work=_work;
- (id)subscribe:(id)arg1;

@end

