/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEFoundation/IDELocalizationStream.h>

@interface _IDELocalizationStreamConcat : IDELocalizationStream
{
    id <IDELocalizationStreamPublisher> _first;
    id <IDELocalizationStreamPublisher> _second;
}

+ (id)withFirst:(id)arg1 second:(id)arg2;
- (void).cxx_destruct;
@property(retain) id <IDELocalizationStreamPublisher> first; // @synthesize first=_first;
- (void)onCompleted;
- (void)onError:(id)arg1;
- (void)onNext:(id)arg1;
@property(retain) id <IDELocalizationStreamPublisher> second; // @synthesize second=_second;
- (id)subscribe:(id)arg1;

@end

