/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEFoundation/IDELocalizationStream.h>

@class NSMutableArray;

@interface _IDELocalizationStreamReturn : IDELocalizationStream
{
    NSMutableArray *_remainingDataToPublish;
}

+ (id)withArray:(id)arg1;
- (void).cxx_destruct;
- (void)_next;
- (void)onCompleted;
- (void)onNext:(id)arg1;
@property(retain) NSMutableArray *remainingDataToPublish; // @synthesize remainingDataToPublish=_remainingDataToPublish;
- (id)subscribe:(id)arg1;

@end

