/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEFoundation/IDEActivityLogChangeEvent.h>

@class NSString;

@interface IDEActivityLogAppendTextChangeEvent : IDEActivityLogChangeEvent
{
    NSString *_textString;
}

- (void).cxx_destruct;
- (id)description;
- (id)initWithSection:(id)arg1 textString:(id)arg2;
@property(readonly) NSString *textString; // @synthesize textString=_textString;

@end

