/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@interface IDEAppExtensionConfiguration : NSObject
{
}

+ (int)actionForExtensionIdentifier:(id)arg1 platformFamily:(id)arg2;
+ (id)applicationBundleIdentifiersForExtension:(id)arg1 platformFamily:(id)arg2;
+ (void)initialize;
+ (int)modeForExtensionIdentifier:(id)arg1 platformFamily:(id)arg2;

@end

