/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEFoundation/IDEArchivedContent.h>

@class DVTFilePath;

@interface IDEArchivedInAppContent : IDEArchivedContent
{
}

+ (id)archivedContentPathPlistKey;
+ (id)archivedContentPropertiesPlistKey;
+ (BOOL)fillInfoDictionary:(id)arg1 forContentAtPath:(id)arg2 inArchiveProductsDirectory:(id)arg3;
+ (id)keyPathsForValuesAffectingInAppContentPath;
+ (id)soleArchivedContentRelativePathInDirectory:(id)arg1;
- (long long)autodetectedFormatForPackaging;
@property(readonly) DVTFilePath *inAppContentPath;
- (id)packager;
- (BOOL)supportsPackagingAsFormat:(long long)arg1;

@end

