/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class IDEBuilder, NSString;

@interface IDEBuildFolder : NSObject
{
    NSString *_path;
    IDEBuilder *_currentBuilder;
}

+ (id)sharedBuildFolderWithPath:(id)arg1 error:(id *)arg2;
- (void).cxx_destruct;
@property(retain) IDEBuilder *currentBuilder; // @synthesize currentBuilder=_currentBuilder;
- (void)dealloc;
- (id)description;
- (id)init;
- (id)initWithPath:(id)arg1 error:(id *)arg2;
@property(readonly) NSString *path; // @synthesize path=_path;
- (void)registerCurrentBuilder:(id)arg1;
- (void)unregisterCurrentBuilder:(id)arg1;

@end

