/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "DVTXMLUnarchiving.h"

@class NSArray, NSMutableArray, NSString;

@interface IDEBreakpointAction : NSObject <DVTXMLUnarchiving>
{
    NSString *_displayName;
    NSArray *_expressions;
    BOOL _displayable;
    BOOL _displyable;
}

+ (id)_expandMacrosInString:(id)arg1 usingBreakpoint:(id)arg2;
+ (id)_expressionsInString:(id)arg1;
+ (id)_replace:(id)arg1 with:(id)arg2 inString:(id)arg3;
+ (void)initialize;
+ (id)propertiesAffectingPersistenceState;
- (void).cxx_destruct;
- (void)_breakpointActionCommonInit;
- (id)_expandExpressionsInString:(id)arg1;
- (void)clearExpressions;
@property(copy) NSString *displayName; // @synthesize displayName=_displayName;
- (id)expandExpressionsAndMacrosInString:(id)arg1 usingBreakpoint:(id)arg2;
- (void)extractAndAddExpressionsFromString:(id)arg1;
- (void)extractAndSetExpressionsFromString:(id)arg1;
- (BOOL)haveExpressionsBeenEvaluated;
- (id)init;
- (id)initFromXMLUnarchiver:(id)arg1 archiveVersion:(float)arg2;
@property(getter=isDisplayable) BOOL displayable; // @synthesize displayable=_displyable;
- (void)performActionUsingContext:(id)arg1 andBreakpoint:(id)arg2;
- (void)resetExpressionResults;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(copy) NSArray *expressions; // @dynamic expressions;
@property(readonly) unsigned long long hash;
@property(readonly) NSMutableArray *mutableExpressions; // @dynamic mutableExpressions;
@property(readonly) Class superclass;

@end

