/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "DVTInvalidation.h"

@class DVTStackBacktrace, NSString;

@interface IDEBuildableSupportMixIn : NSObject <DVTInvalidation>
{
    id <IDEBuildable> _buildable;
    BOOL _hasRecursiveDependencyCycle;
}

+ (void)initialize;
- (void).cxx_destruct;
- (BOOL)hasRecursiveDependencyCycle;
- (id)initWithBuildable:(id)arg1;
- (id)orderedRecursiveDependenciesIncludingSelf:(BOOL)arg1;
- (void)primitiveInvalidate;
- (id)uncachedOrderedRecursiveDependenciesIncludingSelf:(BOOL)arg1 visitedBuildables:(id)arg2;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

