/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "DVTInvalidation.h"

@class DVTStackBacktrace, NSAttributedString, NSString;

@interface IDEBatchFindHistoryItem : NSObject <DVTInvalidation>
{
    NSAttributedString *_findAttributedString;
    NSAttributedString *_itemDescription;
    id _payload;
    int _findType;
}

+ (void)initialize;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
@property(readonly) NSAttributedString *findAttributedString; // @synthesize findAttributedString=_findAttributedString;
@property(readonly) int findType; // @synthesize findType=_findType;
@property(readonly) unsigned long long hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithFindAttributedString:(id)arg1 description:(id)arg2 payload:(id)arg3 findType:(int)arg4;
- (BOOL)isEqual:(id)arg1;
@property(readonly) NSAttributedString *itemDescription; // @synthesize itemDescription=_itemDescription;
@property(retain, nonatomic) id payload; // @synthesize payload=_payload;
- (void)primitiveInvalidate;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

