/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "IDETestingSpecifier.h"

@class DVTObservingToken, IDEDeviceAppDataReference, IDELocationScenarioReference, NSArray, NSMutableArray, NSString;

@interface IDEConcreteTestingSpecifier : NSObject <IDETestingSpecifier>
{
    id <IDETestable> _testable;
    NSMutableArray *_skippedTests;
    IDEDeviceAppDataReference *_deviceAppDataReference;
    IDELocationScenarioReference *_locationScenarioReference;
    DVTObservingToken *_buildableValidityObservingToken;
    BOOL _skipped;
}

+ (void)initialize;
- (void).cxx_destruct;
@property(retain) IDEDeviceAppDataReference *deviceAppDataReference;
- (id)initWithTestable:(id)arg1;
@property(retain) IDELocationScenarioReference *locationScenarioReference;
@property BOOL skipped;
- (id)testable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) NSMutableArray *mutableSkippedTests; // @dynamic mutableSkippedTests;
@property(copy) NSArray *skippedTests; // @dynamic skippedTests;
@property(readonly) Class superclass;

@end

