/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEFoundation/IDEScriptingWrapper.h>

@interface IDEContainerItemWrapper : IDEScriptingWrapper
{
}

- (id)project;
- (id)scriptingContainer;
- (id)scriptingID;
- (void)setProject:(id)arg1;
- (void)setScriptingContainer:(id)arg1;
- (void)setScriptingID:(id)arg1;

@end

