/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "IDEContainerCore.h"

@class DVTExtension, DVTFilePath, DVTStackBacktrace, NSString;

@interface IDEContainerCore : NSObject <IDEContainerCore>
{
    DVTFilePath *_filePath;
    DVTExtension *_containerExtension;
    int _currentActivity;
}

+ (BOOL)_closeContainerCoreIfNeeded:(id)arg1;
+ (unsigned long long)_countForContainerCore:(id)arg1;
+ (void)_decrementCountForContainerCore:(id)arg1;
+ (void)_incrementCountForContainerCore:(id)arg1;
+ (void)_invalidateContainerCore:(id)arg1;
+ (id)_openContainerCores;
+ (void)_releaseContainerCore:(id)arg1;
+ (void)_removeReferencesToContainerCore:(id)arg1;
+ (void)_retainContainerCore:(id)arg1;
+ (id)containerDataFilePathsForFilePath:(id)arg1;
+ (id)containerExtensionForFileDataType:(id)arg1;
+ (id)containerFileType;
+ (void)initialize;
+ (BOOL)isContainerCoreOpenForFilePath:(id)arg1;
+ (id)retainedContainerCoreAtFilePath:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
+ (id)retainedContainerCoreForFilePath:(id)arg1;
+ (BOOL)supportsFilePersistence;
- (void).cxx_destruct;
- (void)_saveContainerCoreIfNeeded;
- (id)containerExtension;
- (int)currentActivity;
- (id)filePath;
- (id)init;
- (id)initWithFilePath:(id)arg1 extension:(id)arg2 error:(id *)arg3;
- (void)primitiveInvalidate;
- (void)releaseContainerCore;
- (void)retainContainerCore;
- (id)rootGroup;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

