/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class DVTFilePath, NSString;

@interface IDECodeModule : NSObject
{
    BOOL _isInBuiltProductDirectories;
    int _debugSymbolsLoadState;
    DVTFilePath *_filePath;
    NSString *_name;
    NSString *_frameworkNameIncludingExtension;
    NSString *_identifier;
    unsigned long long _address;
    NSString *_displayAddress;
    NSString *_path;
}

+ (id)frameworkNameIncludingExtensionFromPath:(id)arg1;
- (void).cxx_destruct;
@property unsigned long long address; // @synthesize address=_address;
@property int debugSymbolsLoadState; // @synthesize debugSymbolsLoadState=_debugSymbolsLoadState;
@property(readonly, nonatomic) NSString *displayAddress; // @synthesize displayAddress=_displayAddress;
@property(retain) DVTFilePath *filePath; // @synthesize filePath=_filePath;
@property(readonly, copy) NSString *frameworkNameIncludingExtension; // @synthesize frameworkNameIncludingExtension=_frameworkNameIncludingExtension;
- (unsigned long long)hash;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (id)initWithIdentifier:(id)arg1 pathString:(id)arg2;
- (BOOL)isEqual:(id)arg1;
@property(nonatomic) BOOL isInBuiltProductDirectories; // @synthesize isInBuiltProductDirectories=_isInBuiltProductDirectories;
@property(readonly, copy) NSString *name; // @synthesize name=_name;
@property(readonly, nonatomic) NSString *path; // @synthesize path=_path;

@end

