/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "DVTInvalidation.h"

@class DVTStackBacktrace, IDEActivityLogSectionRecorder, IDELogStore, NSArray, NSString;

@interface IDEDeviceInstallWorkspaceMonitor : NSObject <DVTInvalidation>
{
    NSString *_appName;
    IDELogStore *_logStore;
    IDEActivityLogSectionRecorder *_logRecorder;
    IDEActivityLogSectionRecorder *_logSectionRecorder;
    NSString *_resultError;
}

+ (void)initialize;
+ (id)keyPathsForValuesAffectingLogRecords;
- (void).cxx_destruct;
- (void)addOperationToActivityLog:(id)arg1 details:(id)arg2;
@property(retain) NSString *appName; // @synthesize appName=_appName;
- (void)loadDeviceInstallLogsForWorkspace:(id)arg1;
@property(retain) IDEActivityLogSectionRecorder *logRecorder; // @synthesize logRecorder=_logRecorder;
@property(readonly) NSArray *logRecords;
@property(retain) IDEActivityLogSectionRecorder *logSectionRecorder; // @synthesize logSectionRecorder=_logSectionRecorder;
@property(retain) IDELogStore *logStore; // @synthesize logStore=_logStore;
- (void)primitiveInvalidate;
@property(retain) NSString *resultError; // @synthesize resultError=_resultError;
- (void)setResultErrorString:(id)arg1;
- (void)startActivityLogForAppNamed:(id)arg1 deviceNamed:(id)arg2;
- (void)stopActivityLog;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

