/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEFoundation/IDEDistributionProcessingStep.h>

@interface IDEDistributionSkipPackagingStep : IDEDistributionProcessingStep
{
}

+ (id)processingStep;
- (_Bool)processWithContext:(id)arg1 andError:(id *)arg2;

@end

