/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class DVTMutableOrderedDictionary, IDEDistributionItemSigningInfo;

@interface IDEDistributionProvisioningSnapshot : NSObject
{
    DVTMutableOrderedDictionary *_itemToSigningInfoMap;
    IDEDistributionItemSigningInfo *_installerSigningInfo;
}

- (void).cxx_destruct;
- (id)description;
@property(retain) IDEDistributionItemSigningInfo *installerSigningInfo; // @synthesize installerSigningInfo=_installerSigningInfo;
@property(retain) DVTMutableOrderedDictionary *itemToSigningInfoMap; // @synthesize itemToSigningInfoMap=_itemToSigningInfoMap;

@end

