/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class DVTExtension, IDEDistributionItem, NSArray, NSString;

@interface IDEDistributionProcessingStep : NSObject
{
    DVTExtension *_extension;
    _Bool _supportsDryRun;
    IDEDistributionItem *_distributionItem;
    NSArray *_inputs;
    NSArray *_outputs;
}

+ (id)processingStepWithExtension:(id)arg1;
+ (id)processingStepWithExtension:(id)arg1 andDistributionItem:(id)arg2;
- (void).cxx_destruct;
@property(readonly) IDEDistributionItem *distributionItem; // @synthesize distributionItem=_distributionItem;
- (id)initWithExtension:(id)arg1 andDistributionItem:(id)arg2;
@property(copy) NSArray *inputs; // @synthesize inputs=_inputs;
- (_Bool)isAllowedInput:(id)arg1;
- (_Bool)isAllowedOutput:(id)arg1;
- (_Bool)isRequiredInput:(id)arg1;
@property(readonly, copy) NSString *name;
@property(copy) NSArray *outputs; // @synthesize outputs=_outputs;
- (_Bool)processWithContext:(id)arg1 andError:(id *)arg2;
- (id)requiredInputs;
@property(readonly) _Bool supportsDryRun; // @synthesize supportsDryRun=_supportsDryRun;

@end

