/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "DVTXMLUnarchiving.h"

@class IDEScheme, NSDictionary, NSString;

@interface IDEExecutionAction : NSObject <DVTXMLUnarchiving>
{
    NSString *_title;
    IDEScheme *_runContext;
}

+ (id)actionType;
- (void).cxx_destruct;
@property(readonly) NSDictionary *actionEnvironmentVariables;
- (void)dvt_encodeAttributesWithXMLArchiver:(id)arg1 version:(id)arg2;
- (id)initFromXMLUnarchiver:(id)arg1 archiveVersion:(float)arg2;
@property(readonly) BOOL needsCurrentArchiveVersion;
- (id)operationForExecutionWithBuildParameters:(id)arg1 error:(id *)arg2;
@property(retain) IDEScheme *runContext; // @synthesize runContext=_runContext;
- (void)schemeObjectGraphSetupComplete;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void)setTitleFromUTF8String:(char *)arg1 fromXMLUnarchiver:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

