/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class DVTFilePath, IDELaunchSession, NSArray, NSError, NSMutableArray, NSString;

@interface IDEExecutionTracker : NSObject
{
    NSString *_statusDisplayName;
    DVTFilePath *_statusImageFilePath;
    IDELaunchSession *_launchSession;
    NSMutableArray *_subtrackers;
    BOOL _isFinished;
    int _serviceTier;
    int _cancellationReason;
    NSError *_error;
    NSString *_debugName;
}

+ (void)initialize;
- (void).cxx_destruct;
- (void)_updateIsFinished;
- (void)addSubtracker:(id)arg1;
- (void)cancel;
- (void)cancelWithReason:(int)arg1;
@property int cancellationReason; // @synthesize cancellationReason=_cancellationReason;
@property(copy) NSString *debugName; // @synthesize debugName=_debugName;
- (id)description;
@property(retain) NSError *error; // @synthesize error=_error;
- (id)init;
@property BOOL isFinished; // @synthesize isFinished=_isFinished;
@property(retain) IDELaunchSession *launchSession; // @synthesize launchSession=_launchSession;
@property int serviceTier; // @synthesize serviceTier=_serviceTier;
@property(retain) NSString *statusDisplayName; // @synthesize statusDisplayName=_statusDisplayName;
- (void)setStatusDisplayName:(id)arg1 statusImageFilePath:(id)arg2;
@property(retain) DVTFilePath *statusImageFilePath; // @synthesize statusImageFilePath=_statusImageFilePath;
@property(readonly) BOOL statusChanged;

// Remaining properties
@property(readonly) NSMutableArray *mutableSubtrackers; // @dynamic mutableSubtrackers;
@property(readonly) NSArray *subtrackers; // @dynamic subtrackers;

@end

