/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSCopying.h"

@class NSSet;

@interface IDEEntitlementsDictionary : NSObject <NSCopying>
{
    _Bool _frozen;
    id _storage;
    IDEEntitlementsDictionary *_parent;
}

+ (id)whiteoutMarker;
- (void).cxx_destruct;
- (void)addEntriesFromDictionary:(id)arg1;
@property(readonly, copy) NSSet *allKeys;
@property(readonly, copy) NSSet *allValues;
- (void)applyDelta:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly) unsigned long long count;
- (id)deltaRepresentation;
- (id)flatRepresentation;
- (void)freeze;
- (unsigned long long)hash;
- (id)init;
- (id)initWithDictionary:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)keyEnumerator;
- (id)mutableChild;
- (id)mutableChildByApplyingDelta:(id)arg1;
- (id)objectEnumerator;
- (id)objectForKey:(id)arg1;
- (id)objectForKeyedSubscript:(id)arg1;
@property(readonly) IDEEntitlementsDictionary *parent; // @synthesize parent=_parent;
- (void)removeAllObjects;
- (void)removeObjectForKey:(id)arg1;
- (void)removeObjectsForKeys:(id)arg1;
- (void)setDictionary:(id)arg1;
- (void)setObject:(id)arg1 forKey:(id)arg2;
- (void)setObject:(id)arg1 forKeyedSubscript:(id)arg2;

@end

