/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class IDEIndexDBTransaction, NSString;

@interface IDEIndexDBFactory : NSObject
{
    IDEIndexDBTransaction *_dbTransaction;
    NSString *_tableName;
    NSString *_columnNames;
    NSString *_values;
    NSString *_insertionSQL;
    struct sqlite3_stmt *_dbStatement;
    long long *_objectIdMap;
    long long _objectIdCount;
    long long _objectCount;
    NSString *_tempTableName;
    NSString *_insertionSQL2;
    struct sqlite3_stmt *_dbStatement2;
}

+ (void)initialize;
- (void).cxx_destruct;
- (void)addObjectId:(long long *)arg1 withBindings:(id)arg2;
- (void)close;
@property(readonly, nonatomic) IDEIndexDBTransaction *dbTransaction; // @synthesize dbTransaction=_dbTransaction;
- (void)dealloc;
- (id)initWithTransaction:(id)arg1 table:(id)arg2 columns:(id)arg3;
@property(readonly, nonatomic) long long objectCount; // @synthesize objectCount=_objectCount;
- (long long)realObjectIdForId:(long long)arg1;

@end

