/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "IDEIndexable.h"

@class NSDictionary, NSString;

@interface IDEIndexableMainThreadProxy : NSObject <IDEIndexable>
{
    id <IDEIndexable> _indexableObject;
    BOOL _respondsToSettingsForFiles;
    NSString *_cachedIdentifier;
    NSString *_cachedIndexName;
    NSDictionary *_cachedSettingsForFiles;
}

- (void).cxx_destruct;
- (id)buildSettingsForMainFile:(id)arg1 workspace:(id)arg2;
- (void)clearCachedBuildSettings;
- (id)containerForIndexables:(id)arg1 rootPaths:(id)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy) NSString *description;
- (id)identifier;
- (id)indexName;
- (id)indexableFiles;
@property(retain) id <IDEIndexable> indexableObject; // @synthesize indexableObject=_indexableObject;
- (id)initWithIndexable:(id)arg1;
- (BOOL)isUnitTest;
- (void)languageOfMainFile:(id)arg1 workspace:(id)arg2 completionBlock:(id)arg3;
- (id)localizedIndexableDescription;
- (void)productHeadersInWorkspace:(id)arg1 withCompletionBlock:(id)arg2;
- (id)productNameWithBuildSetting:(id)arg1 workspace:(id)arg2;
- (id)productType;
- (BOOL)requiresMainThread;
- (void)settingsForFilesInWorkspace:(id)arg1 shouldWriteAuxiliaryFiles:(BOOL)arg2 withCompletionBlock:(id)arg3;
- (BOOL)writeProductHeaders:(id)arg1 toFile:(id)arg2 error:(id *)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(nonatomic) __weak id <IDEIndexable> proxy;
@property(readonly) Class superclass;

@end

