/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEFoundation/IDEIndexContainerSymbol.h>

@interface IDEIndexCategorySymbol : IDEIndexContainerSymbol
{
}

- (id)classMethods;
- (id)instanceMethods;
- (id)instanceVariables;
- (id)properties;
- (id)relatedClass;

@end

