/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSCopying.h"
#import "NSObject.h"

@protocol IDEIndexable <NSObject, NSCopying>
- (id)buildSettingsForMainFile:(id)arg1 workspace:(id)arg2;
- (id)containerForIndexables:(id)arg1 rootPaths:(id)arg2;
- (id)identifier;
- (id)indexName;
- (id)indexableFiles;
- (void)languageOfMainFile:(id)arg1 workspace:(id)arg2 completionBlock:(id)arg3;
- (id)localizedIndexableDescription;
- (void)productHeadersInWorkspace:(id)arg1 withCompletionBlock:(id)arg2;
- (BOOL)requiresMainThread;
- (BOOL)writeProductHeaders:(id)arg1 toFile:(id)arg2 error:(id *)arg3;

@optional
- (void)clearCachedBuildSettings;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (BOOL)isUnitTest;
- (id)productNameWithBuildSetting:(id)arg1 workspace:(id)arg2;
- (id)productType;
@property(nonatomic) __weak id <IDEIndexable> proxy;
- (id)settingsForFile:(id)arg1;
- (void)settingsForFilesInWorkspace:(id)arg1 shouldWriteAuxiliaryFiles:(BOOL)arg2 withCompletionBlock:(id)arg3;
@end

