/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "IDEIndexable.h"

@class NSString;

@interface IDEIndexModulesIndexable : NSObject <IDEIndexable>
{
}

+ (id)sharedInstance;
- (id)buildSettingsForMainFile:(id)arg1 workspace:(id)arg2;
- (id)containerForIndexables:(id)arg1 rootPaths:(id)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)identifier;
- (id)indexName;
- (id)indexableFiles;
- (void)languageOfMainFile:(id)arg1 workspace:(id)arg2 completionBlock:(id)arg3;
- (id)localizedIndexableDescription;
- (void)productHeadersInWorkspace:(id)arg1 withCompletionBlock:(id)arg2;
- (BOOL)requiresMainThread;
- (id)settingsForFile:(id)arg1;
- (BOOL)writeProductHeaders:(id)arg1 toFile:(id)arg2 error:(id *)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(nonatomic) __weak id <IDEIndexable> proxy;
@property(readonly) Class superclass;

@end

