/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol IDELocalizedGroup <NSObject>
- (void)addNewReferenceForLocale:(id)arg1 filePath:(id)arg2 completionBlock:(id)arg3;
- (id)localizedContainer;
- (id)proposedFilePathForLocalization:(id)arg1 fileType:(id)arg2;
- (id)subitemForLocale:(id)arg1;
- (id)subitems;
@end

