/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@interface IDELocalizationWork : NSObject
{
}

+ (id)_addFileReferenceWorkForAddFileReferenceContext:(id)arg1;
+ (id)_addItemAtFilePathToSCM:(id)arg1 workspace:(id)arg2;
+ (id)fileReferenceStreamForName:(id)arg1 directoryPath:(id)arg2 superitem:(id)arg3 target:(id)arg4;
+ (id)groupStreamFromFileReference:(id)arg1 language:(id)arg2;
+ (id)readStringsWorkForContext:(id)arg1;
+ (id)writeStringsWorkForContext:(id)arg1;

@end

