/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "DVTInvalidation.h"

@class DVTObservingToken, DVTStackBacktrace, IDELaunchSession, IDELocation, IDELocationScenario, IDESimulateLocationService, NSOperationQueue, NSString, NSTimer;

@interface IDELocationSimulator : NSObject <DVTInvalidation>
{
    IDELaunchSession *_launchSession;
    IDESimulateLocationService *_service;
    int _state;
    IDELocationScenario *_scenario;
    DVTObservingToken *_debugSessionStateObserver;
    BOOL _playingBack;
    NSTimer *_playbackTimer;
    unsigned long long _currentPlaybackIndex;
    IDELocation *_currentPlaybackLocation;
    double _lastUpdateTime;
    NSOperationQueue *_playbackQueue;
}

+ (void)initialize;
+ (id)locationSimulatorLogAspect;
- (void).cxx_destruct;
- (void)_debugSessionStateChanged;
- (int)_locationSimulatorStateForDebugSessionState:(int)arg1;
- (void)_pausePlayback;
- (void)_playbackTimerFired:(id)arg1;
- (void)_setState:(int)arg1;
- (id)_simulateLocationCapability;
- (void)_startOrResumePlayback;
- (void)_stopPlayback;
- (void)_updateLocationScenario;
- (void)_updateScenarioSimulation;
- (void)_updateService;
- (id)initWithLaunchSession:(id)arg1;
@property(readonly) IDELaunchSession *launchSession; // @synthesize launchSession=_launchSession;
- (void)primitiveInvalidate;
@property(retain, nonatomic) IDELocationScenario *scenario; // @synthesize scenario=_scenario;
@property(retain) IDESimulateLocationService *service; // @synthesize service=_service;
@property(readonly) int state; // @synthesize state=_state;
- (void)stopSimulating;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

