/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEFoundation/IDEOverridingBuildProperties.h>

@class DVTMacroDefinitionTable;

@interface IDEMutableOverridingBuildProperties : IDEOverridingBuildProperties
{
}

@property(copy) DVTMacroDefinitionTable *macrosFromCommandLine;
@property(copy) DVTMacroDefinitionTable *macrosFromCommandLineXcconfigFile;
@property(copy) DVTMacroDefinitionTable *macrosFromEnvironmentXcconfigFile;
- (void)setMacroDefinitionTable:(id)arg1 forLevel:(int)arg2;
@property(copy) DVTMacroDefinitionTable *synthesizedMacros;

@end

