/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEFoundation/IDEOnDiskLogStore.h>

@class NSMutableDictionary, NSOperationQueue, NSString;

@interface IDEOnDiskLogStore_Impl : IDEOnDiskLogStore
{
    NSString *_rootDirectoryPath;
    NSMutableDictionary *_cache;
    NSMutableDictionary *_cachedLogs;
    NSOperationQueue *_asyncOperations;
    BOOL _preserveOldLogs;
}

+ (void)initialize;
- (void).cxx_destruct;
- (id)_cachePath;
- (void)_moveToRootDirectoryAtPath:(id)arg1 errorBlock:(id)arg2;
- (id)_pathForUniqueIdentifier:(id)arg1;
- (void)_pruneLogsToLogStoreSizeLimit;
- (void)_removeAllButTheLatestLog;
- (void)_removeLogRecord:(id)arg1 completionBlock:(id)arg2;
- (BOOL)_saveCacheWithError:(id *)arg1;
- (void)_saveLog:(id)arg1 logRecord:(id)arg2 toPath:(id)arg3 completionBlock:(id)arg4;
- (id)addLog:(id)arg1 entityIdentifier:(id)arg2 completionBlock:(id)arg3;
- (id)description;
- (id)initWithRootDirectoryAtPath:(id)arg1 error:(id *)arg2;
- (BOOL)preserveOldLogs;
- (void)primitiveInvalidate;
- (id)rootDirectoryPath;
- (void)setPreserveOldLogs:(BOOL)arg1;
- (id)testableSummariesPlistFilePathForActivityLogSection:(id)arg1;

@end

