/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class DVTMacroDefinitionTable, NSArray, NSMutableDictionary;

@interface IDEOverridingBuildProperties : NSObject
{
    NSMutableDictionary *_macros;
    NSArray *_arrayRepresentation;
    unsigned long long _hash;
}

- (void).cxx_destruct;
- (id)_copyUsingOverridingPropertiesClass:(Class)arg1;
- (void)_setMacroDefinitionTable:(id)arg1 forLevel:(int)arg2;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)description;
- (id)dvt_detailedDebugDescription;
- (unsigned long long)hash;
- (id)init;
- (id)initWithMacroDefinitionTable:(id)arg1;
- (BOOL)isEmpty;
- (BOOL)isEqual:(id)arg1;
- (id)macroDefinitionTableForLevel:(int)arg1;
- (id)macroDefinitionTables;
@property(readonly, copy) DVTMacroDefinitionTable *macrosFromCommandLine;
@property(readonly, copy) DVTMacroDefinitionTable *macrosFromCommandLineXcconfigFile;
@property(readonly, copy) DVTMacroDefinitionTable *macrosFromEnvironmentXcconfigFile;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
@property(readonly, copy) DVTMacroDefinitionTable *synthesizedMacros;

@end

