/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class DVTRegularExpression, NSArray, NSObject<OS_dispatch_queue>;

@interface IDEOCUnitTestOutputParser : NSObject
{
    id <IDEOCUnitTestOutputParserDelegate> _delegate;
    DVTRegularExpression *_testSuiteStartedRegex;
    DVTRegularExpression *_testSuiteFinishedRegex;
    DVTRegularExpression *_testSuiteExecutedRegex;
    DVTRegularExpression *_testCaseStartedRegex;
    DVTRegularExpression *_testCaseMeasuredPerformanceMetricRegex;
    DVTRegularExpression *_testCaseFinishedRegex;
    DVTRegularExpression *_testCaseFailedRegex;
    NSArray *_performanceTestParsers;
    NSObject<OS_dispatch_queue> *_processingQueue;
    NSObject<OS_dispatch_queue> *_delegateQueue;
    BOOL _outputsToConsole;
}

+ (void)_initializeRegularExpressionsIfNeeded;
+ (BOOL)_initializedForUserInteraction;
- (void).cxx_destruct;
- (void)dealloc;
@property __weak id <IDEOCUnitTestOutputParserDelegate> delegate; // @synthesize delegate=_delegate;
- (id)filterTestSuiteIdentifierFromString:(id)arg1;
- (id)init;
@property BOOL outputsToConsole; // @synthesize outputsToConsole=_outputsToConsole;
- (void)performDelegateBlock:(id)arg1;
- (void)performParserBlock:(id)arg1;
- (void)processConsoleText:(id)arg1;

@end

