/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSFileHandle, NSString;

@interface IDEPseudoTerminal : NSObject
{
    int _masterFD;
    int _slaveFD;
    NSFileHandle *_masterFileHandle;
    NSString *_slaveName;
}

- (void).cxx_destruct;
- (void)_closeMasterFD;
- (BOOL)_openFirstAvailableMasterWithAccessMode:(int)arg1 error:(id *)arg2;
- (int)_openSlaveCounterpart:(int)arg1 error:(id *)arg2;
- (id)initWithAccessMode:(int)arg1 error:(id *)arg2;
- (id)initWithAccessMode:(int)arg1 ownsSlaveFileDescriptor:(BOOL)arg2 error:(id *)arg3;
@property(readonly) NSFileHandle *masterFileHandle; // @synthesize masterFileHandle=_masterFileHandle;
@property(readonly) int slaveFD; // @synthesize slaveFD=_slaveFD;
@property(readonly) NSFileHandle *slaveFileHandle;
@property(readonly) NSString *slaveName; // @synthesize slaveName=_slaveName;

@end

