/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEFoundation/IDERunOperationWorker.h>

@class DVTFilePath, NSMutableDictionary;

@interface IDERunOperationPathWorker : IDERunOperationWorker
{
}

@property(readonly) NSMutableDictionary *compositeEnvironmentVariables;
@property(readonly) DVTFilePath *filePath;

@end

