/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class DVTFilePath, DVTMapTable, NSArray, NSMutableArray, NSString;

@interface IDESchemeActionsInvocationRecord : NSObject
{
    NSMutableArray *_actions;
    NSMutableArray *_warningSummaries;
    NSMutableArray *_errorSummaries;
    NSMutableArray *_analyzerWarningSummaries;
    NSMutableArray *_testFailureSummaries;
    NSMutableArray *_testableSummaries;
    DVTMapTable *_strongActionRecordsToStatusObservers;
    BOOL _running;
    BOOL _archiveFetchable;
    BOOL _productFetchable;
    BOOL _shouldClearExistingFileOnSave;
    BOOL _remoteTestSummaryNeedsFetch;
    DVTFilePath *_archivePath;
    NSString *_archiveName;
    unsigned long long _archiveSize;
    DVTFilePath *_productPath;
    NSString *_productName;
    unsigned long long _productSize;
    unsigned long long _warningCount;
    unsigned long long _errorCount;
    unsigned long long _analyzerWarningCount;
    unsigned long long _testsCount;
    unsigned long long _testsFailedCount;
    DVTFilePath *_creatingWorkspaceFilePath;
    NSString *_archiveGUID;
    NSString *_productGUID;
    DVTFilePath *_filePath;
    id <IDESchemeActionsInvocationRecordUpdateDelegate> _updateDelegate;
    id _remoteTestSummaryIdentifier;
}

+ (BOOL)automaticallyNotifiesObserversOfActions;
+ (void)invocationRecordWithLocalActionResultFilePath:(id)arg1 completionBlock:(id)arg2;
+ (id)keyPathsForValuesAffectingSimpleOperationStatus;
+ (id)keyPathsForValuesAffectingStatus;
+ (BOOL)updateSummariesFromDictionaryRepresentations:(id)arg1 withSummaryOwner:(id)arg2 summaryPropertyName:(id)arg3 summaryiVarArrayRef:(id *)arg4 summariesAreTestFailures:(BOOL)arg5;
- (void).cxx_destruct;
- (id)_init;
- (void)_updateSummaries;
- (void)_updateTestableSummaries;
@property(retain, nonatomic) NSArray *actions; // @synthesize actions=_actions;
@property(nonatomic) unsigned long long analyzerWarningCount; // @synthesize analyzerWarningCount=_analyzerWarningCount;
@property(retain, nonatomic) NSArray *analyzerWarningSummaries; // @synthesize analyzerWarningSummaries=_analyzerWarningSummaries;
@property(retain, nonatomic) NSString *archiveGUID; // @synthesize archiveGUID=_archiveGUID;
@property(retain, nonatomic) NSString *archiveName; // @synthesize archiveName=_archiveName;
@property(retain, nonatomic) DVTFilePath *archivePath; // @synthesize archivePath=_archivePath;
@property(nonatomic) unsigned long long archiveSize; // @synthesize archiveSize=_archiveSize;
- (void)close;
@property(retain, nonatomic) DVTFilePath *creatingWorkspaceFilePath; // @synthesize creatingWorkspaceFilePath=_creatingWorkspaceFilePath;
- (void)dealloc;
- (id)description;
- (id)dictionaryRepresentation;
@property(nonatomic) unsigned long long errorCount; // @synthesize errorCount=_errorCount;
@property(retain, nonatomic) NSArray *errorSummaries; // @synthesize errorSummaries=_errorSummaries;
- (void)fetchLogsAndUpdateRecordWithCompletionBlock:(id)arg1;
- (void)fetchTestSummariesAndUpdateRecordWithCompletionBlock:(id)arg1;
@property(retain, nonatomic) DVTFilePath *filePath; // @synthesize filePath=_filePath;
- (id)filePathForSchemeActionRecordDirectoryWithSchemeCommand:(id)arg1 atIndex:(unsigned long long)arg2;
- (id)init;
- (id)initLocalRecordWithWorkspace:(id)arg1;
- (id)initWithFilePath:(id)arg1 updateDelegate:(id)arg2 error:(id *)arg3;
@property(nonatomic, getter=isArchiveFetchable) BOOL archiveFetchable; // @synthesize archiveFetchable=_archiveFetchable;
@property(nonatomic, getter=isProductFetchable) BOOL productFetchable; // @synthesize productFetchable=_productFetchable;
@property(nonatomic, getter=isRunning) BOOL running; // @synthesize running=_running;
- (id)localTestSummaryFilePath;
- (id)makeActionRecordWithSchemeCommand:(id)arg1 schemeTask:(int)arg2 runDestination:(id)arg3;
@property(retain, nonatomic) NSString *productGUID; // @synthesize productGUID=_productGUID;
@property(retain, nonatomic) NSString *productName; // @synthesize productName=_productName;
@property(retain, nonatomic) DVTFilePath *productPath; // @synthesize productPath=_productPath;
@property(nonatomic) unsigned long long productSize; // @synthesize productSize=_productSize;
@property(copy, nonatomic) id remoteTestSummaryIdentifier; // @synthesize remoteTestSummaryIdentifier=_remoteTestSummaryIdentifier;
@property(nonatomic) BOOL remoteTestSummaryNeedsFetch; // @synthesize remoteTestSummaryNeedsFetch=_remoteTestSummaryNeedsFetch;
- (BOOL)saveTestSummariesWithError:(id *)arg1;
- (void)saveWithCompletionBlock:(id)arg1;
@property(nonatomic) BOOL shouldClearExistingFileOnSave; // @synthesize shouldClearExistingFileOnSave=_shouldClearExistingFileOnSave;
@property(retain, nonatomic) NSArray *testFailureSummaries; // @synthesize testFailureSummaries=_testFailureSummaries;
@property(retain, nonatomic) NSArray *testableSummaries; // @synthesize testableSummaries=_testableSummaries;
@property(nonatomic) unsigned long long testsCount; // @synthesize testsCount=_testsCount;
@property(nonatomic) unsigned long long testsFailedCount; // @synthesize testsFailedCount=_testsFailedCount;
- (void)setUpObserversForSchemeActionRecord:(id)arg1;
@property(nonatomic) unsigned long long warningCount; // @synthesize warningCount=_warningCount;
@property(retain, nonatomic) NSArray *warningSummaries; // @synthesize warningSummaries=_warningSummaries;
@property(readonly, nonatomic) int simpleOperationStatus;
@property(readonly, nonatomic) int status;
- (void)tearDownObserversForSchemeActionRecord:(id)arg1;
- (id)testSummaryFormatVersionString;
- (void)updateAllSchemeActionRecordDirectoryFilePaths;
@property(readonly, nonatomic) id <IDESchemeActionsInvocationRecordUpdateDelegate> updateDelegate; // @synthesize updateDelegate=_updateDelegate;
- (BOOL)updateLocalTestSummaryWithRemoteTestSummary:(id)arg1 error:(id *)arg2;
- (void)updateRecordWithCompletionBlock:(id)arg1;
- (void)updateWithArchiveData:(id)arg1 withCompletionBlock:(id)arg2;
- (BOOL)updateWithDictionaryRepresentation:(id)arg1;
- (void)updateWithProductData:(id)arg1 withCompletionBlock:(id)arg2;

@end

