/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

@protocol IDESchemeActionsInvocationRecordUpdateDelegate
- (void)fetchLogsAndUpdateRecord:(id)arg1 withCompletionBlock:(id)arg2;
- (void)fetchTestSummariesAndUpdateRecord:(id)arg1 withCompletionBlock:(id)arg2;
- (BOOL)shouldActionsInvocationRecord:(id)arg1 refetchRemoteLogForSchemeActionResult:(id)arg2 withOriginalRemoteLogIdentifier:(id)arg3 newRemoteLogIdentifier:(id)arg4;
- (BOOL)shouldActionsInvocationRecord:(id)arg1 refetchRemoteTestSummaryForSchemeActionResult:(id)arg2 withOriginalRemoteTestSummaryIdentifier:(id)arg3 newRemoteTestSummaryIdentifier:(id)arg4;
- (BOOL)shouldActionsInvocationRecord:(id)arg1 refetchRemoteTestSummaryWithOriginalRemoteTestSummaryIdentifier:(id)arg2 newRemoteTestSummaryIdentifier:(id)arg3;
- (void)updateRecord:(id)arg1 withCompletionBlock:(id)arg2;
@end

