/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "DVTDocumentLocation.h"

@class NSString;

@interface IDESourceControlDocumentLocation : DVTDocumentLocation
{
    NSString *_branchName;
    NSString *_revisionName;
}

- (void).cxx_destruct;
@property(readonly) NSString *branchName; // @synthesize branchName=_branchName;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithDocumentLocation:(id)arg1 branchName:(id)arg2 revisionName:(id)arg3;
- (id)initWithDocumentURL:(id)arg1 branchName:(id)arg2 revisionName:(id)arg3;
- (BOOL)isEqualDisregardingTimestamp:(id)arg1;
@property(readonly) NSString *revisionName; // @synthesize revisionName=_revisionName;
- (id)workingTreeItem;

@end

