/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEFoundation/IDESourceControlTreeItem.h>

@class NSArray, NSMutableArray;

@interface IDESourceControlTreeGroup : IDESourceControlTreeItem
{
    BOOL _areChildrenLoaded;
}

+ (void)initialize;
+ (id)keyPathsForValuesAffectingSparseChildren;
@property BOOL areChildrenLoaded; // @synthesize areChildrenLoaded=_areChildrenLoaded;
@property(copy) NSArray *children; // @dynamic children;
- (void)clearAllRevisions;
- (void)computeChildrenIfNeeded;
- (id)ideModelObjectTypeIdentifier;
@property(readonly) NSMutableArray *mutableChildren; // @dynamic mutableChildren;
- (void)reload;
- (id)sparseChildren;

@end

