/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "IDEDebugProcess.h"

@class IDELaunchSession, NSArray, NSString;

@interface IDEShellXPCProcess : NSObject <IDEDebugProcess>
{
    NSString *_name;
}

- (void).cxx_destruct;
@property(readonly, copy) NSString *associatedProcessUUID;
- (id)contentDelegateUIExtensionIdentifier;
- (id)initWithName:(id)arg1;
@property(readonly) IDELaunchSession *launchSession;
@property(readonly, nonatomic) NSArray *loadedCodeModules;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

