/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEFoundation/IDESchemeActionAbstractTestSummaryObject.h>

#import "IDESchemeActionTestSummaryContainer.h"

@class NSArray, NSMutableArray, NSString;

@interface IDESchemeActionTestableSummary : IDESchemeActionAbstractTestSummaryObject <IDESchemeActionTestSummaryContainer>
{
    NSMutableArray *_tests;
    NSString *_blueprintProviderPath;
    NSString *_blueprintName;
}

+ (void)_coalesceTestSummariesInContainers:(id)arg1 intoAggregateContainer:(id)arg2;
+ (void)_countOfSuccessfulTests:(unsigned long long *)arg1 failingTests:(unsigned long long *)arg2 mixedTests:(unsigned long long *)arg3 inSummaryContainer:(id)arg4;
+ (id)coalescedTestableSummaryForTestableSummariesForSameTestable:(id)arg1;
+ (void)countOfSuccessfulTests:(unsigned long long *)arg1 failingTests:(unsigned long long *)arg2 mixedTests:(unsigned long long *)arg3 inSummaries:(id)arg4;
+ (BOOL)includeDummyTestSummaryInTestableSummary;
+ (void)initialize;
- (void).cxx_destruct;
- (id)addNewTestSummaryGroupWithName:(id)arg1 identifier:(id)arg2;
- (id)addNewTestSummaryWithName:(id)arg1 identifier:(id)arg2 status:(unsigned long long)arg3 failureSummaries:(id)arg4 performanceMetrics:(id)arg5;
@property(copy) NSString *blueprintName; // @synthesize blueprintName=_blueprintName;
@property(copy) NSString *blueprintProviderPath; // @synthesize blueprintProviderPath=_blueprintProviderPath;
@property(readonly) NSArray *containedTestSummaries;
- (id)dictionaryRepresentation;
- (id)initWithDictionaryRepresentation:(id)arg1;
- (id)initWithName:(id)arg1 blueprintProviderPath:(id)arg2 blueprintName:(id)arg3;
- (BOOL)isSummaryForSameTestableAsSummary:(id)arg1;
@property(readonly) NSMutableArray *mutableContainedTestSummaries;
- (unsigned long long)status;
- (BOOL)updateWithDictionaryRepresentation:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(copy) NSMutableArray *mutableTests; // @dynamic mutableTests;
@property(copy) NSString *name;
@property(readonly) Class superclass;
@property(copy) NSArray *tests; // @dynamic tests;

@end

