/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class IDERunnable, NSArray, NSMutableArray, NSMutableSet, NSSet;

@interface IDETestRunner : NSObject
{
    NSMutableArray *_skippedTests;
    NSMutableArray *_testResults;
    NSMutableSet *_runningTests;
    id <IDETestable> _testable;
    IDERunnable *_host;
    id <IDETestingSpecifier> _testingSpecifier;
}

+ (void)initialize;
- (void).cxx_destruct;
- (id)defaultTestArgumentsOperationForBuildParameters:(id)arg1 launchParameters:(id)arg2 runDestination:(id)arg3 workspace:(id)arg4 error:(id *)arg5 completionBlock:(id)arg6;
- (id)defaultTestEnvironmentVariablesForBuildParameters:(id)arg1 runDestination:(id)arg2 workspace:(id)arg3 error:(id *)arg4;
- (void)didRunTest:(id)arg1 withResult:(id)arg2;
@property(retain) IDERunnable *host; // @synthesize host=_host;
- (id)init;
@property(retain) id <IDETestable> testable; // @synthesize testable=_testable;
@property(retain) id <IDETestingSpecifier> testingSpecifier; // @synthesize testingSpecifier=_testingSpecifier;
- (id)testHostRunnableForRunDestination:(id)arg1 buildParameters:(id)arg2 outError:(id *)arg3;
- (id)testOperationsForExecutionEnvironment:(id)arg1 buildParameters:(id)arg2 runDestination:(id)arg3 workspace:(id)arg4 testOperationErrorBlock:(id)arg5 error:(void)arg6 launchParametersBlock:(id *)arg7;
- (id)testOperationsForExecutionEnvironment:(id)arg1 withBuildOperation:(id)arg2 buildParameters:(id)arg3 runDestination:(id)arg4 workspace:(id)arg5 error:(id *)arg6 launchParametersBlock:(id)arg7;
- (void)willRunTest:(id)arg1;

// Remaining properties
@property(readonly) NSMutableArray *mutableRunningTests; // @dynamic mutableRunningTests;
@property(readonly) NSMutableArray *mutableSkippedTests; // @dynamic mutableSkippedTests;
@property(readonly) NSMutableArray *mutableTestResults; // @dynamic mutableTestResults;
@property(copy) NSSet *runningTests; // @dynamic runningTests;
@property(copy) NSArray *skippedTests; // @dynamic skippedTests;
@property(copy) NSArray *testResults; // @dynamic testResults;

@end

