/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "DVTEncodableIndexDelegate.h"
#import "DVTInvalidation.h"

@class DVTEncodableIndex, DVTLibraryFragmentFilter, DVTStackBacktrace, IDEWorkspace, NSArray, NSMutableSet, NSObject<OS_dispatch_queue>, NSString;

@interface IDETextIndex : NSObject <DVTEncodableIndexDelegate, DVTInvalidation>
{
    NSObject<OS_dispatch_queue> *_indexQueue;
    unsigned long long _maxConcurrentOperationCount;
    DVTLibraryFragmentFilter *_filterIndex;
    DVTEncodableIndex *_findIndex;
    IDEWorkspace *_workspace;
    NSArray *_dataProviders;
    int _readyFlag;
    NSMutableSet *_scheduledJobs;
    unsigned long long _nRunningJobs;
    double _startTime;
    long long _nCompleted;
    NSObject<OS_dispatch_queue> *_updateQueue;
    double _timeOfLastUpdateRequest;
    BOOL _updatePending;
    NSObject<OS_dispatch_queue> *_saveQueue;
    double _timeOfLastSaveRequest;
    unsigned long long _indexTypesForPendingSave;
}

+ (void)_logMissingProviderForFileDataType:(id)arg1;
+ (long long)defaultMaxConcurrentOperationCount;
+ (void)initialize;
+ (id)logAspect;
- (void).cxx_destruct;
- (void)_beginTextIndexingIfNeeded;
- (id)_collectFilePathsForTextIndex;
- (BOOL)_computeFilterForFilePath:(id)arg1 withDataProvider:(id)arg2 queryString:(id)arg3;
- (id)_computeFindableForFilePath:(id)arg1 withDataProvider:(id)arg2;
- (id)_dataProviderForFileDataType:(id)arg1;
- (id)_dataProviderForFilePath:(id)arg1 lastKnownFileDataType:(id)arg2 outFileDataType:(id *)arg3;
- (void)_finishIndexing;
- (BOOL)_hasBegunTextIndexing;
- (void)_indexFileInPath:(id)arg1;
- (id)_indexFolderPath;
- (void)_initDataProviders;
- (void)_loadTextIndex;
- (void)_postNotificationName:(id)arg1 userInfo:(id)arg2;
- (void)_removeIndexEntriesForPathStrings:(id)arg1 indexTypes:(unsigned long long)arg2;
- (void)_reportProgress:(double)arg1;
- (void)_saveTextIndexForTypes:(unsigned long long)arg1;
- (void)_scheduleJobs;
- (void)_scheduleSaveForTypes:(unsigned long long)arg1;
- (void)_scheduleUpdate;
- (void)_startIndexing;
- (void)_updateIfReady;
- (void)beginTextIndexing;
- (void)dealloc;
- (void)encodableIndex:(id)arg1 didAddItemForIdentifier:(id)arg2;
- (void)encodableIndex:(id)arg1 didRemoveItemForIdentifier:(id)arg2;
- (id)filePathsPossiblyContainingString:(id)arg1 indexedFilePaths:(id *)arg2;
- (id)findableForFilePath:(id)arg1;
- (id)init;
- (id)initWithWorkspace:(id)arg1;
- (void)primitiveInvalidate;
- (void)scheduleJob:(id)arg1;
- (void)scheduleJobs:(id)arg1;
- (void)setMaxConcurrentOperationCount:(unsigned long long)arg1;
- (void)updateTextIndex;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

