/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEFoundation/IDEBreakpoint.h>

@interface IDETestFailureBreakpoint : IDEBreakpoint
{
}

- (id)displayName;
- (id)init;
- (id)symbolNames;

@end

