/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEFoundation/IDEUpgradeContext.h>

@class IDEContainer;

@interface IDEUpgradeContainerContext : IDEUpgradeContext
{
    IDEContainer *_container;
}

- (void).cxx_destruct;
@property(readonly) IDEContainer *container; // @synthesize container=_container;
- (id)description;
- (id)initWithContainer:(id)arg1;

@end

