/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class IDEUpgradeContext, NSString;

@interface IDEUpgradeTask : NSObject
{
    NSString *_title;
    NSString *_subtitle;
    NSString *_category;
    IDEUpgradeContext *_context;
    BOOL _selected;
}

+ (id)analyzeInContext:(id)arg1;
+ (id)analyzeInScheme:(id)arg1;
+ (id)metricLogAspect;
- (void).cxx_destruct;
- (void)_setCategory:(id)arg1;
@property(readonly) NSString *category; // @synthesize category=_category;
@property(readonly) IDEUpgradeContext *context; // @synthesize context=_context;
- (id)initWithTitle:(id)arg1 subtitle:(id)arg2 context:(id)arg3;
@property BOOL selected; // @synthesize selected=_selected;
@property(readonly) NSString *subtitle; // @synthesize subtitle=_subtitle;
@property(readonly) NSString *title; // @synthesize title=_title;
- (BOOL)upgrade;

@end

