/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "DVTInvalidation.h"

@class DVTFilePath, DVTPerformanceMetric, DVTStackBacktrace, IDESnapshotsManager, IDEWorkspace, NSDictionary, NSObject<OS_dispatch_queue>, NSString;

@interface IDEWorkspaceSnapshotManager : NSObject <DVTInvalidation>
{
    IDESnapshotsManager *_snapshotsManager;
    DVTPerformanceMetric *_metric;
    IDEWorkspace *_workspace;
    DVTFilePath *_repositoryPath;
    BOOL _userIntentToSnapshot;
    NSString *_currentOperationName;
    id <IDESnapshotConfirmationDelegate> _confirmationDelegate;
    NSObject<OS_dispatch_queue> *_snapshotManagerQueue;
    NSDictionary *_localizedStrings;
}

+ (void)initialize;
- (void).cxx_destruct;
- (void)_generateLocalizedStrings;
- (id)_localizedStringForKey:(id)arg1;
- (BOOL)_shouldCreateSnapshotWithType:(int)arg1 error:(id *)arg2;
- (void)_snapshotsSettingsDidChange:(id)arg1;
@property(retain) id <IDESnapshotConfirmationDelegate> confirmationDelegate; // @synthesize confirmationDelegate=_confirmationDelegate;
- (void)createAutomaticSnapshotBefore:(id)arg1 generatedBy:(id)arg2 type:(int)arg3 completionBlock:(id)arg4;
- (void)createSnapshotWithType:(int)arg1 name:(id)arg2 description:(id)arg3 origin:(id)arg4 completionBlock:(id)arg5;
@property(copy) NSString *currentOperationName; // @synthesize currentOperationName=_currentOperationName;
- (id)initWithWorkspace:(id)arg1;
- (void)primitiveInvalidate;
@property(retain) DVTFilePath *repositoryPath; // @synthesize repositoryPath=_repositoryPath;
@property(readonly) IDEWorkspace *workspace; // @synthesize workspace=_workspace;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

