/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEFoundation/IDEBreakpoint.h>

@class NSString;

@interface IDEWatchpoint : IDEBreakpoint
{
    NSString *_expression;
    NSString *_variableName;
    unsigned long long _address;
    NSString *_hexAddress;
}

+ (id)_displayStringForAddress:(unsigned long long)arg1;
+ (id)keyPathsForValuesAffectingDisplayName;
+ (id)keyPathsForValuesAffectingHexAddress;
- (void).cxx_destruct;
@property unsigned long long address; // @synthesize address=_address;
- (id)displayName;
@property(readonly) NSString *expression; // @synthesize expression=_expression;
@property(readonly) NSString *hexAddress;
- (id)initWithExpression:(id)arg1 variableName:(id)arg2;
@property(readonly) NSString *variableName; // @synthesize variableName=_variableName;

@end

