/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSView.h"

@interface _IDESwipeAnimationHostView : NSView
{
}

- (BOOL)acceptsFirstResponder;
- (id)hitTest:(struct CGPoint)arg1;
- (void)mouseDown:(id)arg1;
- (BOOL)performKeyEquivalent:(id)arg1;
- (void)rightMouseDown:(id)arg1;

@end

