/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSSplitView.h"

@class NSColor;

@interface _IDETmpSplitView : NSSplitView
{
    double _dividerThickness;
    BOOL _suppressFrameWarnings;
    NSColor *dividerColor;
}

- (void).cxx_destruct;
- (BOOL)_validateSubviewFrames;
@property(copy) NSColor *dividerColor; // @synthesize dividerColor;
@property double dividerThickness; // @synthesize dividerThickness=_dividerThickness;
- (void)drawDividerInRect:(struct CGRect)arg1;
@property BOOL suppressFrameWarnings; // @synthesize suppressFrameWarnings=_suppressFrameWarnings;

@end

