/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSOpenSavePanelDelegate.h"

@class NSSet, NSString;

@interface _IDEStructureNavigatorAddFilesOpenPanelDelegate : NSObject <NSOpenSavePanelDelegate>
{
    NSSet *_urls;
}

- (void).cxx_destruct;
- (id)initWithContainer:(id)arg1;
- (BOOL)panel:(id)arg1 shouldEnableURL:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

