/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSMetadataQuery, NSString;

@interface _IDEBotsURLSpotlightHandler : NSObject
{
    NSMetadataQuery *_spotlightQuery;
    id _completionHandler;
    id _bot;
    id _integration;
    NSString *_projectName;
}

+ (id)sharedSpotlightHandler;
- (void).cxx_destruct;
- (void)didStartGathering:(id)arg1;
- (void)initalGatherComplete:(id)arg1;
- (void)queryDidUpdate:(id)arg1;
- (void)startQueryForProjectName:(id)arg1 bot:(id)arg2 integration:(id)arg3 completionHandler:(id)arg4;

@end

