/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "DVTInvalidation.h"

@class DVTStackBacktrace, IDEGeniusResultsGraphNode, IDENavigableItem, NSString;

@interface _IDEGeniusResultsContext : NSObject <DVTInvalidation>
{
    NSString *_geniusCategory;
    IDENavigableItem *_geniusRootNavigableItem;
    IDEGeniusResultsGraphNode *_geniusResultsGraphNode;
}

+ (void)initialize;
- (void).cxx_destruct;
@property(copy) NSString *geniusCategory; // @synthesize geniusCategory=_geniusCategory;
@property(retain, nonatomic) IDENavigableItem *geniusRootNavigableItem; // @synthesize geniusRootNavigableItem=_geniusRootNavigableItem;
- (void)primitiveInvalidate;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

