/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSMenuDelegate.h"

@protocol DVTFilteringMenuDelegate <NSMenuDelegate>
- (void)filterItems:(id)arg1 inMenu:(id)arg2 forSearchString:(id)arg3;
@end

