/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol IDEActivityPopUpContentLayerControllerDelegate <NSObject>

@optional
- (void)doneButtonWasClickedInPopUpContentLayerController:(id)arg1;
- (void)popUpContentLayerController:(id)arg1 didChangePreferredHeightTo:(double)arg2;
- (void)popUpContentLayerController:(id)arg1 displayedReportCountDidChangeTo:(unsigned long long)arg2;
@end

