/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "DVTInvalidation.h"

@class DVTExtension, DVTStackBacktrace, IDEWorkspace, NSArray, NSImage, NSMutableArray, NSString;

@interface IDEActivityReporter : NSObject <DVTInvalidation>
{
    DVTExtension *_representedExtension;
    IDEWorkspace *_workspace;
    NSArray *_activityReports;
    NSImage *_image;
}

+ (id)activityReporterWithExtension:(id)arg1 workspace:(id)arg2;
+ (void)initialize;
- (void).cxx_destruct;
@property(readonly) NSImage *image;
- (id)initWithWorkspace:(id)arg1;
- (id)newActivityReportWithTitle:(id)arg1 options:(int)arg2 image:(id)arg3;
- (id)newActivityReportWithTitle:(id)arg1 options:(int)arg2 image:(id)arg3 fileIOPriority:(unsigned long long)arg4 fileIOCoordinatorBlock:(id)arg5;
- (id)newActivityReportWithTitle:(id)arg1 options:(int)arg2 isUserVisible:(BOOL)arg3 image:(id)arg4 fileIOPriority:(unsigned long long)arg5 fileIOCoordinatorBlock:(id)arg6;
- (void)primitiveInvalidate;
@property(retain) DVTExtension *representedExtension; // @synthesize representedExtension=_representedExtension;
@property(readonly) IDEWorkspace *workspace; // @synthesize workspace=_workspace;

// Remaining properties
@property(readonly) NSArray *activityReports; // @dynamic activityReports;
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) NSMutableArray *mutableActivityReports; // @dynamic mutableActivityReports;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

