/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "DVTInvalidation.h"

@class DVTStackBacktrace, IDEProjectItemModel, NSOrderedSet, NSSet, NSString;

@interface IDEAppIDItemIdentifiersItemModelSet : NSObject <DVTInvalidation>
{
    id <IDEFlightChecking> _flightCheck;
    NSOrderedSet *_unexpandedIdentifiers;
    BOOL _requiresPortalIdentifiers;
    IDEProjectItemModel *_itemModel;
    NSString *_teamItemsKeyPath;
    NSString *_featuresItemsKeyPath;
    Class _listTeamItemsOpClass;
    NSString *_flightCheckName;
    NSSet *_availableTeamIdentifiers;
}

+ (id)expandedIdentifiers:(id)arg1 targetCapabilitiesContext:(id)arg2 error:(id *)arg3;
+ (void)initialize;
- (void).cxx_destruct;
- (id)_featureDelegate;
- (void)_readAvailableTeamIdentifiers;
- (void)_setUnexpandedIdentifiers:(id)arg1 postAssignmentBlock:(id)arg2;
@property(retain) NSSet *availableTeamIdentifiers; // @synthesize availableTeamIdentifiers=_availableTeamIdentifiers;
- (id)expandedIdentifier:(id)arg1 error:(id *)arg2;
- (id)expandedIdentifiersWithError:(id *)arg1;
@property(readonly) NSString *featuresItemsKeyPath; // @synthesize featuresItemsKeyPath=_featuresItemsKeyPath;
@property(readonly) id <IDEFlightChecking> flightCheck;
@property(readonly) NSString *flightCheckName; // @synthesize flightCheckName=_flightCheckName;
- (id)initWithItemModel:(id)arg1 teamItemsKeyPath:(id)arg2 featuresItemsKeyPath:(id)arg3 listTeamItemsOpClass:(Class)arg4 flightCheckName:(id)arg5;
- (id)initWithoutPortalWithItemModel:(id)arg1;
@property(retain) IDEProjectItemModel *itemModel; // @synthesize itemModel=_itemModel;
@property(readonly) Class listTeamItemsOpClass; // @synthesize listTeamItemsOpClass=_listTeamItemsOpClass;
- (void)primitiveInvalidate;
- (id)refreshAvailableTeamIdentifiers;
@property(readonly) BOOL requiresPortalIdentifiers; // @synthesize requiresPortalIdentifiers=_requiresPortalIdentifiers;
@property(copy, nonatomic) NSOrderedSet *unexpandedIdentifiers;
@property(readonly) NSString *teamItemsKeyPath; // @synthesize teamItemsKeyPath=_teamItemsKeyPath;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

