/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "CALayer.h"

@class IDEActivityPopUpReportLayer, NSArray, NSMutableArray, NSString;

@interface IDEActivityPopUpContentLayer : CALayer
{
    id <IDEActivityPopUpContentLayerDelegate> _delegate;
    NSMutableArray *_orderedReportLayers;
    NSMutableArray *_lineLayers;
    NSMutableArray *_orderedVisibleReportLayers;
    BOOL _issuesAreVisible;
    BOOL _botStatusIsVisible;
    NSArray *_issueCategories;
    NSString *_issuesContainerTypeString;
    NSArray *_botStatusCategories;
    IDEActivityPopUpReportLayer *_layerToHide;
    double _spaceNeededForMultiActionIndicator;
}

- (void).cxx_destruct;
- (void)addActivityReportLayer:(id)arg1;
- (void)addStandardLineLayer;
@property(copy) NSArray *botStatusCategories; // @synthesize botStatusCategories=_botStatusCategories;
@property BOOL botStatusIsVisible; // @synthesize botStatusIsVisible=_botStatusIsVisible;
@property id <IDEActivityPopUpContentLayerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)init;
- (void)insertActivityReportLayer:(id)arg1 atIndex:(unsigned long long)arg2;
@property(copy) NSArray *issueCategories; // @synthesize issueCategories=_issueCategories;
@property BOOL issuesAreVisible; // @synthesize issuesAreVisible=_issuesAreVisible;
@property(copy) NSString *issuesContainerTypeString; // @synthesize issuesContainerTypeString=_issuesContainerTypeString;
@property(retain, nonatomic) IDEActivityPopUpReportLayer *layerToHide; // @synthesize layerToHide=_layerToHide;
- (void)layoutSublayers;
- (id)orderedVisibleReportLayers;
@property(readonly) double preferredHeight;
- (void)preferredHeightDidChange;
- (void)removeActivityReportLayer:(id)arg1;
@property(nonatomic) double spaceNeededForMultiActionIndicator; // @synthesize spaceNeededForMultiActionIndicator=_spaceNeededForMultiActionIndicator;

@end

