/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEMigrationTarget.h>

@class IDEARCConversionAssistantContext, NSString;

@interface IDEARCConversionTarget : IDEMigrationTarget
{
    IDEARCConversionAssistantContext *_assistantContext;
    NSString *_displayName;
    BOOL _fileOveridesARCSetting;
}

- (void).cxx_destruct;
- (id)_treeControllerChildren;
- (id)_treeControllerWarningMessage;
@property(readonly) IDEARCConversionAssistantContext *assistantContext; // @synthesize assistantContext=_assistantContext;
@property(readonly, nonatomic) NSString *blueprintProviderName;
@property(readonly) BOOL buildsWithARC;
@property(readonly) BOOL canConvertToUseARC;
@property BOOL convertsToARC;
- (void)disableOverridingBuildSettings;
@property(readonly, copy) NSString *displayName; // @synthesize displayName=_displayName;
- (void)enableOverridingBuildSettings;
@property(readonly) BOOL fileOveridesARCSetting; // @synthesize fileOveridesARCSetting=_fileOveridesARCSetting;
- (id)initWithBlueprint:(id)arg1 assistantContext:(id)arg2;
@property(readonly, nonatomic) NSString *title;
- (void)updateBuildSettings;
- (id)warningMessage;

@end

