/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEAlertsPrefsBehaviorTableCellView.h>

@class IDEKeyBindingField, NSTableView;

@interface IDEAlertsPrefsCustomBehaviorTableCellView : IDEAlertsPrefsBehaviorTableCellView
{
    IDEKeyBindingField *_keyBindingField;
    NSTableView *_tableView;
}

- (void).cxx_destruct;
- (void)beginEditingFromEvent:(id)arg1 inTableView:(id)arg2 column:(long long)arg3 row:(long long)arg4;
- (void)controlTextDidBeginEditing:(id)arg1;
- (void)controlTextDidEndEditing:(id)arg1;
- (id)customAlertEvent;
@property(retain, nonatomic) IDEKeyBindingField *keyBindingField; // @synthesize keyBindingField=_keyBindingField;
- (id)keyBindingFieldCell:(id)arg1 validatedKeyboardShortcut:(id)arg2;
- (BOOL)keyBindingFieldCellAllowsMultipleKeyboardShortcut:(id)arg1;
- (void)keyBindingFieldCellDidAddKeyboardShortcut:(id)arg1;
- (void)keyBindingFieldCellWillRemoveKeyboardShortcut:(id)arg1;
- (id)keyBindingString;
- (id)keyBindingStringForKeyboardShortCut:(id)arg1;
- (id)keyboardShortcut;
- (struct CGRect)keyboardShortcutRect;
- (struct CGRect)keyboardShortcutRectForString:(id)arg1 editing:(BOOL)arg2;
- (void)setAlertEvent:(id)arg1;
@property(nonatomic) __weak NSTableView *tableView; // @synthesize tableView=_tableView;
- (void)setTitleFromEdit:(id)arg1;
- (void)tile;
- (void)tileWithString:(id)arg1 editing:(BOOL)arg2;
- (struct CGRect)titleRect;

@end

