/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "CALayer.h"

#import "DVTInvalidation.h"

@class DVTObservingToken, DVTStackBacktrace, IDEActivityProgressIndicatorLayer, IDEActivityReport, IDEActivityScrollingTextLayer, NSMutableArray, NSString;

@interface IDEActivityReportLayer : CALayer <DVTInvalidation>
{
    IDEActivityProgressIndicatorLayer *_progressIndicatorLayer;
    IDEActivityScrollingTextLayer *_scrollingTextLayer;
    long long _displayStyle;
    IDEActivityReport *_activityReport;
    CALayer *_imageLayer;
    NSMutableArray *_stringSegments;
    BOOL _paused;
    DVTObservingToken *_kvoActivityReportTitleSegmentsToken;
    DVTObservingToken *_kvoActivityReportProgressToken;
    DVTObservingToken *_kvoActivityReportTitleToken;
    DVTObservingToken *_kvoActivityReportThrottleFactorToken;
    BOOL _isActiveWindowStyle;
    double _spaceNeededForMultiActionIndicator;
    double _spaceNeededForStatusLayers;
}

+ (id)activityReportLayerForDisplayStyle:(long long)arg1;
+ (struct CGSize)defaultSizeForPopUpStyle;
+ (void)initialize;
- (void).cxx_destruct;
- (void)_addPausedSegment;
- (id)_pausedAttributes;
- (void)_removePausedSegment;
- (void)_updatePaused:(BOOL)arg1;
- (void)_updateStringSegments:(id)arg1;
- (id)_workspace;
@property(retain, nonatomic) IDEActivityReport *activityReport; // @synthesize activityReport=_activityReport;
- (id)defaultCompletionSummary;
- (id)defaultIdleActionString;
- (id)defaultIdleTitle;
- (id)defaultReportTitle;
@property(readonly, copy) NSString *description;
@property(nonatomic) long long displayStyle; // @synthesize displayStyle=_displayStyle;
@property(readonly) BOOL indeterminateReportInProgress;
- (id)init;
@property(nonatomic) BOOL isActiveWindowStyle; // @synthesize isActiveWindowStyle=_isActiveWindowStyle;
- (id)keyPathsForValuesAffectingIndeterminateReportInProgress;
- (void)layoutSublayers;
- (id)nonFailedBuildTextAttributes;
- (void)primitiveInvalidate;
@property(nonatomic) double spaceNeededForMultiActionIndicator; // @synthesize spaceNeededForMultiActionIndicator=_spaceNeededForMultiActionIndicator;
@property(nonatomic) double spaceNeededForStatusLayers; // @synthesize spaceNeededForStatusLayers=_spaceNeededForStatusLayers;
- (BOOL)shouldHideProgress;
- (void)sizeToFit;
- (void)startObservingActivityReport;
- (void)stopObservingActivityReport;
- (void)updateConstraints;
- (void)updateScrollingTextFieldStringValue;
- (void)updateVisibilityForTextFieldAndAdjustLayoutIfNeeded;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

