/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEStructureEditingAssistantContext.h>

@class DVTObservingToken, IDEGroup, NSArray, NSString;

@interface IDEAddContainerItemsAssistantContext : IDEStructureEditingAssistantContext
{
    IDEGroup *_targetGroup;
    DVTObservingToken *_targetGroupObservingToken;
    NSArray *_containerItems;
    BOOL _stripOutBuildProductContainerItems;
    BOOL _createGroupsForFolders;
    BOOL _copyFilesToTargetGroup;
    id _prepareBlock;
    NSString *_buildToolPath;
    NSString *_buildArgumentsString;
    BOOL _shouldHideCopyFilesToTargetGroupSwitchButton;
}

+ (id)_containerAddingItemsAssistantExtensionForContainer:(id)arg1;
+ (id)contextWithTargetGroup:(id)arg1;
+ (void)initialize;
- (void).cxx_destruct;
- (void)_addItemsFromDraggingInfo:(id)arg1;
- (void)_configureForOnlyDraggingProjects;
@property(readonly) NSString *actualAssistantIdentifier;
- (id)assistantIdentifier;
@property(copy) NSString *buildArgumentsString; // @synthesize buildArgumentsString=_buildArgumentsString;
@property(copy) NSString *buildToolPath; // @synthesize buildToolPath=_buildToolPath;
@property(copy) NSArray *containerItems; // @synthesize containerItems=_containerItems;
@property BOOL copyFilesToTargetGroup;
@property BOOL createGroupsForFolders;
- (void)dealloc;
- (id)init;
@property(copy) id prepareBlock; // @synthesize prepareBlock=_prepareBlock;
@property BOOL shouldHideCopyFilesToTargetGroupSwitchButton; // @synthesize shouldHideCopyFilesToTargetGroupSwitchButton=_shouldHideCopyFilesToTargetGroupSwitchButton;
@property BOOL stripOutBuildProductContainerItems; // @synthesize stripOutBuildProductContainerItems=_stripOutBuildProductContainerItems;
@property(retain, nonatomic) IDEGroup *targetGroup; // @synthesize targetGroup=_targetGroup;

@end

