/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class IDEBatchFindScopeRuleRow, NSIndexPath;

@interface IDEBatchFindScopeRuleNode : NSObject
{
    IDEBatchFindScopeRuleRow *_row;
    NSIndexPath *_indexPath;
}

+ (id)nodeArrayForIndexPath:(id)arg1 inRow:(id)arg2;
+ (id)nodeForIndexPath:(id)arg1 inRow:(id)arg2;
- (void).cxx_destruct;
- (id)childAtIndex:(long long)arg1;
@property(readonly) long long childCount;
- (unsigned long long)hash;
@property(readonly) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
- (id)initWithPath:(id)arg1 inRow:(id)arg2;
- (BOOL)isEqual:(id)arg1;
@property(readonly) IDEBatchFindScopeRuleRow *row; // @synthesize row=_row;

@end

