/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEBatchFindFileLocator.h>

@class IDEContainer;

@interface IDEBatchFindWorkspaceFileLocator : IDEBatchFindFileLocator
{
    BOOL _skipFrameworks;
    IDEContainer *_scopeContainer;
}

+ (id)_containerForPath:(id)arg1 inGroup:(id)arg2;
+ (id)containerItemForWorkspacePath:(id)arg1 inWorkspace:(id)arg2;
- (void).cxx_destruct;
- (id)_generateGroupTitleForPath:(id)arg1 isInFramework:(char *)arg2 fileReferenceAssociatedFiles:(id)arg3;
- (id)_majorContainerForContainer:(id)arg1 isFramework:(char *)arg2;
- (id)initWithPath:(id)arg1 skippingLinkedFrameworks:(BOOL)arg2 andPredicate:(id)arg3 container:(id)arg4;
- (id)locationOperationForWorkspace:(id)arg1 withResultsBlock:(id)arg2;
- (BOOL)requiresMainThread;
@property(retain) IDEContainer *scopeContainer; // @synthesize scopeContainer=_scopeContainer;

@end

