/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

#import "IDEBatchFindResultGroupDelegate.h"
#import "IDENavigableItemCoordinatorDelegate.h"

@class IDEBatchFindResultSet, IDENavigableItem, IDENavigableItemCoordinator, IDENavigatorDataCell, IDENavigatorOutlineView, IDESearchResultTruncatingCell, NSArray, NSIndexSet, NSMutableArray, NSMutableSet, NSSet, NSString, NSTableColumn;

@interface IDEBatchFindResultsOutlineController : IDEViewController <IDENavigableItemCoordinatorDelegate, IDEBatchFindResultGroupDelegate>
{
    IDENavigatorOutlineView *_outlineView;
    NSTableColumn *_checkTableColumn;
    NSTableColumn *_mainTableColumn;
    NSMutableArray *_observerTokens;
    NSArray *_selectedObjects;
    NSArray *_selectedResultNavigables;
    NSIndexSet *_previousSelection;
    NSSet *_checkedResultNavigables;
    NSSet *_checkedResultNavigablesForReplacement;
    IDEBatchFindResultSet *_resultSet;
    double _lastOutlineUpdate;
    NSMutableSet *_collapsedItems;
    NSMutableSet *_groupsExpandedNeedingSelectionChange;
    NSMutableSet *_observedFilePaths;
    BOOL _dontPublishSelectionChanges;
    BOOL _showsStatusImage;
    BOOL _allowsDelete;
    BOOL _showsCheckedRow;
    BOOL _symbolLookupEnabled;
    BOOL _isShowingPreview;
    BOOL _deferRefreshForRootNavigables;
    BOOL _invalidatingRowHeights;
    IDENavigatorDataCell *_groupPrototypeCell;
    IDESearchResultTruncatingCell *_resultPrototypeCell;
    BOOL _toolTipsEnabled;
    BOOL _searchInProgress;
    IDENavigableItem *_resultsNavigable;
    IDENavigableItemCoordinator *_navigableItemCoordinator;
    struct _NSRange _visibleRows;
}

+ (id)groupStatusPrototypeCells;
+ (void)initialize;
+ (id)keyPathsForValuesAffectingResultsNavigable;
+ (id)keyPathsForValuesAffectingRootNavigables;
+ (id)keyPathsForValuesAffectingSelectedResultNavigables;
- (void).cxx_destruct;
- (void)_delayedSelectionOfExpandedChildren;
- (void)_expandItems;
- (void)_observeFilePathOfGroupNavItem:(id)arg1;
- (void)_refreshOutline;
- (void)_requestOutlineUpdateImmediately:(BOOL)arg1;
- (void)_setupObservers;
- (void)_unobserveFilePathOfGroups;
- (BOOL)_writeItems:(id)arg1 toPasteboard:(id)arg2;
@property BOOL allowsDelete; // @synthesize allowsDelete=_allowsDelete;
@property(retain, nonatomic) NSSet *checkedResultNavigables; // @synthesize checkedResultNavigables=_checkedResultNavigables;
@property(readonly) NSSet *checkedResultNavigablesForReplacement;
@property(retain) NSIndexSet *collapsedGroups;
- (void)contextMenu_copy:(id)arg1;
- (void)copy:(id)arg1;
- (BOOL)delegateFirstResponder;
- (void)delete:(id)arg1;
- (id)domainIdentifier;
@property BOOL dontPublishSelectionChanges; // @synthesize dontPublishSelectionChanges=_dontPublishSelectionChanges;
- (id)dvtExtraBindings;
- (void)filterResultsWithPredicate:(id)arg1;
- (void)finishedSymbolQueryForResultsGroupNavItem:(id)arg1;
- (id)groupPrototypeCell;
- (void)invalidateRowHeights:(BOOL)arg1;
@property BOOL isShowingPreview; // @synthesize isShowingPreview=_isShowingPreview;
- (void)loadView;
@property(retain) IDENavigableItemCoordinator *navigableItemCoordinator; // @synthesize navigableItemCoordinator=_navigableItemCoordinator;
@property(copy) NSString *noResultsString;
- (void)openClickedNavigableItemAction:(id)arg1;
- (void)openDoubleClickedNavigableItemsAction:(id)arg1;
- (void)openSelectedNavigableItemsKeyAction:(id)arg1;
- (id)openSpecifierForNavigableItem:(id)arg1 error:(id *)arg2;
@property(readonly) IDENavigatorOutlineView *outlineView;
- (id)outlineView:(id)arg1 dataCellForTableColumn:(id)arg2 item:(id)arg3;
- (BOOL)outlineView:(id)arg1 doCommandBySelector:(SEL)arg2;
- (unsigned long long)outlineView:(id)arg1 draggingSourceOperationMaskForLocal:(BOOL)arg2;
- (double)outlineView:(id)arg1 heightOfRowByItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 insertText:(id)arg2;
- (BOOL)outlineView:(id)arg1 isGroupHeaderItem:(id)arg2;
- (id)outlineView:(id)arg1 objectValueForTableColumn:(id)arg2 byItem:(id)arg3;
- (id)outlineView:(id)arg1 selectionIndexesForProposedSelection:(id)arg2;
- (void)outlineView:(id)arg1 setObjectValue:(id)arg2 forTableColumn:(id)arg3 byItem:(id)arg4;
- (BOOL)outlineView:(id)arg1 shouldSelectItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 shouldShowCellExpansionForTableColumn:(id)arg2 item:(id)arg3;
- (id)outlineView:(id)arg1 toolTipForCell:(id)arg2 rect:(struct CGRect *)arg3 tableColumn:(id)arg4 item:(id)arg5 mouseLocation:(struct CGPoint)arg6;
- (void)outlineView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 item:(id)arg4;
- (BOOL)outlineView:(id)arg1 writeItems:(id)arg2 toPasteboard:(id)arg3;
- (void)outlineViewItemDidCollapse:(id)arg1;
- (void)outlineViewItemDidExpand:(id)arg1;
- (void)primitiveInvalidate;
- (void)reload;
- (id)resultPrototypeCell;
@property(retain) IDEBatchFindResultSet *resultSet;
@property(retain) IDENavigableItem *resultsNavigable; // @synthesize resultsNavigable=_resultsNavigable;
@property(readonly) NSArray *rootNavigables;
@property BOOL searchInProgress; // @synthesize searchInProgress=_searchInProgress;
- (void)selectAllResults;
@property(retain) NSArray *selectedObjects; // @synthesize selectedObjects=_selectedObjects;
@property(retain, nonatomic) NSArray *selectedResultNavigables; // @synthesize selectedResultNavigables=_selectedResultNavigables;
@property(retain) NSIndexSet *selectedRowIndexes;
@property(nonatomic) BOOL showsCheckedRow; // @synthesize showsCheckedRow=_showsCheckedRow;
@property BOOL showsStatusImage; // @synthesize showsStatusImage=_showsStatusImage;
@property(nonatomic) BOOL symbolLookupEnabled; // @synthesize symbolLookupEnabled=_symbolLookupEnabled;
@property(nonatomic) BOOL toolTipsEnabled; // @synthesize toolTipsEnabled=_toolTipsEnabled;
@property struct _NSRange visibleRows; // @synthesize visibleRows=_visibleRows;
- (void)updateBatchFindResults;
- (void)updateDetailLevel;
- (void)viewBoundsChanged:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

