/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEBatchFindPathBarMenuItem.h>

@interface IDEBatchFindFunctionType : IDEBatchFindPathBarMenuItem
{
    BOOL _showSymbolSearch;
}

- (id)children;
- (id)initWithTitle:(id)arg1 showSymbolSearch:(BOOL)arg2;
@property BOOL showSymbolSearch; // @synthesize showSymbolSearch=_showSymbolSearch;

@end

