/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEBatchFindPathBarMenuItem.h>

@interface IDEBatchFindPathBarMatchStyleType : IDEBatchFindPathBarMenuItem
{
    int _findType;
}

- (id)children;
@property int findType; // @synthesize findType=_findType;
- (id)initWithTitle:(id)arg1 findType:(int)arg2;
- (void)setFindOptions:(id)arg1;

@end

