/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSPredicate, NSString;

@interface IDEBatchFindScopePredicate : NSObject
{
    NSString *_name;
    NSString *_uuid;
    NSPredicate *_predicate;
    BOOL _hasUnsavedChanges;
}

+ (id)_archivablePredicateData:(id)arg1;
+ (id)_archivedScopesFromData:(id)arg1;
+ (id)readPredicatesForWorkspace:(id)arg1;
+ (void)writePredicates:(id)arg1 forWorkspace:(id)arg2 deletedScope:(BOOL)arg3;
- (void).cxx_destruct;
- (BOOL)_predicateContainsLocationSpecificExpression:(id)arg1;
- (void)dvt_encodeAttributesWithXMLArchiver:(id)arg1 version:(id)arg2;
@property BOOL hasUnsavedChanges; // @synthesize hasUnsavedChanges=_hasUnsavedChanges;
- (id)initFromXMLUnarchiver:(id)arg1 archiveVersion:(float)arg2;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSPredicate *predicate; // @synthesize predicate=_predicate;
- (void)setPredicateFromUTF8String:(const char *)arg1 fromXMLUnarchiver:(id)arg2;
@property(copy, nonatomic) NSString *uuid; // @synthesize uuid=_uuid;
@property(readonly) BOOL workspaceSpecific;

@end

