/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEBatchFindCriteria.h>

#import "NSCoding.h"

@class IDEBatchFindStrategiesController, IDEWorkspace, NSArray, NSMutableArray, NSPredicate;

@interface IDEBatchFindTextualFindCriteria : IDEBatchFindCriteria <NSCoding>
{
    NSPredicate *_filterPredicate;
    BOOL _searchFrameworks;
    IDEWorkspace *_workspace;
    NSMutableArray *_invalidLocationPaths;
    IDEBatchFindStrategiesController *_strategiesController;
    NSArray *_searchLocations;
}

+ (id)_builtInFileFilter;
+ (id)_containerForNavigableItem:(id)arg1 workspace:(id)arg2 skipFrameworks:(BOOL)arg3;
+ (BOOL)_isLocationPredicate:(id)arg1;
+ (id)_predicateForComparisonPredicate:(id)arg1;
+ (id)_substituteGenericPredicate:(id)arg1;
- (void).cxx_destruct;
- (void)_addUnresolvedContainerItemPath:(id)arg1;
- (void)_batchFindInvalidScopeSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (id)_extractLocationsFromTopLevelPredicate:(id)arg1;
- (id)_locatorFromLocationPredicate:(id)arg1 withCriteriaPredicate:(id)arg2;
- (void)_reportInvalidLocationPaths;
- (void)_showScopeEditor;
- (id)description;
- (void)encodeWithCoder:(id)arg1;
@property(readonly) NSPredicate *filterPredicate; // @synthesize filterPredicate=_filterPredicate;
- (Class)findQueryClass;
- (unsigned long long)hash;
- (id)initWithCoder:(id)arg1;
- (id)initWithFindDescriptor:(id)arg1 frameworks:(BOOL)arg2 filterPredicate:(id)arg3 containerScope:(id)arg4 workspace:(id)arg5 strategiesController:(id)arg6;
- (id)initWithFindDescriptor:(id)arg1 frameworks:(BOOL)arg2 filterPredicate:(id)arg3 containerScopes:(id)arg4 workspace:(id)arg5 strategiesController:(id)arg6;
- (BOOL)isEqual:(id)arg1;
- (id)matchingFileOperationForWorkspace:(id)arg1 withResultBlock:(id)arg2;
@property(readonly) BOOL searchFrameworks; // @synthesize searchFrameworks=_searchFrameworks;
@property(retain) NSArray *searchLocations; // @synthesize searchLocations=_searchLocations;
- (id)trimmedSearchPathsForPaths:(id)arg1 findString:(id)arg2 unsavedFiles:(id)arg3 workspace:(id)arg4;

@end

