/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "DVTInvalidation.h"

@class DVTDownloadable, DVTDownloadableManager, DVTDownloadableOperation, DVTObservingToken, DVTStackBacktrace, NSImage, NSMutableSet, NSString;

@interface IDEComponentDownloadsPrefPaneItem : NSObject <DVTInvalidation>
{
    DVTDownloadable *_downloadable;
    int _state;
    DVTDownloadableOperation *_downloadOperation;
    long long _downloadProgress;
    NSString *_fileSizeForDisplay;
    NSString *_fileSize;
    id _downloadCompletionBlock;
    BOOL _cancelable;
    DVTDownloadableManager *_downloadableManager;
    DVTObservingToken *_downloadCancelledToken;
    DVTObservingToken *_downloadFinishedToken;
    NSMutableSet *_downloadOperationObservationTokens;
}

+ (id)contextForDownloadableIdentifier:(id)arg1 ignoreDownloading:(BOOL)arg2;
+ (id)iconForDownloadableType:(id)arg1;
+ (void)initialize;
+ (id)itemWithDownloadable:(id)arg1 state:(int)arg2 downloadOperation:(id)arg3 downloadableManager:(id)arg4;
- (void).cxx_destruct;
- (void)_updateCancelable;
- (void)cancelDownload;
@property(readonly) BOOL cancelable; // @synthesize cancelable=_cancelable;
- (long long)compare:(id)arg1;
@property(readonly, copy) NSString *description;
@property(retain, nonatomic) DVTDownloadableOperation *downloadOperation; // @synthesize downloadOperation=_downloadOperation;
@property(readonly) long long downloadProgress; // @synthesize downloadProgress=_downloadProgress;
- (BOOL)downloadWithError:(id *)arg1 downloadCompletionBlock:(id)arg2;
@property(readonly) DVTDownloadable *downloadable; // @synthesize downloadable=_downloadable;
@property(readonly) NSString *fileSize; // @synthesize fileSize=_fileSize;
@property(readonly) NSString *fileSizeForDisplay; // @synthesize fileSizeForDisplay=_fileSizeForDisplay;
@property(readonly) NSImage *image;
- (void)primitiveInvalidate;
@property int state; // @synthesize state=_state;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

