/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol IDEContinuousIntegrationLogNavigatorHelper <NSObject>
- (void)additionalIntegrationsOnServerForBotNavigable:(id)arg1 completionBlock:(id)arg2;
- (BOOL)isIntegrationFinished:(id)arg1;
- (id)legacyBotNavigablesForLegacyBots:(id)arg1;
- (void)loadMoreBotsInBotNavigable:(id)arg1 completionBlock:(id)arg2;
- (id)navigableItemForBot:(id)arg1;
- (id)navigableItemForIntegration:(id)arg1;
- (BOOL)navigableItemSelection:(id)arg1 allowsAction:(SEL)arg2;
- (void)performAction:(SEL)arg1 forNavigableItemSelection:(id)arg2 withNavigator:(id)arg3;
- (int)statusOfIntegration:(id)arg1;
- (id)titleForNavigableItemSelection:(id)arg1 action:(SEL)arg2;
@end

