/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

#import "DVTCompletingTextViewDelegate.h"
#import "DVTFindBarHostable.h"
#import "DVTScopeBarHost.h"
#import "IDEConsoleTextViewObjectiveCExpressionRangeDelegate.h"
#import "IDEConsoleTextViewStandardIODelegate.h"
#import "IDEDebuggerBarConsoleInfoProvider.h"

@class DVTFindBar, DVTMapTable, DVTObservingToken, DVTScopeBarController, DVTScopeBarView, DVTScopeBarsManager, DVTScrollView, IDEConsoleTextView, IDEWorkspaceDocument, NSButton, NSMutableArray, NSMutableSet, NSPopUpButton, NSScrollView, NSSet, NSString, NSTimer, NSUndoManager, NSView;

@interface IDEConsoleArea : IDEViewController <IDEConsoleTextViewObjectiveCExpressionRangeDelegate, DVTFindBarHostable, DVTScopeBarHost, IDEConsoleTextViewStandardIODelegate, IDEDebuggerBarConsoleInfoProvider, DVTCompletingTextViewDelegate>
{
    DVTScopeBarView *_scopeBar;
    IDEConsoleTextView *_consoleView;
    NSPopUpButton *_filterModePopUpButton;
    NSButton *_clearConsoleButton;
    IDEWorkspaceDocument *_workspaceDocument;
    NSMutableArray *_inputHistoryForDebugger;
    unsigned long long _inputHistoryIndexForDebugger;
    NSString *_userEnteredTextBeforeShowingCommandHistory;
    NSUndoManager *_undoManager;
    NSMutableSet *_consoleAdaptors;
    DVTMapTable *_launchSessionsToClearTimes;
    NSSet *_initialConsoleItems;
    NSTimer *_clearInitialConsoleItemsTimer;
    DVTObservingToken *_workspaceDocumentObserverToken;
    DVTObservingToken *_launchSessionsObserverToken;
    DVTObservingToken *_consoleAdaptorsObservingToken;
    DVTObservingToken *_debugSessionStateObservingToken;
    DVTObservingToken *_currentDebugSessionToken;
    DVTFindBar *_findBar;
    DVTScopeBarController *_findScopeBarController;
    DVTScopeBarsManager *_scopeBarsManager;
    struct _NSRange _originalSelection;
    id _findStringChangedNotificationToken;
    int _filterMode;
    BOOL _hasNewInterestingOutput;
    DVTScrollView *_consoleScrollView;
}

+ (void)configureStateSavingObjectPersistenceByName:(id)arg1;
+ (long long)version;
- (void).cxx_destruct;
- (void)_addConsoleAdaptors:(id)arg1;
- (void)_appendItem:(id)arg1;
- (void)_appendItems:(id)arg1;
- (void)_assertUnsupportedAction;
- (void)_clearText;
- (id)_createFindBar;
- (void)_debugSessionPausedScriptingStateChanged;
- (void)_debugSessionStateChanged;
- (void)_filterChanged;
- (id)_findBar:(BOOL)arg1;
- (void)_handleLaunchSessionsChanged:(id)arg1;
- (void)_installCompletionStrategiesBasedOnDebugger;
- (void)_installFindBar;
- (void)_invalidateFindBarResults;
- (BOOL)_isFindBarInstalled;
- (void)_outputForConsole:(id)arg1;
- (void)_removeConsoleAdaptors:(id)arg1;
- (void)_removeObserverForConsoleAdaptor:(id)arg1;
- (void)_setWorkspaceDocument:(id)arg1;
- (void)_setupClearConsoleButton;
- (BOOL)_shouldAppendItem:(id)arg1;
- (id)_sortedCompletionStrategiesForGroupIdentifier:(id)arg1;
- (void)_stopObservingGlobalFindStringDidChangeNotification;
- (void)_timerFiredToClearInitialConsoleItems:(id)arg1;
- (void)_updateConsoleAdaptorsForCurrentLaunchSession;
- (void)activateConsole;
- (BOOL)becomeFirstResponder;
- (void)clearConsole:(id)arg1;
- (void)commitStateToDictionary:(id)arg1;
- (void)completingTextView:(id)arg1 willPassContextToStrategies:(id)arg2 atWordStartLocation:(unsigned long long)arg3;
@property __weak DVTScrollView *consoleScrollView; // @synthesize consoleScrollView=_consoleScrollView;
- (void)consoleView:(id)arg1 didEndText:(id)arg2 forDebugger:(BOOL)arg3 trackHistory:(BOOL)arg4;
- (BOOL)delegateFirstResponder;
- (void)dismissFindBar:(id)arg1 andRestoreSelection:(BOOL)arg2;
- (void)dvtFindBar:(id)arg1 didUpdateCurrentResult:(id)arg2;
- (BOOL)dvtFindBar:(id)arg1 validateUserInterfaceItem:(id)arg2;
@property(nonatomic) int filterMode; // @synthesize filterMode=_filterMode;
- (void)find:(id)arg1;
- (void)findAndReplace:(id)arg1;
- (void)findNext:(id)arg1;
- (void)findPrevious:(id)arg1;
@property BOOL hasNewInterestingOutput; // @synthesize hasNewInterestingOutput=_hasNewInterestingOutput;
- (void)hideFindBar:(id)arg1;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(readonly) NSMutableArray *inputHistoryForDebugger;
- (void)loadView;
- (void)primitiveInvalidate;
- (struct _NSRange)rangeOfExpressionInUserEnteredStringAfterPrompt:(id)arg1;
- (void)replace:(id)arg1;
- (void)replaceAll:(id)arg1;
- (void)replaceAndFindNext:(id)arg1;
- (void)replaceAndFindPrevious:(id)arg1;
- (void)revertStateWithDictionary:(id)arg1;
@property(readonly) DVTScopeBarView *scopeBarView; // @synthesize scopeBarView=_scopeBar;
@property(readonly) NSView *scopeBarsBaseView;
- (void)setupTextViewContextMenuWithMenu:(id)arg1;
- (void)showNextCommandFromHistory:(id)arg1;
- (void)showPreviousCommandFromHistory:(id)arg1 currentStringAfterPrompt:(id)arg2;
- (id)startingLocationForFindBar:(id)arg1 findingBackwards:(BOOL)arg2;
@property(readonly) BOOL tracksInputHistoryForDebugger;
- (id)undoManagerForTextView:(id)arg1;
- (void)useSelectionForReplace:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (void)viewDidInstall;
- (id)viewToShowWrapOrEndOfFileBezelOn:(id)arg1;
- (void)viewWillUninstall;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) NSScrollView *scopeBarsAdjustableScrollView;
@property(readonly) Class superclass;

@end

