/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol IDEContinuousIntegrationActionManager <NSObject>
- (void)canCreateHostedRepositoriesOnService:(id)arg1 completionHandler:(id)arg2;
- (BOOL)canUserCreateAndDeleteBotsOnServiceForBotOrIntegration:(id)arg1;
- (BOOL)canUserCreateBotsOnAnyService;
- (void)cancelIntegration:(id)arg1 withCompletionBlock:(id)arg2;
- (void)createHostedRepositoryWithName:(id)arg1 onService:(id)arg2 completionHandler:(id)arg3;
- (void)deleteBot:(id)arg1 workspace:(id)arg2 withCompletionBlock:(id)arg3;
- (void)deleteIntegration:(id)arg1 withCompletionBlock:(id)arg2;
- (void)fetchBotForBotId:(id)arg1 onService:(id)arg2 withCompletionBlock:(id)arg3;
- (void)fetchIntegrationForId:(id)arg1 onService:(id)arg2 withCompletionBlock:(id)arg3;
- (void)hostedRepositoriesOnService:(id)arg1 completionHandler:(id)arg2;
- (void)integrateBot:(id)arg1 cleanFirst:(BOOL)arg2 completionHandler:(id)arg3;
- (void)integrationsForBot:(id)arg1 max:(unsigned long long)arg2 sortNewestFirst:(BOOL)arg3 completionHandler:(id)arg4;
- (id)projectNameInBlueprintForBot:(id)arg1;
- (void)refreshWhichServicesUserCanCreateAndDeleteBots;
- (id)serviceMatchingHostName:(id)arg1;
- (id)webURLForBot:(id)arg1;
- (id)webURLForIntegration:(id)arg1;
@end

