/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "DVTBorderedView.h"

#import "DVTInvalidation.h"

@class DVTGradientImageButton, DVTStackBacktrace, IDEComparisonEditor, IDEComparisonEditorChangesStepperView, IDEPathControl, NSString;

@interface IDEComparisonEditorTimelineNavBar : DVTBorderedView <DVTInvalidation>
{
    IDEComparisonEditor *_comparisonEditor;
    IDEPathControl *_primaryPathControl;
    IDEPathControl *_secondaryPathControl;
    IDEComparisonEditorChangesStepperView *_changesStepperControl;
    DVTGradientImageButton *_timelineActivationButton;
    BOOL _showAsInset;
    BOOL _hideTimelineButton;
    BOOL _hideSecondaryPathControl;
    BOOL _hideChangesStepperControl;
}

+ (void)initialize;
- (void).cxx_destruct;
- (void)_dvt_commonInit;
- (void)centerChangesStepperControl;
@property(readonly) IDEComparisonEditorChangesStepperView *changesStepperControl; // @synthesize changesStepperControl=_changesStepperControl;
@property(retain) IDEComparisonEditor *comparisonEditor; // @synthesize comparisonEditor=_comparisonEditor;
@property BOOL hideChangesStepperControl; // @synthesize hideChangesStepperControl=_hideChangesStepperControl;
@property BOOL hideSecondaryPathControl;
@property BOOL hideTimelineButton;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)layoutTopDown;
@property(retain) IDEPathControl *primaryPathControl; // @synthesize primaryPathControl=_primaryPathControl;
- (void)primitiveInvalidate;
@property(retain) IDEPathControl *secondaryPathControl; // @synthesize secondaryPathControl=_secondaryPathControl;
@property BOOL showAsInset; // @synthesize showAsInset=_showAsInset;
@property(retain) DVTGradientImageButton *timelineActivationButton; // @synthesize timelineActivationButton=_timelineActivationButton;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

