/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@interface IDECodeSnippetCompletionScopeRowValue : NSObject
{
    NSString *_completionScope;
}

- (void).cxx_destruct;
@property(readonly) NSString *completionScope; // @synthesize completionScope=_completionScope;
@property(readonly) NSString *completionScopeDisplayName;
- (id)description;
- (id)initWithCompletionScope:(id)arg1;

@end

