/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol IDEContinuousIntegrationCreateEditBotWindowController <NSObject>
- (void)beginSessionModalForWorkspaceTabController:(id)arg1 hostWindow:(id)arg2 editingBot:(id)arg3 editingMode:(long long)arg4 withCompletionBlock:(id)arg5;
- (void)beginSessionModalForWorkspaceTabController:(id)arg1 hostWindow:(id)arg2 editingBot:(id)arg3 withCompletionBlock:(id)arg4;
@end

