/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

@class NSProgressIndicator, NSString;

@interface IDEDistributionProgressViewController : IDEViewController
{
    NSString *_message;
    NSProgressIndicator *_spinner;
}

- (void).cxx_destruct;
- (void)loadView;
@property(copy) NSString *message; // @synthesize message=_message;
- (id)nibName;
@property(retain) NSProgressIndicator *spinner; // @synthesize spinner=_spinner;

@end

