/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSTableCellView.h"

@class DVTGauge, IDECombinedDownloadsPrefPaneController, IDEComponentDownloadsPrefPaneItem, IDEDownloadableCapsuleViewController, NSButton, NSTextField, NSTrackingArea;

@interface IDEDownloadsPrefDownloadableItemTableCellView : NSTableCellView
{
    NSButton *_downloadButton;
    NSTextField *_downloadSizeField;
    DVTGauge *_progressGauge;
    IDECombinedDownloadsPrefPaneController *_controller;
    IDEComponentDownloadsPrefPaneItem *_downloadableItem;
    IDEDownloadableCapsuleViewController *_capsuleController;
    NSTrackingArea *_trackingArea;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
@property __weak IDEDownloadableCapsuleViewController *capsuleController; // @synthesize capsuleController=_capsuleController;
@property __weak IDECombinedDownloadsPrefPaneController *controller; // @synthesize controller=_controller;
- (void)download:(id)arg1;
@property(retain) NSButton *downloadButton; // @synthesize downloadButton=_downloadButton;
@property(retain) NSTextField *downloadSizeField; // @synthesize downloadSizeField=_downloadSizeField;
@property __weak IDEComponentDownloadsPrefPaneItem *downloadableItem; // @synthesize downloadableItem=_downloadableItem;
@property(retain) DVTGauge *progressGauge; // @synthesize progressGauge=_progressGauge;
@property(retain) NSTrackingArea *trackingArea; // @synthesize trackingArea=_trackingArea;

@end

