/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSTextFieldCell.h"

@class NSByteCountFormatter, NSImage, NSMutableArray, NSNumberFormatter, NSString;

@interface IDEDebugGaugeTrayCell : NSTextFieldCell
{
    double _maximumValue;
    NSMutableArray *_barValues;
    unsigned long long _numberOfValuesToKeep;
    double _maxValueFromValues;
    BOOL _maxValueIsSet;
    double _lastDoubleValue;
    double _lastSuddenIncreaseInValue;
    BOOL _haveRegisterdForHeartBeat;
    unsigned long long _lastCountOfDisplayableBars;
    double _beginAnimationTime;
    NSNumberFormatter *_noFloatFormatter;
    NSByteCountFormatter *_byteCountFormatter;
    NSByteCountFormatter *_rateCountFormatter;
    BOOL _largerValueIsBetter;
    BOOL _suppressSuddenIncreases;
    BOOL _enableAnimation;
    int _valueButtonFormat;
    unsigned long long _chartType;
    double _animationDuration;
    double _barWidth;
    double _failingPoint;
    double _warningPoint;
    NSImage *_icon;
    double _iconVerticalOffset;
    double _iconHorizontalMidpoint;
    NSString *_label;
}

+ (id)_cellsWantingHeartBeatNotification;
+ (void)_notifyCellsWantingHeartBeatNotification;
+ (void)_registerForHeartBeatNotifications:(id)arg1;
+ (void)_unregisterForHeartBeatNotifications:(id)arg1;
- (void).cxx_destruct;
- (struct CGRect)_barChartRectInFrame:(struct CGRect)arg1;
- (id)_barColorFromValue:(double)arg1 inactive:(BOOL)arg2;
- (id)_byteCountFormatter;
- (id)_byteRateFormatter;
- (void)_drawChartBarValuesWithFrame:(struct CGRect)arg1 inactive:(BOOL)arg2;
- (void)_drawChartProgressValueWithFrame:(struct CGRect)arg1 inactive:(BOOL)arg2;
- (void)_drawChartValuesWithFrame:(struct CGRect)arg1 inactive:(BOOL)arg2;
- (void)_drawChartWithFrame:(struct CGRect)arg1 inactive:(BOOL)arg2;
- (void)_drawIconInRect:(struct CGRect)arg1;
- (void)_drawLineBelowTrayCellRect:(struct CGRect)arg1;
- (void)_drawTitleAlignedLeftInRect:(struct CGRect)arg1;
- (double)_drawValueLabelAlignedRightInRect:(struct CGRect)arg1 inView:(id)arg2;
- (void)_dvt_commonInit;
- (struct CGRect)_gaugeIconRectForCellFrame:(struct CGRect)arg1;
- (BOOL)_isFailing:(double)arg1;
- (BOOL)_isWarning:(double)arg1;
- (double)_leadingSpaceToAlign:(unsigned long long)arg1 toRightOfFrame:(struct CGRect)arg2;
- (id)_noFloatFormatter;
- (unsigned long long)_numberOfBarsThatFitFrame:(struct CGRect)arg1;
- (id)_raisedEffectShadow;
- (id)_raisedEffectShadowHighlighted;
- (double)_realMaxValue;
- (void)_recordBarValue:(id)arg1;
- (void)_resetMaxValue;
- (void)_setControlViewNeedsDisplayInChartArea;
- (BOOL)_showsValueLabel;
- (id)_stringForLabelFromNumber:(id)arg1;
- (id)_valueLabel;
- (struct CGRect)_valueRectInFrame:(struct CGRect)arg1;
@property(nonatomic) double animationDuration; // @synthesize animationDuration=_animationDuration;
- (id)barValues;
@property(nonatomic) double barWidth; // @synthesize barWidth=_barWidth;
@property(nonatomic) unsigned long long chartType; // @synthesize chartType=_chartType;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
@property(readonly, nonatomic) BOOL enableAnimation; // @synthesize enableAnimation=_enableAnimation;
- (void)enqueueBarValue:(id)arg1;
@property(nonatomic) double failingPoint; // @synthesize failingPoint=_failingPoint;
- (void)hostViewWillUninstall;
@property(copy, nonatomic) NSImage *icon; // @synthesize icon=_icon;
@property(nonatomic) double iconHorizontalMidpoint; // @synthesize iconHorizontalMidpoint=_iconHorizontalMidpoint;
@property(nonatomic) double iconVerticalOffset; // @synthesize iconVerticalOffset=_iconVerticalOffset;
- (id)initTextCell:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithLabel:(id)arg1;
@property(copy) NSString *label; // @synthesize label=_label;
@property(nonatomic) BOOL largerValueIsBetter; // @synthesize largerValueIsBetter=_largerValueIsBetter;
@property(nonatomic) double maximumValue; // @synthesize maximumValue=_maximumValue;
@property(nonatomic) BOOL suppressSuddenIncreases; // @synthesize suppressSuddenIncreases=_suppressSuddenIncreases;
@property(nonatomic) int valueButtonFormat; // @synthesize valueButtonFormat=_valueButtonFormat;
@property(nonatomic) double warningPoint; // @synthesize warningPoint=_warningPoint;

@end

