/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEEditorDocument.h>

@class DVTObservingToken, IDELaunchSession;

@interface IDEDebugGaugeReportDocument : IDEEditorDocument
{
    IDELaunchSession *_launchSession;
    DVTObservingToken *_launchSessionObservingToken;
}

+ (BOOL)shouldUnlockFileURLBeforeMakingChanges;
- (void).cxx_destruct;
- (void)editorDocumentWillClose;
- (id)launchSession;
- (BOOL)readFromURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (int)readOnlyStatus;

@end

