/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "NSMenuDelegate.h"

@class DVTDelayedInvocation, IDENavigableItem, IDENavigableItemCoordinator, IDERunContextManager, NSString;

@interface IDEDestinationMenuDelegate : NSObject <NSMenuDelegate>
{
    IDERunContextManager *_runContextManager;
    IDENavigableItemCoordinator *_navigableItemCoordinator;
    IDENavigableItem *_schemeNavigable;
    DVTDelayedInvocation *_delayedInvocation;
}

+ (id)_currentRunContextManager;
+ (void)_openMoreSimulators:(id)arg1;
+ (void)addDownloadMoreSimulatorsIfNecessaryToMenu:(id)arg1 withRunContextManager:(id)arg2;
+ (void)didUpdateRunDestinationMenu:(id)arg1 withRunContextManager:(id)arg2;
+ (void)setSelectedNavigable:(id)arg1 withRunContextManager:(id)arg2;
- (void).cxx_destruct;
- (id)_destinationMenuItemsWithRunContextManager:(id)arg1;
- (id)_menuItemsForRunDestinationNavigable:(id)arg1;
- (void)_setSelectedNavigable:(id)arg1;
- (void)dealloc;
- (id)init;
- (void)menuDidClose:(id)arg1;
- (void)menuNeedsUpdate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

