/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEEditorDocumentPreviewProvider.h>

@class NSLayoutManager;

@interface IDEDummyFindReplacePreviewProvider : IDEEditorDocumentPreviewProvider
{
    NSLayoutManager *_heightLayoutManager;
}

- (void).cxx_destruct;
- (void)_clipTextToCenter:(id)arg1 focusRange:(struct _NSRange)arg2;
- (id)_defaultTextAttributes;
- (id)_resultAtIndex:(long long)arg1;
- (id)document;
- (id)generateViewWithRect:(struct CGRect)arg1;
- (double)minimumHeightForRowAtIndex:(long long)arg1 withWidth:(double)arg2;
- (void)populateView:(id)arg1 forDocumentAtIndex:(long long)arg2;
- (void)populateView:(id)arg1 forPreviewAtIndex:(long long)arg2;
- (id)preview;
- (id)previewViewIdentifier;
- (void)updateSelectedLocation:(id)arg1 forView:(id)arg2 atIndex:(long long)arg3 preview:(BOOL)arg4;

@end

