/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class DVTDeveloperAccount, DVTFilePath, DVTMutableOrderedDictionary, IDEArchive, IDEDistributionLogging, IDEDistributionMethod, IDEDistributionProvisioningSnapshot, NSArray, NSNumber, NSString;

@interface IDEDistributionContext : NSObject
{
    IDEDistributionContext *_parent;
    IDEArchive *_archive;
    IDEDistributionMethod *_distributionMethod;
    NSString *_teamID;
    DVTDeveloperAccount *_account;
    NSNumber *_distributionTask;
    IDEDistributionProvisioningSnapshot *_provisioningSnapshot;
    NSArray *_topLevelDistributionItems;
    IDEDistributionLogging *_logging;
    NSNumber *_uploadSymbols;
    NSArray *_distributionIssues;
    DVTMutableOrderedDictionary *_itemToEntitlementsProcessorsMap;
    DVTFilePath *_finalPackagePath;
    DVTMutableOrderedDictionary *_itemToProcessingResultsMap;
    id <ITunesSoftwareApplicationDescription> _applicationRecord;
    DVTDeveloperAccount *_iTunesConnectAccount;
}

- (void).cxx_destruct;
@property(retain, nonatomic) DVTDeveloperAccount *account; // @synthesize account=_account;
@property(retain, nonatomic) id <ITunesSoftwareApplicationDescription> applicationRecord; // @synthesize applicationRecord=_applicationRecord;
@property(retain, nonatomic) IDEArchive *archive; // @synthesize archive=_archive;
- (id)description;
@property(retain, nonatomic) NSArray *distributionIssues; // @synthesize distributionIssues=_distributionIssues;
@property(retain, nonatomic) IDEDistributionMethod *distributionMethod; // @synthesize distributionMethod=_distributionMethod;
@property(retain, nonatomic) NSNumber *distributionTask; // @synthesize distributionTask=_distributionTask;
@property(retain, nonatomic) DVTFilePath *finalPackagePath; // @synthesize finalPackagePath=_finalPackagePath;
- (id)flattenedDistributionItems;
@property(retain, nonatomic) DVTDeveloperAccount *iTunesConnectAccount; // @synthesize iTunesConnectAccount=_iTunesConnectAccount;
- (id)initWithParent:(id)arg1;
- (BOOL)isInAppContent;
@property(retain, nonatomic) DVTMutableOrderedDictionary *itemToEntitlementsProcessorsMap; // @synthesize itemToEntitlementsProcessorsMap=_itemToEntitlementsProcessorsMap;
@property(retain, nonatomic) DVTMutableOrderedDictionary *itemToProcessingResultsMap; // @synthesize itemToProcessingResultsMap=_itemToProcessingResultsMap;
@property(retain, nonatomic) IDEDistributionLogging *logging; // @synthesize logging=_logging;
- (id)nonChainedDescription;
@property(readonly, nonatomic) IDEDistributionContext *parent; // @synthesize parent=_parent;
@property(retain, nonatomic) IDEDistributionProvisioningSnapshot *provisioningSnapshot; // @synthesize provisioningSnapshot=_provisioningSnapshot;
@property(retain, nonatomic) NSString *teamID; // @synthesize teamID=_teamID;
@property(retain, nonatomic) NSArray *topLevelDistributionItems; // @synthesize topLevelDistributionItems=_topLevelDistributionItems;
@property(retain, nonatomic) NSNumber *uploadSymbols; // @synthesize uploadSymbols=_uploadSymbols;
- (id)team;

@end

