/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "IDEDebugBarContentProvider.h"

@class DVTObservingToken, IDEDebugBar, NSArray, NSString;

@interface IDEDebugBarContentProvider : NSObject <IDEDebugBarContentProvider>
{
    IDEDebugBar *_debugBar;
    NSArray *_controlViews;
    DVTObservingToken *_workspaceFinishedLoadingObservation;
    DVTObservingToken *_currentDebugSessionObservation;
    DVTObservingToken *_currentDebugSessionStateObservation;
}

- (void).cxx_destruct;
- (id)currentDebugSession;
- (void)currentDebugSessionDidChange;
- (void)currentDebugSessionStateDidChange;
- (id)currentLaunchSession;
@property(retain) IDEDebugBar *debugBar; // @synthesize debugBar=_debugBar;
@property(copy) NSArray *debugBarControlViews; // @synthesize debugBarControlViews=_controlViews;
- (id)init;
- (void)wasAttachedToDebugBar:(id)arg1;
- (void)willBeDetachedFromDebugBar:(id)arg1;
- (void)workspaceDidFinishLoading;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

