/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "IDEDiagnosticActivityLogMessage.h"

@interface IDEDiagnosticActivityLogMessage (KitAdditions)
+ (id)keyPathsForValuesAffectingValid;
- (id)childExplorableItems;
- (id)exploredIssue;
- (BOOL)isNoteSeverity;
- (id)parentExplorableItem;
- (BOOL)valid;
@end

