/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEEditorDocument.h>

@class DVTObservingToken, IDEContainer;

@interface IDEEditorContainerDocument : IDEEditorDocument
{
    IDEContainer *_container;
    DVTObservingToken *_containerValidObservingToken;
}

+ (Class)_containerClass;
+ (BOOL)autosavesInPlace;
+ (id)keyPathsForValuesAffectingReadOnlyItemURL;
+ (id)keyPathsForValuesAffectingReadOnlyStatus;
+ (BOOL)shouldTrackFileSystemChanges;
- (void).cxx_destruct;
- (BOOL)canRevert;
@property(retain, nonatomic) IDEContainer *container; // @synthesize container=_container;
- (void)editorDocumentWillClose;
- (BOOL)makeWritableWithError:(id *)arg1;
- (void)printDocument:(id)arg1;
- (BOOL)readFromURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;
- (id)readOnlyItemURL;
- (int)readOnlyStatus;
- (void)revertDocumentToSaved:(id)arg1;
- (void)runPageLayout:(id)arg1;
- (void)saveDocument:(id)arg1;
- (void)saveDocumentAs:(id)arg1;
- (void)saveDocumentTo:(id)arg1;
- (void)updateChangeCount:(unsigned long long)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;
- (BOOL)writeToURL:(id)arg1 ofType:(id)arg2 error:(id *)arg3;

@end

