/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "DVTInvalidation.h"

@class DVTDispatchLock, DVTPointerArray, DVTStackBacktrace, IDEEditorDocument<DVTTextReplacable>, IDENavigableItem, IDEWorkspaceDocument, NSArray, NSImage, NSIndexSet, NSString, NSURL;

@interface IDEEditorDocumentPreviewProvider : NSObject <DVTInvalidation>
{
    IDENavigableItem *_navigable;
    IDEEditorDocument<DVTTextReplacable> *_document;
    IDEEditorDocument<DVTTextReplacable> *_preview;
    double _branchTime;
    NSArray *_allResults;
    NSIndexSet *_replaceResultsIndexSet;
    NSString *_replacementString;
    NSArray *_documentLocations;
    NSArray *_previewLocations;
    DVTPointerArray *_originalRowViewCache;
    DVTPointerArray *_previewRowViewCache;
    NSURL *_url;
    DVTDispatchLock *_cacheLock;
    IDEWorkspaceDocument *_workspaceDocument;
    BOOL _disclosed;
}

+ (void)initialize;
+ (double)minimumRowHeight;
+ (id)performanceLogAspect;
+ (id)populationQueue;
- (void).cxx_destruct;
@property(readonly) NSArray *allResults;
@property(readonly) IDENavigableItem *batchFindNavigable; // @synthesize batchFindNavigable=_navigable;
@property(retain) DVTDispatchLock *cacheLock; // @synthesize cacheLock=_cacheLock;
- (void)didReplaceFindResults;
@property BOOL disclosed; // @synthesize disclosed=_disclosed;
@property(readonly) IDEEditorDocument<DVTTextReplacable> *document; // @synthesize document=_document;
- (id)generateViewWithRect:(struct CGRect)arg1;
@property(readonly) NSImage *image;
- (id)initWithBatchFindGroupNavigableItem:(id)arg1 workspaceDocument:(id)arg2;
- (void)invalidatePreview;
- (double)minimumHeightForRowAtIndex:(long long)arg1 withWidth:(double)arg2;
@property(readonly) NSString *name;
@property(readonly) NSArray *originalLocations;
- (void)populateView:(id)arg1 forDocumentAtIndex:(long long)arg2;
- (void)populateView:(id)arg1 forPreviewAtIndex:(long long)arg2;
@property(readonly) IDEEditorDocument<DVTTextReplacable> *preview; // @synthesize preview=_preview;
@property(readonly) NSArray *previewLocations;
- (void)primitiveInvalidate;
@property(copy, nonatomic) NSIndexSet *replaceResultsIndexSet; // @synthesize replaceResultsIndexSet=_replaceResultsIndexSet;
@property(retain, nonatomic) NSString *replacementString; // @synthesize replacementString=_replacementString;
@property(readonly) long long rowCount;
- (void)setupDocument;
- (void)setupPreview;
- (void)updateReplacementsInPreview;
- (void)updateSelectedLocation:(id)arg1 forView:(id)arg2 atIndex:(long long)arg3 preview:(BOOL)arg4;
@property(readonly) NSURL *url; // @synthesize url=_url;
- (void)willReplaceFindResults;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

