/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "IDEFileReference.h"

@interface IDEFileReference (InspectorProperties)
+ (id)keyPathsForValuesAffectingIdeInspectedAssignedDataType;
+ (id)keyPathsForValuesAffectingIdeInspectedIsNameEditable;
+ (id)keyPathsForValuesAffectingIdeInspectedMessageForChoosingRelativeLocation;
+ (id)keyPathsForValuesAffectingIdeInspectedNilResolutionStrategyPlaceholder;
+ (id)keyPathsForValuesAffectingIdeInspectedRelativeLocationContainingFolderPlaceholder;
+ (id)keyPathsForValuesAffectingIdeInspectedRelativeLocationIsEditable;
+ (id)keyPathsForValuesAffectingIdeInspectedRelativeLocationPlaceholder;
+ (id)keyPathsForValuesAffectingIdeInspectedRelativeLocationShouldChooseDirectory;
+ (id)keyPathsForValuesAffectingIdeInspectedRelativeLocationShouldChooseFile;
+ (id)keyPathsForValuesAffectingIdeInspectedShowsFileTypePopUp;
- (id)applicableInspectorsForCategory:(id)arg1 suggestion:(id)arg2;
- (id)ideInspectedAssignedDataType;
- (BOOL)ideInspectedIsNameEditable;
- (id)ideInspectedMessageForChoosingRelativeLocation;
- (id)ideInspectedNilResolutionStrategyPlaceholder;
- (id)ideInspectedRelativeLocationContainingFolderPlaceholder;
- (BOOL)ideInspectedRelativeLocationIsEditable;
- (id)ideInspectedRelativeLocationPlaceholder;
- (BOOL)ideInspectedRelativeLocationShouldChooseDirectory;
- (BOOL)ideInspectedRelativeLocationShouldChooseFile;
- (BOOL)ideInspectedShowsFileTypePopUp;
- (void)setIdeInspectedAssignedDataType:(id)arg1;
@end

