/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSImage, NSRunningApplication, NSString;

@interface IDEFirstLaunchAppToQuit : NSObject
{
    NSString *_displayName;
    NSRunningApplication *_runningApplication;
}

- (void).cxx_destruct;
- (id)_initWithNSRunningApplication:(id)arg1;
- (id)_initWithNSRunningApplication:(id)arg1 customDisplayName:(id)arg2;
@property(readonly) NSString *displayName; // @synthesize displayName=_displayName;
@property(readonly) NSImage *icon;
@property(readonly) NSRunningApplication *runningApplication; // @synthesize runningApplication=_runningApplication;

@end

