/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "IDEKeyDrivenNavigableItemRepresentedObject.h"

@class DVTDocumentLocation, DVTFileDataType, DVTFilePath, DVTSDK, IDEFileReference, IDETypeIdentifier, NSArray, NSImage, NSMutableArray, NSString;

@interface IDEFrameworkFilePath : NSObject <IDEKeyDrivenNavigableItemRepresentedObject>
{
    DVTFilePath *_filePath;
    NSString *_name;
    NSMutableArray *_childPathComponents;
    DVTSDK *_SDK;
    unsigned long long _frameworkFilePathType;
}

+ (id)_allSDKFrameworksFilePaths;
+ (void)_recalclulateAllSDKFrameworksFilePaths;
+ (id)_rootFrameworksFilePath;
+ (void)_setAllSDKFrameworksFilePaths:(id)arg1;
+ (BOOL)isFrameworkURL:(id)arg1;
+ (id)keyPathsForValuesAffectingNavigableItem_documentType;
+ (id)structureNavigableItemForFrameworkURL:(id)arg1 inCoordinator:(id)arg2 inWorkspace:(id)arg3 error:(id *)arg4;
- (void).cxx_destruct;
@property(retain) DVTSDK *SDK; // @synthesize SDK=_SDK;
- (id)_pathOfNamesForDescendantWithFilePath:(id)arg1;
@property(copy, nonatomic) NSArray *childPathComponents; // @synthesize childPathComponents=_childPathComponents;
@property(readonly, copy) NSString *description;
@property(readonly, copy) DVTFilePath *filePath; // @synthesize filePath=_filePath;
@property(readonly) unsigned long long frameworkFilePathType; // @synthesize frameworkFilePathType=_frameworkFilePathType;
@property(readonly) unsigned long long hash;
@property(readonly, copy) IDETypeIdentifier *ideModelObjectTypeIdentifier;
- (id)init;
- (id)initWithFilePath:(id)arg1 name:(id)arg2 type:(unsigned long long)arg3;
- (BOOL)isEqual:(id)arg1;
@property(readonly, copy) NSString *name; // @synthesize name=_name;
- (id)navigableItem_conformanceString;
@property(readonly) DVTDocumentLocation *navigableItem_contentDocumentLocation;
@property(readonly) DVTFileDataType *navigableItem_documentType;
@property(readonly) NSImage *navigableItem_image;
@property(readonly) NSString *navigableItem_name;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) IDEFileReference *navigableItem_fileReference;
@property(readonly) NSString *navigableItem_groupIdentifier;
@property(readonly) BOOL navigableItem_isLeaf;
@property(readonly) BOOL navigableItem_isMajorGroup;
@property(readonly) NSString *navigableItem_toolTip;
@property(readonly) Class superclass;

@end

