/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSArray, NSString;

@interface IDEFileInspectorFileTypeGroup : NSObject
{
    NSString *_displayName;
    NSArray *_fileDataTypes;
}

+ (id)allDisplayedEntries;
+ (id)allGroups;
+ (id)fileDataTypesPerGroupID;
+ (id)fileGroups;
+ (id)folderGroups;
+ (id)groupEntryExtensionPoint;
+ (id)groupExtensionPoint;
+ (id)groupsByFilteringFileDataTypes:(id)arg1;
- (void).cxx_destruct;
- (id)description;
@property(readonly) NSString *displayName; // @synthesize displayName=_displayName;
@property(readonly) NSArray *fileDataTypes; // @synthesize fileDataTypes=_fileDataTypes;
- (id)initWithDisplayName:(id)arg1 fileDataTypes:(id)arg2;

@end

