/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

#import "NSTableViewDelegate.h"

@class DVTBorderedView, DVTObservingToken, DVTReplacementView, DVTScrollView, DVTTabChooserView, NSArray, NSArrayController, NSColor, NSFont, NSObjectController, NSString, NSTableView, NSView;

@interface IDEFontAndColorPrefsPaneController : IDEViewController <NSTableViewDelegate>
{
    DVTReplacementView *preferenceSetReplacementView;
    DVTBorderedView *_fontAndColorBorderView;
    DVTTabChooserView *_tabChooserView;
    NSTableView *_fontAndColorItemTable;
    NSArrayController *_categoriesArrayController;
    NSObjectController *_currentThemeObjectController;
    DVTBorderedView *_generalColorView;
    NSView *_sourceEditorGeneralView;
    NSView *_consoleGeneralView;
    NSArray *_fontAndColorItems;
    DVTObservingToken *_selectedTabObserver;
    DVTObservingToken *_backgroundColorObserver;
    DVTObservingToken *_selectionIndexesObserver;
    DVTScrollView *_scrollView;
}

+ (void)initialize;
- (void).cxx_destruct;
- (void)_handleTabChanged;
- (void)_initTabChooserView;
- (void)_sourceTextColorsChanged:(id)arg1;
- (id)_theme;
- (void)_updateBindingsBasedOnSelectedTab;
- (void)_updateFontPickerAndColorWell;
@property(readonly) NSArrayController *categoriesArrayController; // @synthesize categoriesArrayController=_categoriesArrayController;
- (void)changeFont:(id)arg1;
- (void)chooseFont:(id)arg1;
@property(copy) NSColor *combinedSyntaxColor;
@property(copy) NSFont *combinedSyntaxFont;
@property(retain) NSArray *fontAndColorItems; // @synthesize fontAndColorItems=_fontAndColorItems;
- (void)loadView;
- (void)primitiveInvalidate;
@property(retain) DVTScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (void)viewDidInstall;
- (void)viewWillUninstall;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

