/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEContainerContentsMediaRepository.h>

@class NSMutableDictionary, NSSet;

@interface IDEFileMediaRepository : IDEContainerContentsMediaRepository
{
    NSMutableDictionary *_resourcesByPath;
    NSSet *_resources;
}

+ (id)allSupportedMediaFileDataTypes;
+ (id)containerObserverToRepositoryMap;
+ (id)handleFileReferenceContainerObserverChange:(long long)arg1 forPath:(id)arg2 withDataType:(id)arg3;
- (void).cxx_destruct;
- (void)_fileReferenceObserverDidUpdateOrAddResourcesByPath:(id)arg1;
- (id)_resourcesRemovedBecauseFileReferenceObserverDidRemovePaths:(id)arg1;
- (void)fileReferenceObserverDidReportUpdatedAndAddedResourcesByPath:(id)arg1 removedPaths:(id)arg2;
- (id)initWithContainerObserver:(id)arg1;
- (void)primitiveInvalidate;
- (id)resources;

@end

