/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "DVTInvalidation.h"
#import "IDEKeyDrivenNavigableItemRepresentedObject.h"

@class DVTDocumentLocation, DVTFileDataType, DVTObservingToken, DVTStackBacktrace, IDEFileReference, IDENavigableItem, NSArray, NSImage, NSString;

@interface IDEGeniusResultsGraphNode : NSObject <IDEKeyDrivenNavigableItemRepresentedObject, DVTInvalidation>
{
    DVTObservingToken *_manualDomainRootChildItemsObservingToken;
    int _type;
    NSString *_identifier;
    NSImage *_image;
    NSString *_name;
    NSArray *_subitems;
    NSString *_manualDomainIdentifier;
    IDENavigableItem *_manualDomainRootNavigableItem;
}

+ (id)_rootNodeForGeniusResults:(id)arg1 editorContext:(id)arg2 includeJumpToCounterpartCategory:(BOOL)arg3 includeManualCategory:(BOOL)arg4;
+ (id)_rootNodeForGeniusResultsWithJumpToCounterpartCategory:(id)arg1;
+ (id)_rootNodeForGeniusResultsWithManualCategory:(id)arg1 editorContext:(id)arg2;
+ (void)initialize;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (id)ideModelObjectTypeIdentifier;
@property(copy) NSString *identifier; // @synthesize identifier=_identifier;
@property(retain) NSImage *image; // @synthesize image=_image;
- (id)initWithType:(int)arg1 identifier:(id)arg2 image:(id)arg3 name:(id)arg4 subitems:(id)arg5;
@property(readonly, copy) NSString *manualDomainIdentifier; // @synthesize manualDomainIdentifier=_manualDomainIdentifier;
@property(copy) IDENavigableItem *manualDomainRootNavigableItem; // @synthesize manualDomainRootNavigableItem=_manualDomainRootNavigableItem;
@property(copy) NSString *name; // @synthesize name=_name;
- (id)nameWithSubitemCount;
@property(readonly) DVTDocumentLocation *navigableItem_contentDocumentLocation;
@property(readonly) DVTFileDataType *navigableItem_documentType;
@property(readonly) IDEFileReference *navigableItem_fileReference;
- (id)navigableItem_identifierForRepresentedObjectAtIndex:(unsigned long long)arg1 inRelationshipKeyPath:(id)arg2;
@property(readonly) NSImage *navigableItem_image;
- (unsigned long long)navigableItem_indexOfRepresentedObjectForIdentifier:(id)arg1 inRelationshipKeyPath:(id)arg2;
@property(readonly) NSString *navigableItem_name;
- (void)primitiveInvalidate;
- (void)setChildrenToURL:(id)arg1;
- (void)setManualDomainIdentifier:(id)arg1 rootNavigableItem:(id)arg2;
@property(copy, nonatomic) NSArray *subitems; // @synthesize subitems=_subitems;
@property int type; // @synthesize type=_type;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) NSString *navigableItem_groupIdentifier;
@property(readonly) BOOL navigableItem_isLeaf;
@property(readonly) BOOL navigableItem_isMajorGroup;
@property(readonly) NSString *navigableItem_toolTip;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

