/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSView.h"

@interface IDEGaugeReportTopSectionContentBackground : NSView
{
    BOOL _lastComponent;
}

- (void)drawRect:(struct CGRect)arg1;
@property BOOL lastComponent; // @synthesize lastComponent=_lastComponent;

@end

