/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "IDEGroup.h"

@interface IDEGroup (InspectorProperties)
+ (id)keyPathsForValuesAffectingIdeInspectedIsNameEditable;
- (id)applicableInspectorsForCategory:(id)arg1 suggestion:(id)arg2;
- (BOOL)ideInspectedIsNameEditable;
- (id)ideInspectedRelativeLocationContainingFolderPlaceholder;
- (id)ideInspectedRelativeLocationPlaceholder;
- (BOOL)ideInspectedRelativeLocationShouldChooseDirectory;
- (BOOL)ideInspectedRelativeLocationShouldChooseFile;
@end

