/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "IDEIndexSymbol.h"

@interface IDEIndexSymbol (IDEKitExtensions)
- (id)completionText;
- (id)descriptionText;
- (id)displayText;
- (id)displayType;
- (id)icon;
- (void)infoViewControllerWithWidth:(double)arg1 context:(id)arg2 completionBlock:(id)arg3;
- (id)largeIcon;
- (BOOL)notRecommended;
- (id)parentText;
- (long long)priority;
- (long long)priorityBucket;
- (unsigned long long)priorityComparatorKind;
- (void)setPriority:(long long)arg1;
@end

