/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEInspectorAbstractActionProperty.h>

@class IDEInspectorKeyPath, NSArray, NSPopUpButton, NSString;

@interface IDEInspectorActionMenuProperty : IDEInspectorAbstractActionProperty
{
    NSArray *_menuItems;
    IDEInspectorKeyPath *_menuItemsKeyPath;
    NSString *_title;
    IDEInspectorKeyPath *_titleKeyPath;
    NSPopUpButton *_pullDown;
}

- (void).cxx_destruct;
- (void)applyMenuItemsToPullDown:(id)arg1;
- (double)baseline;
@property(retain, nonatomic) NSPopUpButton *pullDown; // @synthesize pullDown=_pullDown;
- (void)refresh;
- (void)refreshTarget:(id)arg1;
- (void)refreshTitle:(id)arg1;
- (void)setupRefreshTriggersAndConfigure;
- (id)staticMenuItems;

@end

