/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEEntitlementsProcessorViewController.h>

@class NSArray, NSArrayController;

@interface IDEiCloudEntitlementsProcessorViewController : IDEEntitlementsProcessorViewController
{
    NSArray *_availableEnvironments;
    NSArrayController *_availableEnvironmentsController;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *availableEnvironments; // @synthesize availableEnvironments=_availableEnvironments;
@property(retain, nonatomic) NSArrayController *availableEnvironmentsController; // @synthesize availableEnvironmentsController=_availableEnvironmentsController;
- (void)viewDidInstall;

@end

