/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEInspectorProperty.h>

@class IDEAttributedStringControl, IDEInspectorKeyPath;

@interface IDEInspectorAttributedStringProperty : IDEInspectorProperty
{
    IDEAttributedStringControl *_attributedStringControl;
    IDEInspectorKeyPath *_valueKeyPath;
}

- (void).cxx_destruct;
- (void)awakeFromNib;
- (double)baseline;
- (id)findIndicatorContentViewWithContext:(id)arg1;
- (void)primitiveInvalidate;
- (void)refresh;
- (void)setupRefreshTriggersAndConfigure;
- (void)userDidUpdateAttributedStringValue:(id)arg1;

@end

