/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEInspectorEnumerationProperty.h>

@class IDEInspectorKeyPath, IDEInspectorResizableSegmentedControlView, NSSegmentedControl, NSTextField;

@interface IDEInspectorImageEnumerationProperty : IDEInspectorEnumerationProperty
{
    IDEInspectorKeyPath *_valueKeyPath;
    IDEInspectorResizableSegmentedControlView *_resizableSegmentedControlView;
    NSSegmentedControl *_segmentedControl;
    NSTextField *_label;
}

- (void).cxx_destruct;
- (double)baseline;
- (void)configureEnumeratedOptions;
- (BOOL)hasTitle;
@property(retain, nonatomic) NSTextField *label; // @synthesize label=_label;
- (id)nibName;
- (void)refresh;
@property(retain, nonatomic) IDEInspectorResizableSegmentedControlView *resizableSegmentedControlView; // @synthesize resizableSegmentedControlView=_resizableSegmentedControlView;
@property(retain, nonatomic) NSSegmentedControl *segmentedControl; // @synthesize segmentedControl=_segmentedControl;
- (void)setupRefreshTriggersAndConfigure;
- (void)userDidChangeValue:(id)arg1;

@end

