/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDENavigableItem.h>

@class NSDictionary;

@interface IDEKeyDrivenNavigableItem : IDENavigableItem
{
    NSDictionary *_cachedPropertyValues;
    struct {
        unsigned int _invalidatingChildItems:1;
        unsigned int _disposing:1;
        unsigned int _reserved:30;
    } _idekdniFlags;
}

+ (id)_automatic_keyPathsForValuesAffectingMajorGroup;
+ (void)_customizeNewNavigableItemClass:(Class)arg1 forModelObjectClass:(Class)arg2 extension:(id)arg3;
+ (unsigned long long)countOfNavigableItemsForRepresentedObject:(id)arg1;
+ (id)keyPathsForValuesAffectingConflictStateForUpdateOrMerge;
+ (id)keyPathsForValuesAffectingFileReference;
+ (id)keyPathsForValuesAffectingGroupIdentifier;
+ (id)keyPathsForValuesAffectingImage;
+ (id)keyPathsForValuesAffectingName;
+ (id)keyPathsForValuesAffectingProgressValue;
+ (id)keyPathsForValuesAffectingSourceControlCurrentRevision;
+ (id)keyPathsForValuesAffectingSourceControlLastModifiedDate;
+ (id)keyPathsForValuesAffectingSourceControlLocalStatus;
+ (id)keyPathsForValuesAffectingSourceControlLocalStatusFlag;
+ (id)keyPathsForValuesAffectingSourceControlServerStatus;
+ (id)keyPathsForValuesAffectingSourceControlServerStatusFlag;
+ (id)keyPathsForValuesAffectingToolTip;
+ (id)navigableItemsForRepresentedObject:(id)arg1;
+ (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void).cxx_destruct;
- (BOOL)_automatic_isMajorGroup;
- (id)_cachedPropertyValues;
- (id)_childItemsKeyPath;
- (void)_configurePropertyObservingForKey:(id)arg1;
- (void)_propagateFilterPredicateToChildItems;
- (void)_refreshChildItem:(id)arg1;
- (void)_registerInNavigableItemByRepresentedObjectMap;
- (void)_removeFromNavigableItemByRepresentedObjectMap;
- (void)_setCoordinator:(id)arg1;
- (void)_setRepresentedObject:(id)arg1;
- (void)cacheValue:(id)arg1 forProperty:(id)arg2;
- (id)cachedPropertyValues;
- (id)cachedValueForProperty:(id)arg1;
- (id)childItemsKeyPath;
- (id)childRepresentedObjects;
- (unsigned long long)conflictStateForUpdateOrMerge;
- (id)contentDocumentLocation;
- (id)documentType;
- (id)fileReference;
- (id)groupIdentifier;
- (id)identifierForChildItem:(id)arg1;
- (id)image;
- (unsigned long long)indexOfChildItemForIdentifier:(id)arg1;
- (id)initWithRepresentedObject:(id)arg1;
- (void)invalidateChildItems;
- (void)invalidateValueForKey:(id)arg1;
- (BOOL)isLeaf;
- (BOOL)isMajorGroup;
- (id)name;
- (void)primitiveInvalidate;
- (long long)progressValue;
- (BOOL)representedObjectSupportsVariableConformanceString;
- (id)sourceControlCurrentRevision;
- (id)sourceControlLastModifiedDate;
- (id)sourceControlLocalStatus;
- (int)sourceControlLocalStatusFlag;
- (id)sourceControlServerStatus;
- (int)sourceControlServerStatusFlag;
- (id)sourceControlSourceTreeName;
- (id)toolTip;
- (void)willAccessChildItems;

@end

