/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

#import "DVTOutlineViewDelegate.h"
#import "IDEFilterControlBarTarget.h"
#import "IDEKeyBindingFieldCellDelegate.h"

@class DVTBorderedView, DVTImageAndTextCell, DVTObservingToken, DVTOutlineView, DVTPreferenceSetManager, DVTReplacementView, IDEFilterControlBar, NSArray, NSButton, NSMenu, NSScrollView, NSString, NSTextField, NSTreeController;

@interface IDEKeyBindingsPrefsPaneController : IDEViewController <DVTOutlineViewDelegate, IDEKeyBindingFieldCellDelegate, IDEFilterControlBarTarget>
{
    NSArray *_keyBindingItems;
    NSString *_searchString;
    int _displayScope;
    int _searchScope;
    NSString *_statusText;
    NSArray *_conflictStatusItemCells;
    NSArray *_conflictWithHotKeyStatusItemCells;
    DVTObservingToken *_currentPreferenceSetObservingToken;
    DVTObservingToken *_contentNeedsSavingObservingToken;
    unsigned long long _lastLockedModifierMask;
    unsigned long long _lastUnlockedModifierMask;
    id _windowDidBecomeMainNotificationObserver;
    id _activeTabControllerNotificationObserver;
    NSButton *_displayAllScopeButton;
    NSButton *_displayMenuScopeButton;
    NSButton *_displayTextScopeButton;
    NSButton *_displayModifiedScopeButton;
    NSButton *_displayConflictsScopeButton;
    IDEFilterControlBar *_filterControlBar;
    NSMenu *_searchFieldMenu;
    NSScrollView *_scrollView;
    DVTBorderedView *_containerBorderedView;
    DVTBorderedView *_scopeBarBorderedView;
    DVTBorderedView *_keyBindingsBorderedView;
    DVTReplacementView *_preferenceSetReplacementView;
    DVTOutlineView *_keyBindingsOutlineView;
    NSTreeController *_keyBindingsController;
    DVTImageAndTextCell *_titleCell;
    NSTextField *_statusTextField;
}

+ (id)keyPathsForValuesAffectingSearchWords;
- (void).cxx_destruct;
- (id)_attributedStringByHighlightingFindResults:(id)arg1;
- (void)_conflictStatusButtonCellAction:(id)arg1;
- (void)_displayScopeButtonAction:(id)arg1;
- (id)_findResultAttributes;
- (id)_keyBindingItemForItem:(id)arg1;
- (BOOL)_keyBindingOutlineViewNeedsGroupItem;
- (void)_searchScopeMenuItemAction:(id)arg1;
- (void)_showConflictedKeyBindings;
- (void)_showConflictedKeyBindingsAndUpdateScopeButtons;
- (void)_showConflictedKeyBindingsStatusForKeyBinding:(id)arg1;
- (id)_subtitleForKeyBindingItem:(id)arg1;
- (void)_updateAlternateKeyBindingsForKeyBinding:(id)arg1;
- (void)_updateScopeButtons;
- (void)_userUpdateAlternateKeyBindingsForKeyBinding:(id)arg1;
- (void)_verticallyCenterView:(id)arg1;
@property(nonatomic) int displayScope; // @synthesize displayScope=_displayScope;
- (id)filterButtonMenu;
- (id)filterDefinitionIdentifier;
- (void)keyBindingCellFieldDidEndEditing:(id)arg1;
- (id)keyBindingFieldCell:(id)arg1 alternateKeyBindingsForKeyBinding:(id)arg2;
- (BOOL)keyBindingFieldCell:(id)arg1 keyboardShortcutIsPrefix:(id)arg2;
- (id)keyBindingFieldCell:(id)arg1 validatedKeyboardShortcut:(id)arg2;
- (BOOL)keyBindingFieldCellAllowsMultipleKeyboardShortcut:(id)arg1;
- (void)keyBindingFieldCellWillRemoveKeyboardShortcut:(id)arg1;
- (id)keyBindingFieldCellWillReturnAttributedString:(id)arg1;
@property(copy, nonatomic) NSArray *keyBindingItems; // @synthesize keyBindingItems=_keyBindingItems;
- (void)loadView;
- (id)outlineView:(id)arg1 dataCellForTableColumn:(id)arg2 item:(id)arg3;
- (BOOL)outlineView:(id)arg1 doCommandBySelector:(SEL)arg2;
- (BOOL)outlineView:(id)arg1 isGroupItem:(id)arg2;
- (id)outlineView:(id)arg1 selectionIndexesForProposedSelection:(id)arg2;
- (BOOL)outlineView:(id)arg1 shouldEditTableColumn:(id)arg2 item:(id)arg3;
- (BOOL)outlineView:(id)arg1 shouldShowOutlineCellForItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 shouldTrackCell:(id)arg2 forTableColumn:(id)arg3 item:(id)arg4;
- (void)outlineView:(id)arg1 sortDescriptorsDidChange:(id)arg2;
- (id)outlineView:(id)arg1 toolTipForCell:(id)arg2 rect:(struct CGRect *)arg3 tableColumn:(id)arg4 item:(id)arg5 mouseLocation:(struct CGPoint)arg6;
- (void)outlineView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 item:(id)arg4;
- (void)outlineViewSelectionDidChange:(id)arg1;
- (void)outlineViewSelectionIsChanging:(id)arg1;
@property(readonly) DVTPreferenceSetManager *preferenceSetManager;
- (void)primitiveInvalidate;
@property(nonatomic) int searchScope; // @synthesize searchScope=_searchScope;
@property(copy, nonatomic) NSString *searchString; // @synthesize searchString=_searchString;
@property(readonly, copy) NSArray *searchWords;
@property(copy) NSString *statusText; // @synthesize statusText=_statusText;
- (void)updateKeyBindingsItems;
- (BOOL)validateMenuItem:(id)arg1;
- (void)viewDidInstall;
- (void)viewWillUninstall;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

