/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "IDEKeyDrivenNavigableItemRepresentedObject.h"

@class DVTDocumentLocation, DVTFileDataType, IDEFileReference, IDELogNavigatorItem, NSDate, NSImage, NSString;

@interface IDELogNavigatorLoadMoreItem : NSObject <IDEKeyDrivenNavigableItemRepresentedObject>
{
    NSImage *_refreshImage;
    NSString *_navigableItem_name;
    NSString *_subtitle;
    long long _navigableItem_progressValue;
    unsigned long long _count;
    id _firstItem;
    NSDate *_loadMoreStartDate;
    IDELogNavigatorItem *_logNavigatorItem;
    unsigned long long _additionalCount;
}

- (void).cxx_destruct;
@property(nonatomic) unsigned long long additionalCount; // @synthesize additionalCount=_additionalCount;
@property(readonly, nonatomic) unsigned long long count; // @synthesize count=_count;
- (long long)currentStep;
@property(retain, nonatomic) id firstItem; // @synthesize firstItem=_firstItem;
- (id)initWithLogNavigatorItem:(id)arg1 additionalCount:(unsigned long long)arg2;
- (void)loadMore;
@property(readonly, nonatomic) NSDate *loadMoreStartDate; // @synthesize loadMoreStartDate=_loadMoreStartDate;
@property(retain, nonatomic) IDELogNavigatorItem *logNavigatorItem; // @synthesize logNavigatorItem=_logNavigatorItem;
@property(readonly, nonatomic) NSImage *navigableItem_image;
@property(retain, nonatomic) NSString *navigableItem_name; // @synthesize navigableItem_name=_navigableItem_name;
@property(nonatomic) long long navigableItem_progressValue; // @synthesize navigableItem_progressValue=_navigableItem_progressValue;
- (long long)progress;
- (unsigned long long)result;
@property(retain, nonatomic) NSString *subtitle; // @synthesize subtitle=_subtitle;
- (void)update;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTDocumentLocation *navigableItem_contentDocumentLocation;
@property(readonly) DVTFileDataType *navigableItem_documentType;
@property(readonly) IDEFileReference *navigableItem_fileReference;
@property(readonly) NSString *navigableItem_groupIdentifier;
@property(readonly) BOOL navigableItem_isLeaf;
@property(readonly) BOOL navigableItem_isMajorGroup;
@property(readonly) NSString *navigableItem_toolTip;
@property(readonly) Class superclass;

@end

