/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

#import "DVTFindBarFindable.h"
#import "IDEBuildResultsOutlineDelegate.h"

@class DVTObservingToken, IDEActivityLogSection, IDEBuildResultsOutlineLogic, IDEEditor, NSArray, NSBox, NSPopUpButton, NSString, XCBuildResultsOutlineView;

@interface IDELogViewController : IDEViewController <DVTFindBarFindable, IDEBuildResultsOutlineDelegate>
{
    BOOL _showAllResults;
    BOOL _showBySteps;
    BOOL _lastFindResult;
    IDEActivityLogSection *_activityLogSection;
    IDEEditor *_editor;
    id <IDELogViewControllerDelegate> _delegate;
    DVTObservingToken *_activityLogSectionUpdateToken;
    id _documentSizeUpdateToken;
    NSPopUpButton *_scopeBarMessagesPopup;
    IDEBuildResultsOutlineLogic *_outlineLogic;
    XCBuildResultsOutlineView *_buildResultsOutlineView;
    XCBuildResultsOutlineView *_buildIssuesOutlineView;
    NSBox *_containerView;
    NSArray *_currentSelectedDocumentLocations;
    NSArray *_currentSelectedItems;
    IDEActivityLogSection *_lastFindResultSection;
    struct _NSRange _lastFindResultRange;
}

- (void).cxx_destruct;
- (void)_cancelObservationToken;
- (void)_setShowSteps:(BOOL)arg1 showWarnings:(BOOL)arg2 showErrors:(BOOL)arg3 showAnalyzerResults:(BOOL)arg4;
- (void)_updateShowSteps:(BOOL)arg1 showWarnings:(BOOL)arg2 showErrors:(BOOL)arg3 showAnalyzerResults:(BOOL)arg4;
- (void)_updateShownView;
- (id)activeView;
@property(retain) IDEActivityLogSection *activityLogSection; // @synthesize activityLogSection=_activityLogSection;
@property(retain) DVTObservingToken *activityLogSectionUpdateToken; // @synthesize activityLogSectionUpdateToken=_activityLogSectionUpdateToken;
- (id)attributesForScopeBarMenuItems;
@property(retain) XCBuildResultsOutlineView *buildIssuesOutlineView; // @synthesize buildIssuesOutlineView=_buildIssuesOutlineView;
@property(retain) XCBuildResultsOutlineView *buildResultsOutlineView; // @synthesize buildResultsOutlineView=_buildResultsOutlineView;
- (id)configureOutlineView:(id)arg1;
@property(retain) NSBox *containerView; // @synthesize containerView=_containerView;
@property(copy) NSArray *currentSelectedDocumentLocations; // @synthesize currentSelectedDocumentLocations=_currentSelectedDocumentLocations;
@property(copy) NSArray *currentSelectedItems; // @synthesize currentSelectedItems=_currentSelectedItems;
@property(retain) id <IDELogViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain) id documentSizeUpdateToken; // @synthesize documentSizeUpdateToken=_documentSizeUpdateToken;
- (void)doubleClickDocumentLocation:(id)arg1;
@property(retain) IDEEditor *editor; // @synthesize editor=_editor;
@property BOOL lastFindResult; // @synthesize lastFindResult=_lastFindResult;
@property struct _NSRange lastFindResultRange; // @synthesize lastFindResultRange=_lastFindResultRange;
@property(retain) IDEActivityLogSection *lastFindResultSection; // @synthesize lastFindResultSection=_lastFindResultSection;
- (void)loadView;
@property(retain) IDEBuildResultsOutlineLogic *outlineLogic; // @synthesize outlineLogic=_outlineLogic;
- (void)primitiveInvalidate;
- (void)processNewSelectedIndexPaths:(id)arg1;
@property(retain) NSPopUpButton *scopeBarMessagesPopup; // @synthesize scopeBarMessagesPopup=_scopeBarMessagesPopup;
- (void)selectMessageOrSection:(id)arg1;
- (void)selectSection:(id)arg1 withTranscriptTextRange:(struct _NSRange)arg2;
- (void)setLogEditorScopeState:(int)arg1;
@property(nonatomic) BOOL showAllResults; // @synthesize showAllResults=_showAllResults;
@property BOOL showBySteps; // @synthesize showBySteps=_showBySteps;
- (void)showAllMessages:(id)arg1;
- (void)updateOutlineControllerWithSearchString:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

