/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEEditorDocument.h>

#import "DVTTextFindable.h"

@class IDEActivityLogSection, IDESchemeActionRunDestinationRecord, NSArray, NSString;

@interface IDELogDocument : IDEEditorDocument <DVTTextFindable>
{
    IDEActivityLogSection *_activityLog;
    NSArray *_testableSummaries;
    IDESchemeActionRunDestinationRecord *_runDestinationRecord;
}

+ (BOOL)shouldUnlockFileURLBeforeMakingChanges;
- (void).cxx_destruct;
- (id)_iterateStartingWith:(id)arg1 section:(id)arg2 index:(unsigned long long)arg3 backwards:(BOOL)arg4 level:(long long)arg5 messageCount:(unsigned long long)arg6 onRefPath:(BOOL)arg7 passingTest:(id)arg8;
@property(readonly) IDEActivityLogSection *buildLog; // @synthesize buildLog=_activityLog;
- (id)displayName;
- (id)findLocationFollowing:(id)arg1 backwards:(BOOL)arg2 passingTestForSection:(id)arg3;
- (id)findStringMatchingDescriptor:(id)arg1 backwards:(BOOL)arg2 from:(id)arg3 to:(id)arg4;
- (id)initForURL:(id)arg1 withContentsOfURL:(id)arg2 ofType:(id)arg3 error:(id *)arg4;
- (id)lastIndexPathInSection:(id)arg1 inIndexPath:(id)arg2;
- (id)lastLocationInLog;
- (id)messageOrSectionForDocumentLocation:(id)arg1;
- (void)printDocument:(id)arg1;
- (int)readOnlyStatus;
- (void)refreshTestableSummaries;
@property(readonly) IDESchemeActionRunDestinationRecord *runDestinationRecord; // @synthesize runDestinationRecord=_runDestinationRecord;
- (struct _NSRange)searchRangeforStartRange:(struct _NSRange)arg1 backwards:(BOOL)arg2 withinString:(id)arg3;
- (id)searchStringForLocation:(id)arg1;
@property(readonly) NSArray *testableSummaries; // @synthesize testableSummaries=_testableSummaries;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property unsigned long long supportedMatchingOptions;

@end

