/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

@class DVTObservingToken, DVTPreferenceSetManager, DVTReplacementView, NSMenuItem, NSPanel, NSPopUpButton;

@interface IDEPreferenceSetPopUpViewController : IDEViewController
{
    DVTPreferenceSetManager *_prefSetManager;
    DVTObservingToken *_availablePrefSetsObserverToken;
    DVTObservingToken *_currentPrefSetObserverToken;
    NSPopUpButton *_prefSetsPopUpButton;
    NSMenuItem *_managePrefSetsMenuItem;
    NSPanel *_managePrefSetsPanel;
    DVTReplacementView *_prefSetReplacementView;
    id <DVTPreferenceSet> _selectedPreferenceSet;
}

- (void).cxx_destruct;
- (void)_beginObservingPreferenceSetManager;
- (void)_dismissManagePreferenceSetsSheetAction:(id)arg1;
- (void)_endObservingPreferenceSetManager;
- (void)_selectPreferenceSetAction:(id)arg1;
- (void)_selectPreferenceSetFromPreferenceSetManager;
- (void)_updatePrefSetsPopUpButton;
- (void)managePreferenceSets:(id)arg1;
@property(retain) DVTPreferenceSetManager *preferenceSetManager;
@property(readonly) NSPopUpButton *preferenceSetPopUpButton; // @synthesize preferenceSetPopUpButton=_prefSetsPopUpButton;
- (void)primitiveInvalidate;
@property(readonly) id <DVTPreferenceSet> selectedPreferenceSet; // @synthesize selectedPreferenceSet=_selectedPreferenceSet;

@end

