/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEProgramStatusCellView.h>

@interface IDEProgramStatusForMacOSXCellView : IDEProgramStatusCellView
{
}

+ (BOOL)isForIOS;
- (id)URLForJoin;
- (BOOL)hasMembership;

@end

