/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSPopUpButtonCell.h"

@class NSString;

@interface IDEProcessActionPopUpCell : NSPopUpButtonCell
{
    struct CGSize _cellSize;
    BOOL _mouseEntered;
    NSString *_toolTip;
}

- (void).cxx_destruct;
- (void)_updatePopUpButtonImageForSelectedMenuItem;
- (id)accessibilityAttributeValue:(id)arg1;
- (void)addTrackingAreasForView:(id)arg1 inFrame:(struct CGRect)arg2 withUserInfo:(id)arg3 mouseLocation:(struct CGPoint)arg4;
- (struct CGSize)cellSize;
- (void)drawInteriorWithFrame:(struct CGRect)arg1 inView:(id)arg2;
- (id)initWithHeight:(double)arg1;
- (BOOL)isHighlighted;
- (void)mouseEntered:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)selectItemAtIndex:(long long)arg1;
- (void)setMenu:(id)arg1;
@property(copy) NSString *toolTip; // @synthesize toolTip=_toolTip;

@end

