/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "DVTFindPatternSearchField.h"

#import "DVTInvalidation.h"

@class DVTStackBacktrace, IDEProgressSearchSuggestionItem, NSArray, NSString, NSTableColumn, NSTableView, NSWindow, _IDEProgressSearchFieldCell;

@interface IDEProgressSearchField : DVTFindPatternSearchField <DVTInvalidation>
{
    NSString *_sanatizedSuggestionString;
    NSTableView *_suggestionTableView;
    NSTableColumn *_suggestionTitleColumn;
    NSWindow *_suggestionWindow;
    NSArray *_suggestionItems;
    NSArray *_allVisibleSuggestions;
    IDEProgressSearchSuggestionItem *_selectedSuggestionItem;
    id <IDEProgressSearchFieldCommandDelegate> _commandDelegate;
    id <IDEProgressSearchFieldDelegate> _searchFieldDelegate;
}

+ (Class)cellClass;
+ (void)initialize;
- (void).cxx_destruct;
- (void)_controlTextDidChange:(id)arg1;
- (void)_generateMenuWindow;
- (void)_refreshTable;
- (void)_selectionMade:(id)arg1;
- (void)_updateMenu;
@property(readonly) NSArray *allVisibleSuggestions;
@property(readonly) _IDEProgressSearchFieldCell *cell;
@property(retain) id <IDEProgressSearchFieldCommandDelegate> commandDelegate; // @synthesize commandDelegate=_commandDelegate;
- (void)controlTextDidChange:(id)arg1;
- (void)controlTextDidEndEditing:(id)arg1;
- (void)hideSuggestions;
- (void)ide_progressSearchField_setup;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)primitiveInvalidate;
@property(retain) id <IDEProgressSearchFieldDelegate> searchFieldDelegate; // @synthesize searchFieldDelegate=_searchFieldDelegate;
@property(retain) IDEProgressSearchSuggestionItem *selectedSuggestionItem;
@property(copy, nonatomic) NSArray *suggestionItems; // @synthesize suggestionItems=_suggestionItems;
- (void)showSuggestions;
@property(readonly) BOOL suggestionsVisible;
- (id)tableView:(id)arg1 dataCellForTableColumn:(id)arg2 row:(long long)arg3;
- (id)tableView:(id)arg1 objectValueForTableColumn:(id)arg2 row:(long long)arg3;
- (BOOL)tableView:(id)arg1 shouldSelectRow:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 row:(long long)arg4;
- (BOOL)textView:(id)arg1 doCommandBySelector:(SEL)arg2;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

