/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEPeoplePickerContentViewController.h>

@class ABPersonView;

@interface IDEPeoplePickerEditPersonViewController : IDEPeoplePickerContentViewController
{
    ABPersonView *_cardView;
}

+ (id)defaultViewNibName;
- (void).cxx_destruct;
- (void)disableEditing;
- (void)teardown;
- (void)viewDidInstall;

@end

