/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

@class IDEPOEmptyView;

@interface IDEPOEmptyViewController : IDEViewController
{
    IDEPOEmptyView *_emptyView;
}

- (void).cxx_destruct;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)setBackgroundColor:(id)arg1;
- (void)setEmptyString:(id)arg1;

@end

