/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSTableCellView.h"

@class IDEAccountPrefsDeveloperAccountDetailViewController, NSButton;

@interface IDEProgramStatusCellView : NSTableCellView
{
    IDEAccountPrefsDeveloperAccountDetailViewController *_detailViewController;
    NSButton *_joinButton;
}

+ (BOOL)isForIOS;
- (void).cxx_destruct;
- (id)URLForJoin;
- (void)dealloc;
@property(nonatomic) __weak IDEAccountPrefsDeveloperAccountDetailViewController *detailViewController; // @synthesize detailViewController=_detailViewController;
- (BOOL)hasMembership;
- (id)isMemberImage;
- (void)join:(id)arg1;
@property(retain, nonatomic) NSButton *joinButton; // @synthesize joinButton=_joinButton;
- (void)rollOverChangedNote:(id)arg1;
- (void)setObjectValue:(id)arg1;
- (BOOL)shouldShowJoinButton;
- (id)teamDescription;
- (void)updateUI;

@end

