/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

#import "IDEEditorContextDelegate.h"
#import "IDESourceControlMergeControllerContainer.h"

@class DVTBorderedView, DVTObservingToken, DVTSplitView, IDEComparisonEditor, IDEEditorVersionsMode, IDEReviewFilesNavigator, IDESourceControlConflictResolutionController, IDESourceControlInteractiveCommitController, NSString;

@interface IDEReviewFilesViewController : IDEViewController <IDEEditorContextDelegate, IDESourceControlMergeControllerContainer>
{
    DVTSplitView *_splitView;
    DVTBorderedView *_structureBorderedView;
    DVTBorderedView *_comparisonBorderedView;
    IDEReviewFilesNavigator *_navigator;
    IDEEditorVersionsMode *_versionsMode;
    DVTObservingToken *_navigatorSelectedViewIndexesObservingToken;
    DVTObservingToken *_navigatorSelectedObjectsObservingToken;
    id <IDEReviewFilesViewControllerDelegate> _delegate;
    IDESourceControlConflictResolutionController *_conflictResolutionController;
    IDESourceControlInteractiveCommitController *_interactiveCommitController;
}

+ (id)keyPathsForValuesAffectingComparisonEditor;
+ (id)keyPathsForValuesAffectingVersionsEditor;
+ (struct CGRect)minimumSheetFrame;
+ (id)reviewFilesLogAspect;
+ (struct CGSize)sheetSizeForHostWindow:(id)arg1;
- (void).cxx_destruct;
@property(readonly) IDEComparisonEditor *comparisonEditor;
@property(readonly) IDESourceControlConflictResolutionController *conflictResolutionController; // @dynamic conflictResolutionController;
@property(retain) id <IDEReviewFilesViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (id)editorContext:(id)arg1 shouldEditNavigableItem:(id)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
@property(readonly) IDESourceControlInteractiveCommitController *interactiveCommitController; // @dynamic interactiveCommitController;
- (void)loadView;
@property(readonly) IDEReviewFilesNavigator *navigator; // @synthesize navigator=_navigator;
- (void)primitiveInvalidate;
- (void)setupConflictResolutionController;
- (void)setupInteractiveCommitController;
- (BOOL)splitView:(id)arg1 canCollapseSubview:(id)arg2;
- (double)splitView:(id)arg1 constrainMaxCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainMinCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (BOOL)splitView:(id)arg1 shouldAdjustSizeOfSubview:(id)arg2;
@property(readonly) IDEEditorVersionsMode *versionsEditor;
@property(readonly) IDEEditorVersionsMode *versionsMode; // @synthesize versionsMode=_versionsMode;
- (void)viewDidInstall;
- (id)workspaceForEditorContext:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

