/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "DVTTableView.h"

@interface IDERollOverTableView : DVTTableView
{
    BOOL _rolledOver;
}

- (void)drawRect:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
@property(nonatomic, getter=isRolledOver) BOOL rolledOver; // @synthesize rolledOver=_rolledOver;
- (void)mouseEntered:(id)arg1;
- (void)mouseExited:(id)arg1;

@end

