/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSView.h"

@class DVTColoredSpinner, IDERunDestination, NSImage, NSImageView, NSLayoutConstraint, NSMenuItem, NSMutableArray, NSTextField;

@interface IDERunDestinationMenuItemView : NSView
{
    NSMutableArray *_cancellationTokens;
    NSImage *_wifiImage;
    NSImage *_highlightedWifiImage;
    IDERunDestination *_runDestination;
    NSMenuItem *_menuItem;
    NSView *_indentView;
    NSLayoutConstraint *_indentConstraint;
    NSTextField *_stateView;
    NSImageView *_imageView;
    NSTextField *_titleView;
    DVTColoredSpinner *_spinnerView;
    NSImageView *_wifiView;
}

+ (void)applyToMenuItem:(id)arg1;
+ (id)keyPathsForValuesAffectingAccessory;
+ (id)keyPathsForValuesAffectingHideSpinner;
+ (id)keyPathsForValuesAffectingHideWifi;
- (void).cxx_destruct;
- (void)_addBindings;
- (void)_bind:(id)arg1 toKeyPath:(id)arg2;
- (void)_bind:(id)arg1 toKeyPath:(id)arg2 options:(id)arg3;
- (void)_observe:(id)arg1 withBlock:(id)arg2;
- (void)_removeBindings;
- (void)_selectAndClose;
- (BOOL)acceptsFirstResponder;
- (id)accessibilityActionDescription:(id)arg1;
- (id)accessibilityActionNames;
- (id)accessibilityAttributeNames;
- (id)accessibilityAttributeValue:(id)arg1;
- (BOOL)accessibilityIsIgnored;
- (void)accessibilityPerformAction:(id)arg1;
- (long long)accessory;
- (void)awakeFromNib;
- (void)drawRect:(struct CGRect)arg1;
- (BOOL)hideSpinner;
- (BOOL)hideWifi;
@property(retain, nonatomic) NSImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) NSLayoutConstraint *indentConstraint; // @synthesize indentConstraint=_indentConstraint;
@property(retain, nonatomic) NSView *indentView; // @synthesize indentView=_indentView;
- (void)keyDown:(id)arg1;
- (void)layout;
@property(retain, nonatomic) NSMenuItem *menuItem; // @synthesize menuItem=_menuItem;
- (void)mouseUp:(id)arg1;
@property(retain, nonatomic) IDERunDestination *runDestination; // @synthesize runDestination=_runDestination;
@property(retain, nonatomic) DVTColoredSpinner *spinnerView; // @synthesize spinnerView=_spinnerView;
@property(retain, nonatomic) NSTextField *stateView; // @synthesize stateView=_stateView;
@property(retain, nonatomic) NSTextField *titleView; // @synthesize titleView=_titleView;
@property(retain, nonatomic) NSImageView *wifiView; // @synthesize wifiView=_wifiView;
- (void)viewDidMoveToWindow;

@end

