/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "IDEKeyDrivenNavigableItemRepresentedObject.h"
#import "IDERunDestinationRepresentedObject.h"

@class DVTDocumentLocation, DVTFileDataType, IDEFileReference, IDERunDestination, NSImage, NSString;

@interface IDERunDestinationWithName : NSObject <IDEKeyDrivenNavigableItemRepresentedObject, IDERunDestinationRepresentedObject>
{
    IDERunDestination *_runDestination;
    NSString *_name;
}

+ (id)keyPathsForValuesAffectingNavigableItem_image;
+ (id)keyPathsForValuesAffectingNavigableItem_toolTip;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (id)initWithRunDestination:(id)arg1 name:(id)arg2;
@property(readonly) NSString *name; // @synthesize name=_name;
@property(readonly) NSImage *navigableItem_image;
@property(readonly) NSString *navigableItem_name;
@property(readonly) NSString *navigableItem_toolTip;
@property(readonly) IDERunDestination *runDestination; // @synthesize runDestination=_runDestination;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) DVTDocumentLocation *navigableItem_contentDocumentLocation;
@property(readonly) DVTFileDataType *navigableItem_documentType;
@property(readonly) IDEFileReference *navigableItem_fileReference;
@property(readonly) NSString *navigableItem_groupIdentifier;
@property(readonly) BOOL navigableItem_isLeaf;
@property(readonly) BOOL navigableItem_isMajorGroup;
@property(readonly) Class superclass;

@end

