/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "DVTViewController.h"

#import "DVTDynamicTableViewDataSource.h"
#import "DVTDynamicTableViewDelegate.h"

@class DVTBorderedView, DVTDynamicTableView, DVTGradientImageButton, DVTScrollView, DVTSearchField, IDEControlGroup, IDESourceControlBranch, IDESourceControlMultipleStepInvalidationToken, IDESourceControlWorkingTree, NSArray, NSDictionary, NSString;

@interface IDESourceControlBranchTableViewController : DVTViewController <DVTDynamicTableViewDelegate, DVTDynamicTableViewDataSource>
{
    DVTBorderedView *_borderedView;
    DVTBorderedView *_glassBarBorderedView;
    DVTGradientImageButton *_addButton;
    DVTGradientImageButton *_removeButton;
    IDEControlGroup *_controlGroup;
    DVTSearchField *_filterField;
    DVTScrollView *_scrollView;
    NSArray *_items;
    NSDictionary *_branchesByRepository;
    NSArray *_filteredItems;
    NSDictionary *_filteredBranchesByRepository;
    BOOL _showRemoteBranches;
    BOOL _showSpecificBranches;
    BOOL _hideBranchHistory;
    IDESourceControlWorkingTree *_workingTree;
    NSString *_filterString;
    IDESourceControlMultipleStepInvalidationToken *_branchLoadingToken;
    id <DVTInvalidation> _deleteBranchToken;
    BOOL _showCurrentBranch;
    BOOL _showLoading;
    BOOL _isLoading;
    DVTDynamicTableView *_tableView;
    IDESourceControlBranch *_selectedBranch;
    IDESourceControlBranch *_currentBranch;
    id <IDESourceControlBranchTableDelegate> _delegate;
}

+ (id)keyPathsForValuesAffectingCanRemoveBranch;
- (void).cxx_destruct;
- (id)_dateFormatter;
- (void)_startLoading;
- (void)_stopLoading;
- (void)addBranch:(id)arg1;
@property(readonly) BOOL canRemoveBranch;
- (void)clearBranches;
@property(retain) IDESourceControlBranch *currentBranch; // @synthesize currentBranch=_currentBranch;
@property __weak id <IDESourceControlBranchTableDelegate> delegate; // @synthesize delegate=_delegate;
- (double)dynamicTableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)dynamicTableView:(id)arg1 heightForRow:(long long)arg2 inSection:(long long)arg3;
- (long long)dynamicTableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)dynamicTableView:(id)arg1 toolTipForRow:(long long)arg2 inSection:(long long)arg3;
- (id)dynamicTableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)dynamicTableView:(id)arg1 viewForRow:(long long)arg2 inSection:(long long)arg3;
- (void)dynamicTableViewSelectionDidChange:(id)arg1;
@property(retain) NSString *filterString;
@property BOOL hideBranchHistory; // @synthesize hideBranchHistory=_hideBranchHistory;
@property BOOL hideFilterField;
@property BOOL isLoading; // @synthesize isLoading=_isLoading;
- (void)loadView;
- (id)nibName;
- (long long)numberOfSectionsInDynamicTableView:(id)arg1;
- (id)objectValueForRow:(long long)arg1 inSection:(long long)arg2;
- (void)primitiveInvalidate;
- (void)removeBranch:(id)arg1;
- (void)selectBranch:(id)arg1;
@property(retain) IDESourceControlBranch *selectedBranch; // @synthesize selectedBranch=_selectedBranch;
@property BOOL showAddRemoveButtons;
@property BOOL showCurrentBranch; // @synthesize showCurrentBranch=_showCurrentBranch;
@property BOOL showLoading; // @synthesize showLoading=_showLoading;
@property BOOL showRemoteBranches;
@property __weak DVTDynamicTableView *tableView; // @synthesize tableView=_tableView;
- (void)showAllBranchesForWorkingTree:(id)arg1 withCompletionBlock:(id)arg2;
- (void)showBranches:(id)arg1 forRepository:(id)arg2 withCompletionBlock:(id)arg3;
@property(readonly) IDESourceControlWorkingTree *workingTree; // @synthesize workingTree=_workingTree;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

