/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEDebugBarContentProvider.h>

@class DVTObservingToken, IDENavigableItem, IDENavigableItemCoordinator, IDEPathControl, NSArray;

@interface IDEStackFrameDebugBarContentProvider : IDEDebugBarContentProvider
{
    IDEPathControl *_pathControl;
    IDENavigableItemCoordinator *_navigableItemCoordinator;
    IDENavigableItem *_rootNavigableItem;
    IDENavigableItem *_selectedItem;
    DVTObservingToken *_currentStackFrameObserverToken;
    DVTObservingToken *_selectedNavigableItemFrameObserverToken;
    DVTObservingToken *_debugSessionStateObserverToken;
    DVTObservingToken *_launchSessionStateObserverToken;
    BOOL _handlingSetSelectedItem;
}

+ (id)assetBundle;
+ (BOOL)automaticallyNotifiesObserversOfSelectedItem;
+ (Class)debugSessionControllerClass;
+ (id)keyPathsForValuesAffectingNavigableDebugItems;
- (void).cxx_destruct;
- (void)_forgetNavigableItems:(id)arg1;
- (void)_handleDebugBarSelectedModelItemChanged;
- (void)_retrySetSelectedItem;
- (void)_selectItemBasedOnDebugSessionState;
- (void)_simpleSetSelectedItemWithKVO:(id)arg1;
- (BOOL)_userIsCurrentlyCPUDebugging;
- (struct CGRect)additionalGrabRectOfDebugBar:(id)arg1 inTermsOfView:(id)arg2;
- (void)currentDebugSessionDidChange;
- (void)currentDebugSessionStateDidChange;
- (void)currentStackFrameDidChange:(id)arg1;
- (id)domainIdentifier;
- (id)init;
@property(readonly) NSArray *navigableDebugItems; // @dynamic navigableDebugItems;
@property(readonly) IDENavigableItemCoordinator *navigableItemCoordinator; // @synthesize navigableItemCoordinator=_navigableItemCoordinator;
@property(retain) IDEPathControl *pathControl; // @synthesize pathControl=_pathControl;
- (void)removeRootNavigableItemFromCoordinator;
@property(retain, nonatomic) IDENavigableItem *rootNavigableItem; // @synthesize rootNavigableItem=_rootNavigableItem;
@property(retain, nonatomic) IDENavigableItem *selectedItem; // @synthesize selectedItem=_selectedItem;
- (void)updateBoundContent;
- (void)wasAttachedToDebugBar:(id)arg1;
- (void)willBeDetachedFromDebugBar:(id)arg1;
- (void)workspaceDidFinishLoading;
- (double)xOffsetForSharedLibrariesPopUpAnchoredOnDebugBar:(id)arg1;

@end

