/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol IDESourceControlWorkspaceUIHandlerProtocol <NSObject>
- (void)askToShareNewWorkingCopies:(id)arg1;
- (void)didFindUpgradableWorkingCopy;
- (void)offerAdditionalWorkingCopies;
- (void)warnAboutNewerRepositoryVersionWithError:(id)arg1;
- (void)workspaceMonitorDidFinishScanning:(id)arg1;
@end

