/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "DVTInvalidation.h"
#import "IDESourceControlWorkspaceUIHandlerProtocol.h"
#import "NSAlertDelegate.h"
#import "NSWindowDelegate.h"

@class DVTFilePath, DVTStackBacktrace, IDESourceControlCreateGitRepositoryOperationInfo, IDESourceControlNewCheckoutWindowController, IDESourceControlUpgradeWindowController, IDEWorkspaceDocument, IDEXcodeServer, NSAlert, NSMutableSet, NSOperationQueue, NSString;

@interface IDESourceControlWorkspaceUIHandler : NSObject <IDESourceControlWorkspaceUIHandlerProtocol, DVTInvalidation, NSAlertDelegate, NSWindowDelegate>
{
    id _sourceControlCommandContinuationBlock;
    id _upgradeContinuationBlock;
    NSAlert *_waitingOnInitialScanAlert;
    NSAlert *_checkingForUpdatesAlert;
    NSAlert *_upgradeWorkignCopyAlert;
    IDESourceControlUpgradeWindowController *_upgradeWindowController;
    BOOL _initialScanAlertIsShowing;
    BOOL _initialWorkspaceScanIsComplete;
    BOOL _shouldShowUpgradeAlert;
    IDEWorkspaceDocument *_workspaceDocument;
    IDESourceControlNewCheckoutWindowController *_checkoutWC;
    NSMutableSet *_windowControllers;
    IDESourceControlCreateGitRepositoryOperationInfo *_operationInfo;
    NSOperationQueue *_operationQueue;
    BOOL _shouldShowMissingWorkingCopies;
    BOOL _shouldCreateLocalRepository;
    DVTFilePath *_pathToCreateLocalGitRepository;
    IDEXcodeServer *_serverToPushTo;
}

+ (void)initialize;
- (void).cxx_destruct;
- (void)addWindowController:(id)arg1;
- (BOOL)alertShowHelp:(id)arg1;
- (void)askToCheckOutDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)askToShareNewWorkingCopies:(id)arg1;
- (void)createGitRepositoryForFilePath:(id)arg1 workingTree:(id)arg2 repoName:(id)arg3 pushingToServer:(id)arg4;
- (void)didFindUpgradableWorkingCopy;
- (void)displayError:(id)arg1;
- (void)displayWaitingOnInitialWorkspaceScanAlertInWindow:(id)arg1 withContinuationBlock:(id)arg2;
- (void)finishedCreateGitRepositoryWithWorkingTree:(id)arg1;
- (void)finishedUpgrade;
- (id)initWithWorkspaceDocument:(id)arg1;
- (void)initialWorkspaceScanIsFinished;
- (void)newWorkingCopyDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)offerAdditionalWorkingCopies;
@property DVTFilePath *pathToCreateLocalGitRepository; // @synthesize pathToCreateLocalGitRepository=_pathToCreateLocalGitRepository;
- (void)presentCheckoutsForProject:(id)arg1 scopingToWorkingCopyConfigurations:(id)arg2 attachedToWindow:(id)arg3;
- (void)primitiveInvalidate;
@property IDEXcodeServer *serverToPushTo; // @synthesize serverToPushTo=_serverToPushTo;
@property BOOL shouldCreateLocalRepository; // @synthesize shouldCreateLocalRepository=_shouldCreateLocalRepository;
@property(copy) id sourceControlCommandContinuationBlock; // @synthesize sourceControlCommandContinuationBlock=_sourceControlCommandContinuationBlock;
- (void)shouldCreateLocalRepository:(BOOL)arg1 atFilePath:(id)arg2 pushToServer:(id)arg3;
- (void)showUpgradeWindowForWindow:(id)arg1 workingCopiesNeedingUpgrade:(id)arg2 showsSuppressionButton:(BOOL)arg3;
- (void)upgradeAlertDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (id)waitingOnInitialScanAlert;
- (void)warnAboutNewerRepositoryVersionWithError:(id)arg1;
- (void)windowDidCloseForWindowController:(id)arg1;
- (void)windowWillClose:(id)arg1;
- (void)workspaceMonitorDidFinishScanning:(id)arg1;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

