/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSFileWrapper;

@interface IDESourceControlMergeData : NSObject
{
    NSFileWrapper *_fileWrapper;
    BOOL _dirty;
}

- (void).cxx_destruct;
@property(retain) NSFileWrapper *fileWrapper; // @synthesize fileWrapper=_fileWrapper;
@property(getter=isDirty) BOOL dirty; // @synthesize dirty=_dirty;

@end

