/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

#import "IDETestsInTestableObserver.h"
#import "NSOutlineViewDataSource.h"
#import "NSOutlineViewDelegate.h"

@class DVTBorderedView, DVTLozengeTextField, DVTObservingToken, DVTOutlineView, DVTScopeBarButton, DVTSearchField, IDESharedTestBaselineUpdateController, NSArray, NSButton, NSMapTable, NSMutableArray, NSOperationQueue, NSScrollView, NSString, NSTimer;

@interface IDESharedTestResultsViewController : IDEViewController <NSOutlineViewDelegate, NSOutlineViewDataSource, IDETestsInTestableObserver>
{
    BOOL _isReloadingFromItemDidExpandOrCollapse;
    NSOperationQueue *_testPlaceholderQueryQueue;
    IDESharedTestBaselineUpdateController *_baselineUpdatesController;
    unsigned long long _countOfTestablesToUpdate;
    unsigned long long _countOfTestManagerTestables;
    DVTObservingToken *_controllerContentViewLayoutObservingToken;
    BOOL _readyToReloadView;
    NSMutableArray *_testPlaceholderObservingTokens;
    NSTimer *_updateRowHeightTimer;
    DVTObservingToken *_accessoryViewAlertOptionsToken;
    id <IDEClientTrackingToken> _clientTrackingToken;
    BOOL _failingOnly;
    BOOL _passedOnly;
    BOOL _failedExpectedOnly;
    BOOL _perfOnly;
    id <IDESharedTests_RootObject> _rootObject;
    id _testSelectedCallback;
    DVTBorderedView *_filterBarBorderedView;
    DVTSearchField *_filterField;
    DVTLozengeTextField *_lozengeTextField;
    DVTScopeBarButton *_scopeBarAllButton;
    DVTScopeBarButton *_scopeBarPassedButton;
    DVTScopeBarButton *_scopeBarFailedButton;
    DVTScopeBarButton *_scopeBarUnitAndPerfTestsButton;
    DVTScopeBarButton *_scopeBarPerformanceTestsButton;
    NSButton *_setBaselinesButton;
    DVTOutlineView *_testsOutlineView;
    NSScrollView *_testsScrollView;
    NSArray *_filteredTests;
    NSArray *_outlineViewRootItems;
    NSArray *_filteredOutlineViewRootItems;
    NSArray *_perfTestMetricNames;
    NSArray *_testGraphRows;
    NSMapTable *_testPlaceholdersAndTests;
}

+ (void)initialize;
+ (void)replaceHeaderCellsWithModernOnes:(id)arg1 leftmostHeaderMargin:(double)arg2;
- (void).cxx_destruct;
- (void)_updateRowHeights;
- (id)allPerfTestGroups;
- (id)assertionsAttributedStringForTestFailures:(id)arg1 noBaselines:(id)arg2;
- (id)assertionsInTestRun:(id)arg1;
- (void)commitScopeBarState;
- (void)copy:(id)arg1;
@property BOOL failedExpectedOnly; // @synthesize failedExpectedOnly=_failedExpectedOnly;
@property BOOL failingOnly; // @synthesize failingOnly=_failingOnly;
@property __weak DVTBorderedView *filterBarBorderedView; // @synthesize filterBarBorderedView=_filterBarBorderedView;
@property __weak DVTSearchField *filterField; // @synthesize filterField=_filterField;
- (void)filterFieldAction:(id)arg1;
@property(copy) NSArray *filteredOutlineViewRootItems; // @synthesize filteredOutlineViewRootItems=_filteredOutlineViewRootItems;
@property(copy) NSArray *filteredTests; // @synthesize filteredTests=_filteredTests;
- (id)filteredTestsRespectingScopeFiltersInTestGroup:(id)arg1 withFilterString:(id)arg2;
- (void)frameOfDeviceCellViewForTestRun:(id)arg1 completionBlock:(id)arg2;
- (void)loadView;
@property __weak DVTLozengeTextField *lozengeTextField; // @synthesize lozengeTextField=_lozengeTextField;
- (id)noBaselineWarningsInTestRun:(id)arg1;
- (void)observePerfTestGroupTestables;
- (id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;
- (double)outlineView:(id)arg1 heightOfRowByItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 isGroupItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 isItemExpandable:(id)arg2;
- (long long)outlineView:(id)arg1 numberOfChildrenOfItem:(id)arg2;
- (id)outlineView:(id)arg1 rowViewForItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 shouldSelectItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 shouldShowOutlineCellForItem:(id)arg2;
- (id)outlineView:(id)arg1 viewForTableColumn:(id)arg2 item:(id)arg3;
- (void)outlineViewItemDidCollapse:(id)arg1;
- (void)outlineViewItemDidExpand:(id)arg1;
- (void)outlineViewItemWillExpand:(id)arg1;
@property(copy) NSArray *outlineViewRootItems; // @synthesize outlineViewRootItems=_outlineViewRootItems;
- (void)outlineViewSelectionDidChange:(id)arg1;
@property BOOL passedOnly; // @synthesize passedOnly=_passedOnly;
@property BOOL perfOnly; // @synthesize perfOnly=_perfOnly;
@property(copy) NSArray *perfTestMetricNames; // @synthesize perfTestMetricNames=_perfTestMetricNames;
- (void)primitiveInvalidate;
- (void)reloadAndExpandOutlineView;
- (void)reloadAndFilterOutline;
- (void)restoreScopeBarState;
@property(retain, nonatomic) id <IDESharedTests_RootObject> rootObject; // @synthesize rootObject=_rootObject;
- (void)scopeBarAll:(id)arg1;
@property __weak DVTScopeBarButton *scopeBarAllButton; // @synthesize scopeBarAllButton=_scopeBarAllButton;
- (void)scopeBarChanged;
- (void)scopeBarFailed:(id)arg1;
@property __weak DVTScopeBarButton *scopeBarFailedButton; // @synthesize scopeBarFailedButton=_scopeBarFailedButton;
- (void)scopeBarPassed:(id)arg1;
@property __weak DVTScopeBarButton *scopeBarPassedButton; // @synthesize scopeBarPassedButton=_scopeBarPassedButton;
- (void)scopeBarPerformance:(id)arg1;
@property __weak DVTScopeBarButton *scopeBarPerformanceTestsButton; // @synthesize scopeBarPerformanceTestsButton=_scopeBarPerformanceTestsButton;
- (void)scopeBarUnitAndPerfTests:(id)arg1;
@property __weak DVTScopeBarButton *scopeBarUnitAndPerfTestsButton; // @synthesize scopeBarUnitAndPerfTestsButton=_scopeBarUnitAndPerfTestsButton;
- (void)scrollViewBoundsDidChange:(id)arg1;
- (void)setBaselinesAction:(id)arg1;
@property __weak NSButton *setBaselinesButton; // @synthesize setBaselinesButton=_setBaselinesButton;
@property(copy) NSArray *testGraphRows; // @synthesize testGraphRows=_testGraphRows;
@property(retain) NSMapTable *testPlaceholdersAndTests; // @synthesize testPlaceholdersAndTests=_testPlaceholdersAndTests;
@property(copy, nonatomic) id testSelectedCallback; // @synthesize testSelectedCallback=_testSelectedCallback;
@property __weak DVTOutlineView *testsOutlineView; // @synthesize testsOutlineView=_testsOutlineView;
@property __weak NSScrollView *testsScrollView; // @synthesize testsScrollView=_testsScrollView;
- (void)showTestForClassName:(id)arg1 methodName:(id)arg2;
- (id)testClassesWithScopeBarFiltering;
- (void)testablesChanged:(id)arg1;
- (void)testsChanged:(id)arg1;
- (void)updateBaselineForPerfMetric:(id)arg1 inTestRun:(id)arg2 newBaseline:(double)arg3 newAllowedSTD:(id)arg4;
- (void)workspaceReferencedTestablesChanged;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

