/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSWindowController.h"

@class IDESourceControlRepository, NSSecureTextField, NSTextField;

@interface IDESourceControlCheckoutAuthenticationWindowController : NSWindowController
{
    NSTextField *_repositoryURLField;
    NSTextField *_usernameField;
    NSSecureTextField *_passwordField;
    IDESourceControlRepository *_repository;
    id _completionHandler;
}

- (void).cxx_destruct;
- (void)authenticate:(id)arg1;
- (void)authenticationSheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (void)beginSheetForWindow:(id)arg1 completionHandler:(id)arg2;
- (void)cancel:(id)arg1;
@property(copy) id completionHandler; // @synthesize completionHandler=_completionHandler;
@property(retain) IDESourceControlRepository *repository; // @synthesize repository=_repository;
- (id)windowNibName;

@end

