/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSTableRowView.h"

@class NSTrackingArea;

@interface IDESharedTestResultsTestTableRowView : NSTableRowView
{
    BOOL _mouseInside;
    NSTrackingArea *_trackingArea;
    BOOL _isLastChildOfGroupRow;
    BOOL _drawTopLine;
    id _item;
    long long _row;
}

- (void).cxx_destruct;
- (void)drawBackgroundInRect:(struct CGRect)arg1;
@property BOOL drawTopLine; // @synthesize drawTopLine=_drawTopLine;
- (void)ensureTrackingArea;
@property BOOL isLastChildOfGroupRow; // @synthesize isLastChildOfGroupRow=_isLastChildOfGroupRow;
@property(retain) id item; // @synthesize item=_item;
- (void)mouseEntered:(id)arg1;
- (void)mouseExited:(id)arg1;
- (BOOL)mouseInside;
@property long long row; // @synthesize row=_row;
- (void)setMouseInside:(BOOL)arg1;
- (void)updateTrackingAreas;

@end

