/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDESourceControlOperationInfo.h>

#import "IDESourceControlBranchingOperationInfoProtocol.h"

@class IDESourceControlBranch, NSString;

@interface IDESourceControlSwitchOperationInfo : IDESourceControlOperationInfo <IDESourceControlBranchingOperationInfoProtocol>
{
    IDESourceControlBranch *_newBranch;
    IDESourceControlBranch *_startingBranch;
}

- (void).cxx_destruct;
@property(retain) IDESourceControlBranch *mainBranch; // @synthesize mainBranch=_startingBranch;
@property(retain) IDESourceControlBranch *otherBranch; // @synthesize otherBranch=_newBranch;
- (id)processInfoWithProgressBlock:(id)arg1 isSingleOperation:(void)arg2 completionBlock:(BOOL)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

