/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "IDEScheme.h"

@interface IDEScheme (IDESchemeImageAdditions)
- (id)_errorIcon;
- (id)_iconForSchemeBasedOnRunnable;
- (id)_iconForSchemeBasedOnTargets;
- (id)iconImage;
@end

