/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDESymbolNavigatorContainerSymbol.h>

@interface IDESymbolNavigatorProtocolSymbol : IDESymbolNavigatorContainerSymbol
{
}

- (id)ideModelObjectTypeIdentifier;
- (id)initWithProtocolSymbol:(id)arg1 operationQueue:(id)arg2 generation:(unsigned long long)arg3 symbolNavigator:(id)arg4;
- (id)loadChildren;

@end

