/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

@class NSPopUpButton;

@interface IDESourceControlPrefsPaneController : IDEViewController
{
    NSPopUpButton *_comparisonLocalRevisionSidePopupButton;
}

- (void).cxx_destruct;
@property BOOL alwaysAddFiles;
@property BOOL enableSourceControl;
- (id)nibName;
- (void)setComparisonLocalRevisionSide:(id)arg1;
@property BOOL showLocalStatus;
@property BOOL showRemoteStatus;
- (void)viewDidInstall;

@end

