/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class NSString;

@protocol IDESharedTests_FailureSummary <NSObject>
@property(readonly, copy, nonatomic) NSString *ide_sharedTests_fileName;
@property(readonly, nonatomic) long long ide_sharedTests_lineNumber;
@property(readonly, copy, nonatomic) NSString *ide_sharedTests_message;
@end

