/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSWindowController.h"

#import "DVTInvalidation.h"
#import "DVTReplacementViewDelegate.h"
#import "NSWindowDelegate.h"

@class DVTBindingToken, DVTBorderedView, DVTObservingToken, DVTReplacementView, DVTSplitView, DVTStackBacktrace, IDESourceControlWorkingTree, IDESourceControlWorkspaceConfigNavigator, IDEWorkspace, NSArray, NSButton, NSSearchField, NSString, NSTabView, NSTextField, NSTimer, NSView;

@interface IDESourceControlWorkspaceHistoryWindowController : NSWindowController <DVTInvalidation, DVTReplacementViewDelegate, NSWindowDelegate>
{
    IDEWorkspace *_workspace;
    NSTextField *_titleField;
    DVTReplacementView *_logReplacementView;
    NSView *_sourceListView;
    IDESourceControlWorkspaceConfigNavigator *_navigator;
    NSTabView *_tabView;
    DVTBorderedView *_detailBorderedView;
    NSButton *_doneButton;
    NSSearchField *_searchField;
    DVTSplitView *_splitView;
    BOOL _hidesSourceList;
    DVTBindingToken *_logSourceTreeItemsBindingToken;
    id _didScanToken;
    NSTimer *_searchTimer;
    DVTObservingToken *_outlineViewSelectionToken;
    int _searchType;
    BOOL _isScanningForWorkingCopies;
    NSArray *_workingTrees;
    NSArray *_selectedWorkingTrees;
    IDESourceControlWorkingTree *_selectedWorkingTree;
    NSString *_startingSearchRevision;
    NSString *_endingSearchRevision;
}

+ (void)initialize;
- (void).cxx_destruct;
- (void)_loadWorkingTrees;
- (void)_scheduleSearchWithString:(id)arg1;
- (void)_updateSearchForRevision;
- (void)_updateToolbarSearchResultsWithSearchString:(id)arg1;
- (void)_waitForWorkspaceScan;
- (void)beginSheetForWindow:(id)arg1;
- (void)controlTextDidChange:(id)arg1;
- (void)done:(id)arg1;
@property(copy) NSString *endingSearchRevision; // @synthesize endingSearchRevision=_endingSearchRevision;
- (id)initWithWindow:(id)arg1;
@property BOOL isScanningForWorkingCopies; // @synthesize isScanningForWorkingCopies=_isScanningForWorkingCopies;
- (void)loadWindow;
- (id)logViewController;
- (void)primitiveInvalidate;
@property int searchType;
- (void)selectSearchType:(id)arg1;
@property(retain) IDESourceControlWorkingTree *selectedWorkingTree; // @synthesize selectedWorkingTree=_selectedWorkingTree;
@property(retain) NSArray *selectedWorkingTrees; // @synthesize selectedWorkingTrees=_selectedWorkingTrees;
@property(copy) NSString *startingSearchRevision; // @synthesize startingSearchRevision=_startingSearchRevision;
@property(retain) NSArray *workingTrees; // @synthesize workingTrees=_workingTrees;
@property(retain) IDEWorkspace *workspace; // @synthesize workspace=_workspace;
- (void)sheetDidEnd:(id)arg1 returnCode:(long long)arg2 contextInfo:(void *)arg3;
- (BOOL)splitView:(id)arg1 canCollapseSubview:(id)arg2;
- (double)splitView:(id)arg1 constrainMaxCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (double)splitView:(id)arg1 constrainMinCoordinate:(double)arg2 ofSubviewAt:(long long)arg3;
- (BOOL)splitView:(id)arg1 shouldHideDividerAtIndex:(long long)arg2;
- (void)updateSearchMenuState;
- (void)updateSearchPlaceholderString;
- (id)windowNibName;

// Remaining properties
@property(retain) DVTStackBacktrace *creationBacktrace;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) DVTStackBacktrace *invalidationBacktrace;
@property(readonly) Class superclass;
@property(readonly, nonatomic, getter=isValid) BOOL valid;

@end

