/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSViewController.h"

#import "IDESourceControlLogFilesChangedViewDelegate.h"

@class IDESourceControlLogFilesChangedView, IDESourceControlLogItem, IDESourceControlRepository, IDESourceControlTreeItem, NSArray, NSBox, NSButton, NSImageView, NSPopover, NSProgressIndicator, NSScrollView, NSString, NSTextField, NSTextView;

@interface IDESourceControlLogDetailViewController : NSViewController <IDESourceControlLogFilesChangedViewDelegate>
{
    NSImageView *_imageView;
    NSTextField *_nameField;
    NSTextField *_commitDateField;
    NSTextField *_revisionField;
    IDESourceControlLogFilesChangedView *_filesChangedButton;
    NSTextView *_descriptionTextView;
    NSScrollView *_descriptionScrollView;
    NSProgressIndicator *_progressIndicator;
    NSButton *_showComparisonButton;
    NSButton *_showBlameButton;
    NSBox *_topBorder;
    NSBox *_bottomBorder;
    NSPopover *_popover;
    IDESourceControlLogItem *_logItem;
    NSString *_filePath;
    IDESourceControlRepository *_filesChangedRepository;
    NSArray *_itemsWithStatus;
    id <IDESourceControlLogDetailDelegate> _delegate;
    IDESourceControlTreeItem *_currentFile;
}

+ (id)logDetailAspect;
- (void).cxx_destruct;
- (void)_displayLogInfo;
- (void)_loadChangedFiles;
- (void)_loadLogMessage;
- (void)_loadingFailed;
- (double)_maxPopoverHeight;
- (void)cleanup;
- (id)displayDate;
- (id)initWithFilePath:(id)arg1 delegate:(id)arg2 popover:(id)arg3;
- (id)initWithLogItem:(id)arg1 filePath:(id)arg2 delegate:(id)arg3 popover:(id)arg4;
- (void)loadView;
@property(retain) IDESourceControlLogItem *logItem;
- (void)showBlame:(id)arg1;
- (void)showComparison:(id)arg1;
- (void)viewChanges:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

