/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class IDESourceControlPerson, IDESourceControlRepository, IDESourceControlTree, NSArray, NSDate, NSDictionary, NSString;

@interface IDESourceControlLogItem : NSObject
{
    IDESourceControlPerson *_author;
    NSString *_revision;
    NSDate *_date;
    NSString *_message;
    NSDictionary *_filesWithStatus;
    IDESourceControlTree *_sourceTree;
    IDESourceControlRepository *_filesChangedRepository;
    NSArray *_itemsWithStatus;
    BOOL _isChangedFilesExpanded;
}

- (void).cxx_destruct;
@property(readonly) IDESourceControlPerson *author; // @synthesize author=_author;
- (long long)compareToLogItem:(id)arg1;
@property(readonly) NSDate *date; // @synthesize date=_date;
- (void)dealloc;
@property(readonly) IDESourceControlRepository *filesChangedRepository; // @synthesize filesChangedRepository=_filesChangedRepository;
@property(retain) NSDictionary *filesWithStatus; // @synthesize filesWithStatus=_filesWithStatus;
- (id)initWithAuthor:(id)arg1 revision:(id)arg2 date:(id)arg3 message:(id)arg4 filesWithStatus:(id)arg5 sourceTree:(id)arg6;
@property BOOL isChangedFilesExpanded; // @synthesize isChangedFilesExpanded=_isChangedFilesExpanded;
- (BOOL)isEqual:(id)arg1;
@property(readonly) NSArray *itemsWithStatus; // @synthesize itemsWithStatus=_itemsWithStatus;
- (void)loadFilesChanged;
@property(retain) NSString *message; // @synthesize message=_message;
@property(readonly) NSString *revision; // @synthesize revision=_revision;
@property(readonly) IDESourceControlTree *sourceTree; // @synthesize sourceTree=_sourceTree;

@end

