/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@class IDESchemeActionRunDestinationRecord, IDESchemeActionsInvocationRecord, NSArray, NSImage, NSString;

@protocol IDESharedTests_TestRun <NSObject>
@property(readonly, copy, nonatomic) NSString *ide_sharedTests_UUID;
@property(readonly, copy, nonatomic) NSArray *ide_sharedTests_failureSummaries;
@property(readonly, nonatomic) BOOL ide_sharedTests_passed;
@property(readonly, copy, nonatomic) NSArray *ide_sharedTests_perfMetrics;
@property(readonly, nonatomic) NSImage *ide_sharedTests_statusImage;
@property(readonly, copy, nonatomic) NSString *ide_sharedTests_testClassName;
@property(readonly, copy, nonatomic) NSString *ide_sharedTests_testName;
@property(readonly, nonatomic) id <IDESharedTests_Device> ide_sharedTests_testedDevice;

@optional
@property(readonly, nonatomic) BOOL ide_sharedTests_fetchesSchemeActionsInvocationRecordAsync;
@property(readonly, nonatomic) IDESchemeActionRunDestinationRecord *ide_sharedTests_schemeActionRunDestinationRecord;
@property(readonly, nonatomic) IDESchemeActionsInvocationRecord *ide_sharedTests_schemeActionsInvocationRecord;
- (void)ide_sharedTests_schemeActionsInvocationRecord:(id)arg1;
@end

