/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "DVTMessageBubbleAnnotation.h"

@class NSPopover;

@interface IDETestIssueErrorAnnotation : DVTMessageBubbleAnnotation
{
    NSPopover *_iterationPopover;
}

+ (id)editedTheme;
+ (id)focusedTheme;
+ (id)normalTheme;
+ (double)precedence;
+ (unsigned long long)scrollbarMarkerType;
+ (unsigned long long)severity;
+ (id)sidebarIcon;
- (void).cxx_destruct;
- (void)_didClickInView:(id)arg1 event:(id)arg2;
- (id)annotationDisplayDescription;
- (id)annotationDisplayName;
- (id)annotationMenuForPerformanceMetricsFromPreviousRun:(id)arg1;
- (id)baselineRecordAndFilePath:(id *)arg1 error:(id *)arg2;
- (void)contextMenu_acceptPreviousAverageForAllMetrics:(id)arg1;
- (void)contextMenu_acceptPreviousAverageForPersistentAllocations:(id)arg1;
- (void)contextMenu_acceptPreviousAverageForTime:(id)arg1;
- (void)contextMenu_acceptPreviousAverageForTotalAllocations:(id)arg1;
- (void)contextMenu_performSelector:(SEL)arg1 sender:(id)arg2;
- (void)contextMenu_revealInReport:(id)arg1;
- (void)didClickInTextSidebarView:(id)arg1 event:(id)arg2;
- (void)didClickMessageBubbleOnIcon:(BOOL)arg1 inTextView:(id)arg2 event:(id)arg3;
- (id)init;
- (id)performanceMetrics;
- (void)setMessageBubbleText:(id)arg1;
- (id)test;
- (void)updateBaselineForPerformanceMetricWithIdentifier:(id)arg1 average:(id)arg2 maxStandardDeviation:(id)arg3;
- (BOOL)validateMenuItem:(id)arg1;

@end

