/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "DVTTileView.h"

@interface IDETemplateChooserTileView : DVTTileView
{
    BOOL _dontSendSelectionIndexesChanges;
}

+ (id)keyPathsForValuesAffectingBindableSelectionIndexes;
- (id)bindableSelectionIndexes;
@property(retain) id <IDETemplateChooserTileViewDelegate> delegate;
- (void)insertNewline:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)setBindableSelectionIndexes:(id)arg1;
- (void)setSelectionIndexes:(id)arg1;

@end

