/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "IDEKeyDrivenNavigableItemRepresentedObject.h"
#import "IDETestsInTestableObserver.h"

@class DVTDocumentLocation, DVTFileDataType, DVTObservingToken, IDEFileReference, IDEWorkspace, NSArray, NSImage, NSMutableArray, NSString;

@interface IDETestNavigatorModel : NSObject <IDETestsInTestableObserver, IDEKeyDrivenNavigableItemRepresentedObject>
{
    id _viewUpdater;
    DVTObservingToken *_testableOriginObservingToken;
    DVTObservingToken *_activeRunContextObservingToken;
    DVTObservingToken *_loadingCompleteObservingToken;
    NSMutableArray *_orderedTestables;
    BOOL _inited;
    BOOL _filteringByScheme;
    BOOL _loadingComplete;
    IDEWorkspace *_workspace;
}

+ (void)initialize;
+ (id)keyPathsForValuesAffectingModelItems;
- (void).cxx_destruct;
- (void)_setupLoadingCompleteObservation;
- (void)_startMonitoringTests:(id)arg1;
- (void)_stopMonitoringTests;
- (void)_tearDownObservations;
- (void)_updateObservedTestables;
@property(nonatomic) BOOL filteringByScheme; // @synthesize filteringByScheme=_filteringByScheme;
- (id)ideModelObjectTypeIdentifier;
- (id)initWithWorkspace:(id)arg1;
@property(nonatomic) BOOL loadingComplete; // @synthesize loadingComplete=_loadingComplete;
- (id)modelItems;
@property(readonly) NSString *navigableItem_name;
- (void)testablesChanged:(id)arg1;
- (void)testsChanged:(id)arg1;
@property(readonly) IDEWorkspace *workspace; // @synthesize workspace=_workspace;
- (void)workspaceReferencedTestablesChanged;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly, copy) NSMutableArray *mutableOrderedTestables; // @dynamic mutableOrderedTestables;
@property(readonly) DVTDocumentLocation *navigableItem_contentDocumentLocation;
@property(readonly) DVTFileDataType *navigableItem_documentType;
@property(readonly) IDEFileReference *navigableItem_fileReference;
@property(readonly) NSString *navigableItem_groupIdentifier;
@property(readonly) NSImage *navigableItem_image;
@property(readonly) BOOL navigableItem_isLeaf;
@property(readonly) BOOL navigableItem_isMajorGroup;
@property(readonly) NSString *navigableItem_toolTip;
@property(copy) NSArray *orderedTestables; // @dynamic orderedTestables;
@property(readonly) Class superclass;

@end

