/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDETemplateInstantiationAssistant.h>

#import "IDECompletionDestinationDelegate.h"
#import "NSOpenSavePanelDelegate.h"

@class IDECompletionDestinationManager, IDEGroup, IDEWorkspace, NSPopUpButton, NSSavePanel, NSString, NSURL;

@interface IDETemplateCompletionAssistant : IDETemplateInstantiationAssistant <NSOpenSavePanelDelegate, IDECompletionDestinationDelegate>
{
    BOOL _canInstantiateTemplate;
    id _completionBlock;
    IDEGroup *_initialDestinationGroup;
    IDEWorkspace *_initialDestinationWorkspace;
    IDECompletionDestinationManager *_destinationManager;
    BOOL _shouldReplaceExisting;
    NSSavePanel *_activeSavePanel;
    NSPopUpButton *_destinationGroupPopUp;
    NSPopUpButton *_destinationWorkspacePopUp;
}

- (void).cxx_destruct;
- (void)_didInstantiateItems:(id)arg1;
- (void)_validateCanFinish;
- (void)attemptRecoveryFromError:(id)arg1 optionIndex:(unsigned long long)arg2 delegate:(id)arg3 didRecoverSelector:(SEL)arg4 contextInfo:(void *)arg5;
- (void)beginSheetModalForWindow:(id)arg1;
- (BOOL)canFinish;
- (BOOL)canGoBack;
- (id)configuredOpenPanel;
- (id)configuredSavePanel;
@property(retain) NSPopUpButton *destinationGroupPopUp; // @synthesize destinationGroupPopUp=_destinationGroupPopUp;
- (BOOL)destinationManager:(id)arg1 shouldAddItemToMenu:(id)arg2;
- (void)destinationManagerGroupDidChange:(id)arg1;
- (void)destinationManagerWorkspaceDidChange:(id)arg1;
@property(copy) NSURL *destinationURL;
@property(retain) NSPopUpButton *destinationWorkspacePopUp; // @synthesize destinationWorkspacePopUp=_destinationWorkspacePopUp;
- (void)didInstantiateItems:(id)arg1;
- (id)finalURLForSelectedURL:(id)arg1;
- (void)finishWithCompletionBlock:(id)arg1;
- (void)handleSavePanelResult:(long long)arg1 completionBlock:(id)arg2;
- (void)handleSavePanelResult:(long long)arg1 url:(id)arg2;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;
- (void)instantiateFileTemplatesWithCompletionBlock:(id)arg1;
- (BOOL)panel:(id)arg1 shouldEnableURL:(id)arg2;
- (BOOL)panel:(id)arg1 validateURL:(id)arg2 error:(id *)arg3;
- (void)primitiveInvalidate;
- (void)setAssistantContext:(id)arg1;
- (void)setupSavePanel:(id)arg1;
- (BOOL)shouldShowAccessoryView;
- (BOOL)shouldShowDestinationGroupPopUp;
- (BOOL)shouldShowDestinationWorkspacePopUp;
- (id)targetWorkspacesForDestinationManager:(id)arg1;
- (BOOL)validateCanFinish;
- (void)viewDidInstall;
- (void)viewWillUninstall;
- (void)willResignCurrentAssistantInAssistantWindowController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

