/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

#import "IDECommandHandler.h"
#import "IDECommandHandlerVendor.h"

@class NSString;

@interface IDETestingCommands : NSObject <IDECommandHandlerVendor, IDECommandHandler>
{
    id <IDESelectionSource> _selectionSource;
}

+ (id)_sharedHandler;
+ (id)handlerForAction:(SEL)arg1 withSelectionSource:(id)arg2;
- (void).cxx_destruct;
- (id)_currentWorkspace;
- (id)_localizedString:(id)arg1;
- (void)contextMenu_profileTest:(id)arg1;
- (void)contextMenu_runTest:(id)arg1;
- (void)profileAgain:(id)arg1;
- (void)profileSelectedItems:(id)arg1;
@property(retain) id <IDESelectionSource> selectionSource; // @synthesize selectionSource=_selectionSource;
- (void)testAgain:(id)arg1;
- (void)testSelectedItems:(id)arg1;
- (BOOL)validateUserInterfaceItem:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

