/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDETemplateInstantiationAssistant.h>

#import "NSComboBoxDataSource.h"

@class NSArray, NSMutableDictionary, NSString, NSTextField, NSView;

@interface IDETemplateOptionsAssistant : IDETemplateInstantiationAssistant <NSComboBoxDataSource>
{
    NSView *_mainView;
    NSArray *_classNames;
    NSMutableDictionary *_controlsForOptionIds;
    BOOL _canGoForward;
    NSTextField *_firstTextField;
    NSArray *_allSortedOptions;
}

- (void).cxx_destruct;
- (void)_setAccessibilityForCell:(id)arg1 withOption:(id)arg2 prefix:(id)arg3;
- (void)_setControl:(id)arg1 forOptionIdentifier:(id)arg2;
- (id)additionalOptions;
@property(readonly) NSArray *allSortedOptions; // @synthesize allSortedOptions=_allSortedOptions;
- (id)assistantTitle;
@property BOOL canGoForward; // @synthesize canGoForward=_canGoForward;
- (id)classNamesForComboBox:(id)arg1;
- (id)comboBox:(id)arg1 completedString:(id)arg2;
- (unsigned long long)comboBox:(id)arg1 indexOfItemWithStringValue:(id)arg2;
- (id)comboBox:(id)arg1 objectValueForItemAtIndex:(long long)arg2;
- (id)controlForOptionIdentifier:(id)arg1;
- (id)createControlForOption:(id)arg1;
- (id)createLabelForOption:(id)arg1;
@property(retain) NSTextField *firstTextField; // @synthesize firstTextField=_firstTextField;
- (void)loadView;
- (id)nextAssistantIdentifier;
- (long long)numberOfItemsInComboBox:(id)arg1;
- (double)requiredViewSpacingForOption:(id)arg1;
- (void)restoreSelectionFromUserDefaults;
- (void)setAssistantContext:(id)arg1;
- (void)setupOptionViews;
- (void)updateOptions:(id)arg1;
- (void)viewDidInstall;
- (void)viewWillUninstall;
- (void)writeStateToUserDefaults;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

