/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "IDETestObserver.h"

@protocol IDETestsInTestableObserver <IDETestObserver>
- (void)testablesChanged:(id)arg1;
@end

