/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEViewController.h>

#import "IDEFilePickerViewDelegate.h"
#import "IDETestsInTestableObserver.h"

@class DVTBorderedView, DVTChoice, DVTGradientImageButton, DVTNotificationToken, DVTObservingToken, DVTOutlineView, DVTSearchField, DVTTabChooserView, IDEArgumentsCapsuleSheetController, IDECapsuleListView, IDEDebuggerSpecifier, IDEEnvironmentVariablesCapsuleSheetController, IDEScheme, IDESimulateLocationMenuController, IDETestSchemeAction, IDEWorkspace, NSArray, NSPopUpButton, NSString, NSTabView, NSTableColumn, NSTextField;

@interface IDETestRunPhaseSheetController : IDEViewController <IDEFilePickerViewDelegate, IDETestsInTestableObserver>
{
    DVTOutlineView *_outlineView;
    DVTGradientImageButton *_addButton;
    DVTGradientImageButton *_deleteButton;
    DVTBorderedView *_topBorderedView;
    DVTSearchField *_searchField;
    DVTTabChooserView *_tabChooser;
    DVTBorderedView *_useRunActionOptionsBorderedView;
    IDECapsuleListView *_capsuleListView;
    DVTBorderedView *_optionsBorderedView;
    NSPopUpButton *_macroExpansionRunnableBuildablesPopUp;
    NSTextField *_macroExpansionDescription;
    NSTabView *_tabView;
    NSTableColumn *_deviceAppDataPackagesColumn;
    NSTableColumn *_locationColumn;
    DVTChoice *_infoChoice;
    DVTChoice *_conditionsChoice;
    IDEArgumentsCapsuleSheetController *_argumentsViewController;
    IDEEnvironmentVariablesCapsuleSheetController *_environmentVariablesViewController;
    IDEScheme *_runContext;
    IDEWorkspace *_workspace;
    IDETestSchemeAction *_runPhase;
    NSArray *_debuggerSpecifiers;
    NSString *_filterString;
    DVTObservingToken *_testableReferenceObserver;
    DVTObservingToken *_launchActionArgsEnvLinkObservingToken;
    DVTObservingToken *_macroExpansionReferenceObservingToken;
    DVTObservingToken *_runContextObservingToken;
    DVTNotificationToken *_buildablesToken;
    IDESimulateLocationMenuController *_simulateLocationMenuController;
}

+ (void)initialize;
- (void).cxx_destruct;
- (BOOL)_getItemsToDelete:(id *)arg1;
- (id)_iconForBuildable:(id)arg1;
- (void)_macroExpansionRunnableBuildableSelected:(id)arg1;
- (void)_runDestinationChanged;
- (void)_selectDeviceAppDataPackage:(id)arg1;
- (void)_selectMenuItemForDeviceApplicationPackageForCell:(id)arg1 forItem:(id)arg2;
- (void)_selectMenuItemForLocationForCell:(id)arg1 forItem:(id)arg2;
- (void)_selectedSchemeChanged:(id)arg1;
- (void)_setLauncherBasedOnSelectedDebugger;
- (void)_setupDeviceAppDataUI;
- (void)_setupLocationUI;
- (void)_updateDeleteButton;
- (void)_updateMacroExpansionDescriptionForSelectedItem;
- (void)_updateMacroExpansionRunnablePopUp;
- (void)_updateMacroExpansionRunnablePopUpSelection;
- (void)addBlueprintsAction:(id)arg1;
- (BOOL)canExpandTestableReference:(id)arg1;
- (id)capsuleListView:(id)arg1 viewControllerForRow:(long long)arg2;
- (void)clearHighlightsInCapsuleView;
- (id)currentToggleItemsAndEnable:(char *)arg1;
@property(retain, nonatomic) NSArray *debuggerSpecifiers; // @synthesize debuggerSpecifiers=_debuggerSpecifiers;
- (id)debuggerSpecifiersForCurrentPlatform;
- (void)deleteBlueprintsAction:(id)arg1;
- (BOOL)doesFilterStringIncludeName:(id)arg1;
- (BOOL)doesFilterStringIncludeTest:(id)arg1;
- (BOOL)doesFilterStringIncludeTestable:(id)arg1;
- (id)dvtExtraBindings;
@property(copy, nonatomic) NSString *filterString; // @synthesize filterString=_filterString;
- (id)filteredTestableReferences;
- (id)filteredTests:(id)arg1;
- (BOOL)isTestActive:(id)arg1;
- (BOOL)isTestEditable:(id)arg1;
- (void)loadView;
- (long long)numberOfObjectsInCapsuleListView:(id)arg1;
- (BOOL)outlineView:(id)arg1 acceptDrop:(id)arg2 item:(id)arg3 childIndex:(long long)arg4;
- (id)outlineView:(id)arg1 child:(long long)arg2 ofItem:(id)arg3;
- (BOOL)outlineView:(id)arg1 doCommandBySelector:(SEL)arg2;
- (BOOL)outlineView:(id)arg1 isItemExpandable:(id)arg2;
- (long long)outlineView:(id)arg1 numberOfChildrenOfItem:(id)arg2;
- (id)outlineView:(id)arg1 objectValueForTableColumn:(id)arg2 byItem:(id)arg3;
- (void)outlineView:(id)arg1 setObjectValue:(id)arg2 forTableColumn:(id)arg3 byItem:(id)arg4;
- (BOOL)outlineView:(id)arg1 shouldSelectItem:(id)arg2;
- (BOOL)outlineView:(id)arg1 shouldTrackCell:(id)arg2 forTableColumn:(id)arg3 item:(id)arg4;
- (unsigned long long)outlineView:(id)arg1 validateDrop:(id)arg2 proposedItem:(id)arg3 proposedChildIndex:(long long)arg4;
- (void)outlineView:(id)arg1 willDisplayCell:(id)arg2 forTableColumn:(id)arg3 item:(id)arg4;
- (BOOL)outlineView:(id)arg1 writeItems:(id)arg2 toPasteboard:(id)arg3;
- (void)outlineViewSelectionDidChange:(id)arg1;
- (void)primitiveInvalidate;
@property(retain) IDEScheme *runContext; // @synthesize runContext=_runContext;
@property(retain) IDETestSchemeAction *runPhase; // @synthesize runPhase=_runPhase;
@property(retain) IDEDebuggerSpecifier *selectedDebuggerSpecifier;
- (void)setItem:(id)arg1 enabled:(BOOL)arg2 recursively:(BOOL)arg3;
@property(retain) DVTTabChooserView *tabChooser; // @synthesize tabChooser=_tabChooser;
@property(retain) IDEWorkspace *workspace;
- (id)testableReferenceForTest:(id)arg1;
- (void)testablesChanged:(id)arg1;
- (void)testsChanged:(id)arg1;
- (void)toggleTests:(id)arg1;
- (void)updateBoundContent;
- (void)updateBoundIDERunContextBinding;
- (void)updateBoundIDEWorkspaceBinding;
- (BOOL)validateMenuItem:(id)arg1;
- (void)viewDidInstall;
- (void)viewWillUninstall;
- (void)workspaceReferencedTestablesChanged;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

