/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import <IDEKit/IDEAssistantContext.h>

#import "NSCopying.h"

@class DVTFilePath, IDEContainerItem, IDEGroup, IDETemplate, IDEWorkspaceDocument, NSArray;

@interface IDETemplateInstantiationContext : IDEAssistantContext <NSCopying>
{
    IDETemplate *_documentTemplate;
    DVTFilePath *_documentFilePath;
    NSArray *_instantiatedItems;
    IDEContainerItem *_primaryInstantiatedItem;
    IDEGroup *_destinationGroup;
    unsigned long long _destinationIndex;
    NSArray *_destinationBuildables;
    NSArray *_templateSections;
    IDEWorkspaceDocument *_createdDocument;
}

- (void).cxx_destruct;
- (void)_asyncFinishTemplateInstantiationAfterCreatingWorkspaceDocumentWithCompletionHandler:(id)arg1;
@property(readonly) BOOL alwaysShowProjectNavigator;
- (void)asyncFinishTemplateInstantiationWithCompletionHandler:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
@property(retain) IDEWorkspaceDocument *createdDocument; // @synthesize createdDocument=_createdDocument;
- (id)destinationBlueprintProvider;
@property(copy) NSArray *destinationBuildables; // @synthesize destinationBuildables=_destinationBuildables;
@property(retain) IDEGroup *destinationGroup; // @synthesize destinationGroup=_destinationGroup;
@property unsigned long long destinationIndex; // @synthesize destinationIndex=_destinationIndex;
@property(retain) DVTFilePath *documentFilePath; // @synthesize documentFilePath=_documentFilePath;
@property(retain, nonatomic) IDETemplate *documentTemplate; // @synthesize documentTemplate=_documentTemplate;
@property(copy) NSArray *instantiatedItems; // @synthesize instantiatedItems=_instantiatedItems;
- (void)loadAvailableTemplatesOfKind:(id)arg1 navigableItemCoordinator:(id)arg2;
@property(retain) IDEContainerItem *primaryInstantiatedItem; // @synthesize primaryInstantiatedItem=_primaryInstantiatedItem;
@property(copy) NSArray *templateSections; // @synthesize templateSections=_templateSections;
@property(readonly, copy) NSArray *targetWorkspaces;

@end

