/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol IDEURLHandler <NSObject>
+ (BOOL)shouldRegisterURLHandlerForScheme:(id)arg1;

@optional
+ (void)handleURL:(id)arg1 completionHandler:(id)arg2;
+ (BOOL)handleURL:(id)arg1 error:(id *)arg2;
@end

