/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSImage.h"

@interface NSImage (IDENSImageAdditions)
+ (id)ide_appleIDAccountSmallImage;
+ (id)ide_appleIDImage;
+ (id)ide_assistantBackgroundImage;
+ (id)ide_contextPhaseBuildImage;
+ (id)ide_repositoryAccountSmallImage;
+ (id)ide_serverAccountSmallImage;
+ (id)ide_serverImage;
+ (id)ide_sourceControlBranch;
+ (id)ide_sourceControlBranchFolderImage;
+ (id)ide_sourceControlRemotesFolderImage;
+ (id)ide_sourceControlRepository;
+ (id)ide_sourceControlRevision;
+ (id)ide_sourceControlTagsFolderImage;
+ (id)ide_sourceControlTrunkFolderImage;
+ (id)ide_sourceControlWorkingCopy;
@end

