/*
 *     Generated by class-dump 3.4 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
 */

#import "NSObject.h"

@protocol NSPopoverDelegate <NSObject>

@optional
- (id)detachableWindowForPopover:(id)arg1;
- (void)popoverDidClose:(id)arg1;
- (void)popoverDidShow:(id)arg1;
- (BOOL)popoverShouldClose:(id)arg1;
- (BOOL)popoverShouldDetach:(id)arg1;
- (void)popoverWillClose:(id)arg1;
- (void)popoverWillShow:(id)arg1;
@end

